### PR TITLE
updated upload spreadsheet version

### PR DESCRIPTION
**Pull request by only1chunts**
# Pull request for issue: NA

This is a pull request for the following functionalities:
* additional items on the checklist tab
* updated list of attributes in the CV tab
* updated list of file-types in the file tab dropdown menu

Hopefully it will reduce the number of attributes that are not valid as the list in the spreadsheet now includes all the valid options (upto 20-May-2024)
The file-types list had not been updated in several of the previous versions, so it was a good time to update that.
Hopefully the additional checklist items will remind curators to check:
- the funding field format
- the readme_DOI.txt is included in the files tab
- the files list in the userbox exactly matches the files list in the Files tab

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @only1chunts,

**question**: Do you have an example of a filled-in spread sheet that uses the new template?
We need to test that the spreadsheet upload tool can still ingest it

**Comment by only1chunts** [comment]
test spreadsheet added.

**Comment by rija** [comment]
HI @pli888 
I was thinking, maybe you can be the first to review this PR as you have the appropriate context at the most freshest in mind.

**Review by pli888 — COMMENTED** [review]
**praise**: New Excel template is more informative
**suggestion**: New template file name is called `GigaDBUpload-template_v20240520.xls` but I think it would be more memorable if it was named `GigaDBUpload-template_v19.xls` which is consistent with previous template files and also if we need to refer to it in discussions, etc.
**question**: In CV tab, why are some attribute rows duplicated? For example:

| attributes | attribute ID number | Attribute definition |
|------------|---------------------|----------------------|
| SWH | 1088 | Software Heritage Library ID, a globally unique persistent identifier of a piece of software archived with the Software Heritage Library. |
| SWH | 1088 | Software Heritage Library ID, a globally unique persistent identifier of a piece of software archived with the Software Heritage Library.
| Batch | 1099 | Batch [NCIT:C67073] A quantity of people or things treated or regarded as a group, especially when subdivided from a larger group. |
| Batch | 1099 | Batch [NCIT:C67073] A quantity of people or things treated or regarded as a group, especially when subdivided from a larger group. |

**issue (non-blocking)**: This is an observation and this PR can be merged when approved but the `GigaDBUpload-template_v20240520-test-202528.xls` test file cannot be uploaded into the `dev` environment GigaDB by Excel upload tool.
**suggestion**: When this PR is merged, create a ticket to report various `data/dev/*.csv` files reference data will need to be updated so that they correspond with all the new attributes in this version of the Excel template in CV tab
**chore**: Fix typo in Checklist tab: Are the Funding information formatted correctly with 4 parts per object separated by "," and each object `sperated` by ";"

**Comment by only1chunts** [comment]
Hi Peter,
I am unable to access GitHub from here, but you are welcome to rename the
file as you see fit.
The attribute list on the CSV tab includes both the full name and short
names as options, hence in cases when those names are the same it looks
like the same thin appearing in the list twice.
I'm not sure what "*suggestion*: When this PR is merged, create a ticket to
report various data/dev/*.csv files reference data will need to be updated
so that they correspond with all the new attributes in this version of the
Excel template in CV tab" means? but if its something to do with the set of
allowed attributes, please can that be taken directly from the live
database instead of from a static copy held in the excel file?
Thanks
Chris

**Review by pli888 — APPROVED** [review]
This PR looks good to approve now.

**Pull request merged**
