### PR TITLE
Skeleton structure for GigaDB CLI tool and stub classes and methods for Files url updater

### PR DESCRIPTION
**Pull request by rija**
Hi @pli888, @kencho51

This pull request is for skeleton project structure for the tool to update the dataset files url on production database.
It doesn't do anything yet, there is no business logic, but the classes and method stubs are there and the automated tests apparatus (based on Codeception) is set up and working 

we would need this merged to ``develop`` at such a stage so that:

1. It shows the structure and design I plan for this kind of tool. Easier to feedback and correct now that there's nothing yet
2. If any of you want to pick up one the task associated with Sprint story #617, you can branch out of  ``develop`` and build upon that code without spending time in setting things up, while making it a bit easier to merge the various tasks afterwards
3. When there's a need to build a non-trivial GigaDB-related tool with test automation (e.g: backup tool), you can branch out of  ``develop`` and copy this code into a new tool (if not needing exotic dependencies like a legacy postgres, the commands should also run without Docker installed)
4. It reduces time to review upcoming related pull requests as by then the design and structure would have been understood already
5. It will help reviewing aspects of the ``fuw-cicd`` branch as the code design and tests are pulled from the CLI tools on that branch (notably for #643 and #647)
6. It is totally independent from the main gigadb webapp, so no impact to gigadb legacy codebase and operation anyway 

The ``gigadb/app/tools/files-url-updater/README.md`` lists the commands that can be run, they should all be executing without error.

### a. The files url updater can be considered a command associated with GigaDB:

* It has one unique job, which it performs when it is been passed a list of dataset ids. Otherwise it does nothing
* It doesn't require a graphical user interface
* It needs to log what it does and success and failure
* it needs a dry-run mode

### b. We have a detailed acceptance test scenarios to implement, that need to be co-located with the script  and the application needs access to a remote target database server

* This cannot just be a simple bash script in ops/scripts.
* But it's not a complete service like FUW, it's still attached to GigaDB.
* It's not a worker either because we use it interactively, so it doesn't go into ``gigadb/app/worker``.
* The target database server won't be the default one used by the main Gigadb codebase
* Yii2 basic template will setup Codeception for unit, functional and acceptance tests
* so I can create a distinct Yii2 basic application in ``gigadb/app/tools`` as ``files-url-updater``
* There is no need to use the Yii2 advanced template

### c. The application needs access to an old  version of  PostgreSQL database 

So the client library needs to be old (I think maximum 9.3)

We can run the command in a docker container defined by a Dockerfile based on Debian Stretch (that's what's used on ``fuw-cicd`` branch) and install the client library for an appropriately old version of PosgreSQL from PostgreSQL Debian package repository.

We cannot base the Dockerfile on Debian Jessie (which is used by the containers on ``develop`` branch)
as I couldn't find old PostgreSQL client libraries packages for it, and it's good thing to start moving away from the Debian Jessie as it 's too old a version.

The PHP image for the container I want to host the tool in is the official one, but they don't have a Stretch version for PHP 7.4, so we will use Debian Buster, its successor.

# Pull request for issue: #629

This is a pull request for the following functionalities:

n/a

## Changes to the database schema

n/a

## Changes to the model classes

n/a

## Changes to the controller classes

n/a

## Changes to the view template files

n/a

## Changes to the style

n/a

## Changes to the tests

n/a

## Changes to the provisioning

n/a

### CODE REVIEW

**Review by pli888 — COMMENTED** [review]
This pull request is good for us to understand the project structure for a standalone GigaDB-related tool in case @kencho51 or I need to implement such a tool in the future. However, it will be populated with business logic for the files url updater tool in a future pull request. This means that we will need to delete this business logic code after we copy this code before starting to create a new tool. Maybe some comments can be added into the code so that we know exactly what code needs adding into classes like the Controller, etc.

Maybe in the future, a [Gii](https://www.yiiframework.com/extension/yiisoft/yii2-gii/doc/guide/2.2/en/topics-creating-your-own-templates) template code generator can be created to auto-generate this skeleton project structure?

To really understand how this project structure works to implement a standalone GigaDB-related tool, I would need to use it. I can try to use this skeleton project structure to implement the Tencent back up tool.

**Comment by rija** [comment]
@pli888 insightful observations. The generator could either be a Gii command or a Composer command (that's what I used to generate that project). The scope of Gii might a bit limited as it doesn't know how to interact with Composer, and having a project with the right dependencies could be very useful.

**Comment by kencho51** [comment]
I think this PR looks good to me. 
But would it be a concern that the code base will become so big if we keep adding tools to GigaDB? 
Would it be possible to have a separate repo for the GigaDB tools?

**Review by kencho51 — DISMISSED** [review]
I think this PR looks good to me.
But would it be a concern that the code base will become so big if we keep adding tools to GigaDB?
Would it be possible to have a separate repo for the GigaDB tools?

**Review by kencho51 — COMMENTED** [review]
I think this PR looks good to me.
But would it be a concern that the code base will become so big if we keep adding tools to GigaDB?
Would it be possible to have a separate repo for the GigaDB tools?

**Comment by pli888** [comment]
Closing this PR because the final working version of the Files URL Updater tool 
was merged into the develop branch by PR #707.

**Pull request closed without merging**
