### PR TITLE
Behave tests

### PR DESCRIPTION
**Pull request by lump1k**
# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

Behave tests for Dataset Creating process
Located at /protected/tests/behave
To run it please use the command
docker-compose run --rm behave-test

You can test in your local machine, but you should change database in protected/config/db.json to gigadb_test

## Changes to the database schema

<Insert description of changes to database schema>

## Changes to the model classes

<Insert description of changes to model classes>

## Changes to the controller classes

<Insert description of changes to controller classes>

## Changes to the view template files

<Insert description of changes to view template files>

## Changes to the style

<Insert description of changes to the look and feel of any web pages>

## Changes to the tests

<Insert description of changes to the test code>

## Changes to the provisioning

<Insert description of any changes related to the building of the GigaDB application>

### CODE REVIEW

**Comment by pli888** [comment]
> You can test in your local machine, but you should change database in protected/config/db.json to gigadb_test

Can you provide step-by-step instructions for running the tests locally please? I have the error message below and I am not sure what configuration changes I need to make to `db.json` or `db_test.json`:

```
Preparing the database for bahave tests...
+ exec
+ exec
+ psql -U gigadb -h database
/var/www/tests/behave_tests: line 22: GIGADB_TEST_DB: unbound variable
```

To generate the above error, my `db.json contained:
```
{
    "database": "gigadb_test",
    "host"    : "database",
    "user"    : "test",
    "password": "test"
}
```

**Comment by lump1k** [comment]
Hello, Peter!
Please add to .secrets file this line:
GIGADB_TEST_DB=gigadb_test

**Comment by pli888** [comment]
I am having problems running your tests locally through to completion. The tests hang when I get to a certain point. See this [log file](https://www.dropbox.com/s/t4vxzsx29zh1o1b/behave.log?dl=0).

**Comment by pli888** [comment]
Actually, it would be useful if you could document the steps to run your tests from a new build which I can then follow on my `gigadb-website` application set up.

**Comment by pli888** [comment]
@lump1k By playing around with the configuration, I can get the tests to run to completion but with none of them passing. See this new [log file](https://www.dropbox.com/s/wjjxbmu3vknrutq/behave.log.2?dl=0).

**Comment by lump1k** [comment]
@pli888 I hope I understood why this problem happened. It's because you open another session for this database somewhere and before running the test we couldnt drop it.
http://www.leeladharan.com/drop-a-postgresql-database-if-there-are-active-connections-to-it
I found this solution and it helps me when I also open some another connection. I pushed this fix. Can you please check it?

**Comment by pli888** [comment]
I am still having problems with running your tests with your latest fix. From downloading the code from your branch, can you tell me the list of command-line steps for executing your tests please?

**Comment by lump1k** [comment]
docker-compose run --rm webapp
docker-compose run --rm behave-test
and then should be 
http://i.imgur.com/aLL2yBb.png

**Comment by pli888** [comment]
Unfortunately, the tests are still failing for me with the latest code commit. Here is the [log](https://www.dropbox.com/s/5w5dc2lioh5brce/behave.log.3?dl=0).

**Comment by lump1k** [comment]
It's strange..
Can you please rechek if you get the lastest version just to be sure
And then remove deployment_behave-test  image and try to run tests again.
I hope it will help

**Comment by pli888** [comment]
I confirm that your code I use is the latest version and I have deleted and re-rebuilt the deployment_behave-test image but the tests still fail for me. This is the [log](https://www.dropbox.com/s/0160ogm7wncl57m/behave.log.4?dl=0) from running the tests when I do this.

**Comment by lump1k** [comment]
@pli888 I decited to do everything from the begginig.

1) I made clone https://github.com/lump1k/gigadb-website.git

2) git checkout sergey
cp ops/configuration/variables/env-sample .env
docker-compose run --rm config
cp ops/configuration/variables/secrets-sample .secrets

and I changed this empty file to file what i have in my old project (you sent me it before)
https://www.dropbox.com/s/fg95t3ie63w9qdm/1.secrets?dl=0 (you can check there what i have)

3) composer install --ignore-platform-reqs

4)  changed protected/config/db.json to
{
    "database": "gigadb_test",
    "host"    : "database",
    "user"    : "gigadb",
    "password": "vagrant"
}

5) docker-compose run --rm webapp
6) docker-compose run --rm behave-test

And it works for me.
Maybe you have some error when you try to go on this page?
http://gigadb.gigasciencejournal.com:9170/site/login
Because as I see from logs it cant find input fields for Email Address name and Password

**Comment by pli888** [comment]
My `db.json` was wrong but I did tell you its contents 6 days ago (see above). When my `db.json` is corrected, I can execute some tests successfully using your configuration:
```
1 feature passed, 7 failed, 0 skipped
25 scenarios passed, 23 failed, 0 skipped, 5 untested
329 steps passed, 16 failed, 29 skipped, 0 undefined, 131 untested
Took 61m58.392s
```

This is the [log file](https://www.dropbox.com/s/ztflk7feielfx1z/behave.log.5?dl=0).

**Comment by lump1k** [comment]
It's hard to understand what happens there. Can you please  send me all files what you have in this folder protected/tests/behave/report?

**Comment by pli888** [comment]
There files in `protected/tests/behave/report` are [here](protected/tests/behave/report).

**Comment by lump1k** [comment]
http://joxi.ru/Vm66My6u47kX4m
Peter, I have it by your url

**Comment by pli888** [comment]
@lump1k Sorry, I have corrected the Dropbox link now.

**Comment by pli888** [comment]
@lump1k Using my laptop, I have improved on the results of your Python tests:
```
Failing scenarios:
  protected/tests/behave/features/additional_information_tab.feature:11  I click Yes for Public data archive links
  protected/tests/behave/features/additional_information_tab.feature:33  I click Yes button for Related GigaDB Datasets
  protected/tests/behave/features/additional_information_tab.feature:40  I click No button for Project links
  protected/tests/behave/features/additional_information_tab.feature:93  I click yes button to provide CodeOceans “Embed code widget” and check if it is saved into DB
  protected/tests/behave/features/additional_information_tab.feature:168  Delete Related DOI and Relationship to Related GigaDB Datasets
  protected/tests/behave/features/additional_information_tab.feature:206  I add manuscript link and check if it is saved into DB by clicking Next button
  protected/tests/behave/features/dataset_submission.feature:4  The user navigates to "Dataset submission selection" page
  protected/tests/behave/features/file_tab.feature:27  the user sees an error message when completing submission without description
  protected/tests/behave/features/file_tab.feature:52  the user uploads metadata file on File tab

5 features passed, 3 failed, 0 skipped
44 scenarios passed, 9 failed, 0 skipped
432 steps passed, 1 failed, 3 skipped, 0 undefined, 69 untested
Took 20m13.438s
```

**Comment by pli888** [comment]
@lump1k Here is an update. I re-ran the tests today and got the following results which are different to those above:
```
Failing scenarios:
  protected/tests/behave/features/additional_information_tab.feature:33  I click Yes button for Related GigaDB Datasets
  protected/tests/behave/features/additional_information_tab.feature:40  I click No button for Project links
  protected/tests/behave/features/additional_information_tab.feature:57  I click No button for all Other links I click Next button
  protected/tests/behave/features/additional_information_tab.feature:157  Add Related DOI and Relationship to Related GigaDB Datasets
  protected/tests/behave/features/additional_information_tab.feature:206  I add manuscript link and check if it is saved into DB by clicking Next button
  protected/tests/behave/features/additional_information_tab.feature:245  I add SketchFab Link and check if it is saved into DB by clicking Next button
  protected/tests/behave/features/additional_information_tab.feature:264  I Add CodeOceans “Embed code widget” and check if it is saved into DB by clicking Next
  protected/tests/behave/features/create_dataset.feature:72  Image upload
  protected/tests/behave/features/fundings.feature:36  I add a grant to the table by clicking NEXT button and I check if it is saved into DB
  protected/tests/behave/features/samples.feature:52  when Save button clicked the dated is saved to DB on Sample tab
  protected/tests/behave/features/samples.feature:60  when adding the same Sample ID twice the error pop-up appears

3 features passed, 5 failed, 0 skipped
40 scenarios passed, 11 failed, 0 skipped, 2 untested
391 steps passed, 2 failed, 1 skipped, 0 undefined, 111 untested
Took 18m36.250s
```

Looking at the scenarios that fail, most of them have the following error:
```
The scenarios that fail have this problem:

HOOK-ERROR in before_scenario: ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

The above error message is pretty obscure but I am looking at potential fixes.

**Comment by pli888** [comment]
@lump1k I have run your tests on my faster office PC but I get similar results with tests failing:
```
Failing scenarios:
  protected/tests/behave/features/additional_information_tab.feature:4  I click No for Public data archive links
  protected/tests/behave/features/additional_information_tab.feature:40  I click No button for Project links
  protected/tests/behave/features/additional_information_tab.feature:93  I click yes button to provide CodeOceans “Embed code widget” and check if it is saved into DB
  protected/tests/behave/features/additional_information_tab.feature:113  I click yes button to  provide the DOI or URL on Other links block and check if it is saved into DB
  protected/tests/behave/features/fundings.feature:14  I add a grant to the table
  protected/tests/behave/features/fundings.feature:26  delete grant from the table
  protected/tests/behave/features/samples.feature:18  Warn the user that all data in table will be over-written when applying a template on Sample table with data
  protected/tests/behave/features/samples.feature:44  recently submitted dataset is highlighted in table

2 features passed, 6 failed, 0 skipped
38 scenarios passed, 8 failed, 0 skipped, 7 untested
378 steps passed, 0 failed, 0 skipped, 0 undefined, 127 untested
Took 13m13.669s
```

The tests that fail have the same HOOK-ERROR message that I get when I run your tests on my laptop:
```
HOOK-ERROR in before_scenario: ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

  Scenario: I click No for Public data archive links [90m                  # protected/tests/behave/features/additional_information_tab.feature:4[0m
    [36mGiven [0m[36mI am on "site/login" and I login[0m[90m                             # None[0m
    [36mGiven [0m[36murl address "/datasetSubmission/additionalManagement/id/322"[0m[90m # None[0m
    [36mWhen [0m[36mI click No button for Public data archive links[0m[90m               # None[0m
    [36mThen [0m[36m"Related GigaDB Datasets" block appears[0m[90m                       # None[0m
```

**Comment by pli888** [comment]
@lump1k I have managed to run and pass all your tests:
```
8 features passed, 0 failed, 0 skipped
53 scenarios passed, 0 failed, 0 skipped
505 steps passed, 0 failed, 0 skipped, 0 undefined
Took 18m40.524s
+ echo '...behave tests finished'
...behave tests finished
+ echo 'Done!'
Done!
```

The problem appears to be related to this [issue](https://github.com/SeleniumHQ/selenium/issues/5296). Selenium version `3.141.0` is being used in your `behave-test` Docker container. When I downgrade Selenium to version `3.8.0`, all your tests run fine.

To downgrade the version of Selenium, I included the code below in the `Behave-Dockerfile`:
```
# Force reinstall selenium version 3.8.0
RUN pip3 install selenium==3.8.0 --force-reinstall
```

The fix to execute your tests on my PC setup is to pin the Selenium version to `3.8.0`.

**Comment by pli888** [comment]
@lump1k I want to try to create a dataset entry using your submission wizard with the minimum amount of data possible so I can test the whole procedure. Regarding the `Sample` tab, is it essential to provide sample information? I do not have to provide sample information on the [staging server](https://gigadb-staging.gigatools.net) and I can click the `Next` button to get to the `End DatasetSubmission` page.

However, on a local GigaDB application, I click `Next` and this results in an error message.
error

**Comment by pli888** [comment]
@lump1k Also, can you confirm that images uploaded using the `Study` tab actually exist as image files in your `/var/www/protected/config/../../images/uploads` directory please? I seem to be having problems with image upload.

**Comment by lump1k** [comment]
Hello, Peter!
About first one issue. Maybe you forgot to run
docker-compose run --rm  application ./protected/yiic templates add
in your local pc. This comman also will add a lot of attributtes fo templates if they doesnt exist.
This error happens when you try to add  attribute which doesnt exist in table attribute

**Comment by lump1k** [comment]
About the second one. I think the problem is releated with container deployment_web_1. You should use volumes for images/uploads. I hope it will help

**Comment by pli888** [comment]
> About the second one. I think the problem is releated with container deployment_web_1. You should use volumes for images/uploads. I hope it will help

Can you include this configuration detail from `docker-compose.yml` in this pull request please? It is helpful if we both have the same configuration for testing purposes.

**Comment by pli888** [comment]
> Maybe you forgot to run `docker-compose run --rm application ./protected/yiic templates add`
in your local pc. This comman also will add a lot of attributtes fo templates if they doesnt exist.
This error happens when you try to add attribute which doesnt exist in table attribute

I am pretty sure I ran the `templates add` command because there are `sample_template-*.txt` files in the `gigadb-website/files/templates` directory. If I did not run the command then these templates files would not be there - is this correct?

**Comment by lump1k** [comment]
> > About the second one. I think the problem is releated with container deployment_web_1. You should use volumes for images/uploads. I hope it will help
> 
> @lump1k Can you include this configuration detail from `docker-compose.yml` in this pull request please? It is helpful if we both have the same configuration for testing purposes.

ops/deployment/docker-compose.yml
I adde this line 
- ${APPLICATION}/шьфпуіuploads:/var/www/images/uploads
to web/volumes
Can you check please if now you can see the url with image?

**Comment by lump1k** [comment]
> > Maybe you forgot to run `docker-compose run --rm application ./protected/yiic templates add`
> > in your local pc. This comman also will add a lot of attributtes fo templates if they doesnt exist.
> > This error happens when you try to add attribute which doesnt exist in table attribute
> 
> I am pretty sure I ran the `templates add` command because there are `sample_template-*.txt` files in the `gigadb-website/files/templates` directory. If I did not run the command then these templates files would not be there - is this correct?

this commad just parse this files and creates templates in database. if you ran it you should see templates in choose a template select on Sample Tab

**Comment by pli888** [comment]
>I adde this line

>${APPLICATION}/шьфпуіuploads:/var/www/images/uploads
to web/volumes
Can you check please if now you can see the url with image?

The image upload works but only with jpeg image files. We need image upload to work with png image files too.

**Comment by pli888** [comment]
> this commad just parse this files and creates templates in database. if you ran it you should see templates in choose a template select on Sample Tab

This is the procedure I use to start a local GigaDB:
```
$ docker-compose run --rm config
$ docker-compose run --rm webapp
# Make WL database schema changes
$ docker-compose run --rm application ./protected/yiic migrate --interactive=0
# Add templates
$ docker-compose run --rm application ./protected/yiic templates add
sample_template-imaging.txt:
Template imaging successfully added.
sample_template-metabolomics.txt:
Template metabolomics successfully added.
sample_template-transcriptomic.txt:
Template transcriptomic successfully added.
sample_template-metagenomic.txt:
Template metagenomic successfully added.
sample_template-genomic.txt:
Template genomic successfully added.
sample_template-epigenomic.txt:
Template epigenomic successfully added.
sample_template-lipidomics.txt:
Template lipidomics successfully added.
```

When I reach the `Sample` tab and I do not want to include any sample information for a dataset so I select `Empty` as my template, I get the `Attribute Name doesn't exist` error message.

template_error

**Comment by lump1k** [comment]
> > this commad just parse this files and creates templates in database. if you ran it you should see templates in choose a template select on Sample Tab
> 
> This is the procedure I use to start a local GigaDB:
> 
> ```
> $ docker-compose run --rm config
> $ docker-compose run --rm webapp
> # Make WL database schema changes
> $ docker-compose run --rm application ./protected/yiic migrate --interactive=0
> # Add templates
> $ docker-compose run --rm application ./protected/yiic templates add
> sample_template-imaging.txt:
> Template imaging successfully added.
> sample_template-metabolomics.txt:
> Template metabolomics successfully added.
> sample_template-transcriptomic.txt:
> Template transcriptomic successfully added.
> sample_template-metagenomic.txt:
> Template metagenomic successfully added.
> sample_template-genomic.txt:
> Template genomic successfully added.
> sample_template-epigenomic.txt:
> Template epigenomic successfully added.
> sample_template-lipidomics.txt:
> Template lipidomics successfully added.
> ```
> 
> When I reach the `Sample` tab and I do not want to include any sample information for a dataset so I select `Empty` as my template, I get the `Attribute Name doesn't exist` error message.
> 
> template_error

I understood why it happens. Chris said that description for samples must be saved like attribute description. But you don't have this attribute in your database. I made some changes and it will create description attribute if it doescnt exist. Please pull my changes

**Comment by lump1k** [comment]
> > I adde this line
> 
> > ${APPLICATION}/шьфпуіuploads:/var/www/images/uploads
> > to web/volumes
> > Can you check please if now you can see the url with image?
> 
> The image upload works but only with `jpeg` image files. We need image upload to work with `png` image files too.
> 
> Also, when an image file has been selected and the `Save` button has been clicked, it still says `no file selected` next to the `Choose File` button:
> 
> problem
> 
> Can you ensure that the name of the image file continues to be displayed after the `Save` button has been clicked please?

Sorry i forgot to check it there with png. but i knew that it must work, because i worked with this esxtention many times before
the problem is:
https://github.com/Gregwar/Image/issues/26
Can you please install this exif extension with PHP?

and about no file selected
For security reasons, the value of a <input type=file> element can only be changed by a user. It's not possible to change the value through JavaScript or HTML.
https://stackoverflow.com/questions/8323010/putting-default-value-in-input-type-file

**Comment by pli888** [comment]
>I understood why it happens. Chris said that description for samples must be saved like attribute description. But you don't have this attribute in your database. I made some changes and it will create description attribute if it doescnt exist. Please pull my changes

OK, this change allows me to complete the data submission procedure with no sample information input.

>Sorry i forgot to check it there with png. but i knew that it must work, because i worked with this esxtension many times before
the problem is: Gregwar/Image#26
Can you please install this exif extension with PHP?

Adding the code below into `ops/packaging/Dockerfile` allows `gregwar/image` package to work with png files:
```
        libmcrypt-dev \
        bc \
        # Install exiftool for gregwar/image package to work with png files
        exiftool

# Install PHP exif extension for gregwar/image to work with png files
RUN docker-php-ext-configure exif && \
    docker-php-ext-install exif && \
    docker-php-ext-enable exif
```

>and about no file selected
For security reasons, the value of a element can only be changed by a user. It's not possible to change the value through JavaScript or HTML.
https://stackoverflow.com/questions/8323010/putting-default-value-in-input-type-file

This behaviour looks strange so is there another solution for this problem? Otherwise, @only1chunts will need to decide whether to keep this behaviour or not.

**Comment by pli888** [comment]
@lump1k Regarding the `funding tab`, the drop down list is empty in a local GigaDB installation.

funding_tab_problem

The drop down list needs to be populated with the names of funding agencies for selection. How can this be done?

**Comment by pli888** [comment]
@lump1k @only1chunts I am testing the Sample tab. When I try to add sample information, I get an error message as shown below:

sample_tab_problem

The error message is not very helpful to a user. If the species name is invalid then what is the correct species name? Changing `homo sapiens` to `Homo sapiens` also results in the same `Row 1: Species Name is invalid` message.

**Comment by pli888** [comment]
@lump1k In the past, you have mentioned problems with sending/receiving emails associated with the dataset submission wizard functionality. Is this still an issue? If so, please report what these issues are and I will look into them.

**Comment by only1chunts** [comment]
@pli888 the species name is usually a drop down menu that auto filters as you type, that way the submitter can easily select the correct species from the list. For some reason now the drop down is not appearing? either the species table in this dev database is incomplete/missing or there is something not working with the page?

**Comment by only1chunts** [comment]
@pli888 regarding the image thing; 
The exif extension looks like a legitimate php thing (https://www.php.net/manual/en/book.exif.php) so is there a problem with having it in the GigaDB php bundle? We do need the image upload to handle png and tif files so I think we need it if its not a security risk or problem?

**Comment by pli888** [comment]
> The exif extension looks like a legitimate php thing (https://www.php.net/manual/en/book.exif.php) so is there a problem with having it in the GigaDB php bundle? We do need the image upload to handle png and tif files so I think we need it if its not a security risk or problem?

There is no security problem, `exiftool` and the `exif` extension was missing from the container so the submission wizard couldn't handle png images during upload. The `Dockerfile` for the `application` image will be updated to include installation of `exiftool` and `exif`.

**Comment by pli888** [comment]
> the species name is usually a drop down menu that auto filters as you type, that way the submitter can easily select the correct species from the list. For some reason now the drop down is not appearing? either the species table in this dev database is incomplete/missing or there is something not working with the page?

@only1chunts OK, I created a new `species` entry for `Homo sapiens` which fixed the `Row 1: Species Name is invalid` error message. No drop down list appears though.

@lump1k When I click the `save` button to store the sample information for the dataset, I get the error message below. Can you take a look at this problem please?

next_sample_tab_problem

**Comment by pli888** [comment]
> When I click the save button to store the sample information for the dataset, I get the error message below. Can you take a look at this problem please? Bear in mind that I am using the test PostgreSQL database that is deployed using ops/configuration/postgresql-conf/bootstrap.sql in my local GigaDB and I want to keep using this. Let me know if this needs updating for your dataset submission wizard.

When a local GigaDB instance is deployed, the `sample_attribute` table contains:

| id | sample_id | attribute_id | value | unit_id |
| -- | --------- | ------------ | ----- | ------- |
| 30060	| 4346 | 422 |David Lambert & BGI | 	
| 30061 | 4346 | 269 | 35.904731 | 127.162202 |
| 30062 | 4347 | 269 | 16.606667 | 49.259444 |

If we check the maximum value in the `id` column from the `sample_attribute` table:
```
SELECT MAX(id) FROM sample_attribute;
```
We find the maximum value is: `30062`.

However, the PostgreSQL DBMS thinks the next value in the sequence is:
```
SELECT nextval('sample_attribute_id_seq');
# next val = 30061
```

The problem here is that first value is higher than the second value so the primary key sequence is out of sync. This suggests that the import/restore is not maintaining the primary key sequence properly. We need to run this to fix problem:
```
SELECT setval('sample_attribute_id_seq', (SELECT MAX(id) FROM sample_attribute)+1);
# setval = 30063
```

The above will allow you to be able to save information about a sample in the `Sample` tab thereby finishing creation of a new dataset entry and display the final `dataset and sample metadata has been received` message.

**Comment by pli888** [comment]
@lump1k When a sample is created using new `Sample ID`, `Species name` and `Description` values on the `Sample` tab, new rows for this sample are created in the `sample`, `attribute` and `sample_attribute` tables. When this sample is deleted on the `Sample` tab, the corresponding entry in the `sample` table is deleted but not in the `sample_attribute` table. Shouldn't this row in the `sample_attribute` table be deleted too?

**Pull request closed without merging**
