### PR TITLE
Update the text content and url link in Advisory Board page

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #160
@only1chunts The text content and url link in the Advisory Board page have been updated.
The `Editorial Board` now points to [here](https://academic.oup.com/gigascience/pages/Editorial_Board), the `Github page` and the `issue ticketing` system points to [here](https://github.com/gigascience/gigadb-website).
However, the `address` in the [contact us](http://gigadb.org/site/contact) form is outdated, it is suggested to fix it by creating a new issue.

### CODE REVIEW

**Comment by only1chunts** [comment]
Hi @kencho51 , that URL is correct for the current production server, if the location of the contact us page is different in the github repo please can you look into why? 
Either 
(a) the production website is out-dated in which case go ahead and make the advisory board page point to the correct place according to the github version, 
OR
(b) the github version was not updated when we made some changes to the public website, in which case we need to identify exactly what changes were made and add those to the GitHub version!
Sorry, but as Peter will probably have told you, the current situation is far from ideal with changes being needed on the public website before the continuous integration system using GitHub has been initiated, Jesse tried to make sure all the changes on the public website were also submitted to the github version, but there are probably some things that got missed.

**Comment by kencho51** [comment]
Hi @only1chunts , I will further look into it and try to update it.

**Comment by pli888** [comment]
> that URL is correct for the current production server, if the location of the contact us page is different in the github repo please can you look into why?

@only1chunts Ken is talking about the postal address for GigaScience on the [Contact Us](http://gigadb.org/site/contact) web page. You will see that it shows the Tai Po address when we are located in Shek Mun now.

**Comment by only1chunts** [comment]
Sorry, I misunderstood! Yes, the postal address should be updated to the new offices please.

**Comment by pli888** [comment]
> Sorry, I misunderstood! Yes, the postal address should be updated to the new offices please.

This will be done for issue #436.

**Pull request merged**
