### PR TITLE
Documentation on how to implement user dropboxes in Wasabi

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1244

This is a pull request for the following functionalities:

* Documentation on how to implement user dropboxes in Wasabi

## Any changes to documentation?

See docs/wasabidocs/WASABI_USER_DROPBOXES.md

### CODE REVIEW

**Review by kencho51 — APPROVED** [review]
Hi @pli888,

**praise:** The documentation is well written, can be read easily.
**question(non-blocking):** Is it better to extract the policy out from readme and save them as a json file? So they can be tested automatically like `Wasabi.feature` in future.
**note:** The wasabi automation script seems useful in creating 100+ user account, but it is a python script and further testing may be needed if we are going to use in future.

So, happy to approve this PR.

**Review by rija — COMMENTED** [review]
Hi @pli888,

**praise**: the docs describes the two options with clear explanation and enough details where it matters (policies)
**question**: in the second policy ('DenyUsersOtherBuckets'), 
Isn't the first statement: 
```
{                                                                                                             
          "Effect": "Deny",                                                                                           
          "Action": [                                                                                                 
            "s3:ListBucket",                                                                                          
            "s3:GetBucketLocation",                                                                                   
            "s3:ListBucketMultipartUploads"                                                                           
          ],                                                                                                          
          "NotResource": [                                                                                            
            "arn:aws:s3:::gigadb-bucket-${aws:username}/*",                                                           
            "arn:aws:s3:::gigadb-bucket-${aws:username}"                                                              
          ]                                                                                                           
        }
```

already covered by the second statement ?
```
 {                                                                                                             
          "Effect": "Deny",                                                                                           
          "Action": "s3:*",                                                                                           
          "NotResource": [                                                                                            
            "arn:aws:s3:::gigadb-bucket-${aws:username}/*",                                                           
            "arn:aws:s3:::gigadb-bucket-${aws:username}"                                                              
          ]                                                                                                           
        }        
```

Making the first statement unnecessary?

**question**: in the third policy (`gigadb-upload`), what is `CompanyBucket`? 
**question**:  do we know the tradeoffs of each option?

**Review by rija — COMMENTED** [review]
Hi @pli888,
Ignore my question regarding the second policy 'DenyUsersOtherBuckets', as I've just noticed it comes from the linked documentation, and I seem to remember that s3:* doesn't include bucket listing (but I cannot find reference of that anywhere)

**Review by rija — APPROVED** [review]
Hi @pli888,

I've now fully read the linked Wasabi documentation. Here's a revised review.

**praise**: clear description of the policies involved with each options and link to appropriate Wasabi documentation
**nitpick**: probably best to replace  `AllowRootAndHomeListingOfCompanyBucket` with something less generic
**question**: it would be good to know the tradeoffs of each option, but I guess we can discuss that during the sprint events

Given the above, I'm happy to approve this doc

**Pull request merged**
