### PR TITLE
Create rclone config for users

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1834

This is a pull request for the following functionalities:

* Create a rclone config specific to the user created by the user_playbook
* The rclone config for the centos user remains as it is, which the credentials are stored in the GitLab variable page

## How to test?

Describe how the new functionalities can be tested by PR reviewers

### Pre-requisites

1. A $user is created in the wasabi dashboard with its `credentials.csv` has bee saved locally
2. The $user has been assigned to group `Curators` in the wasabi dashboard

```

% cd ops/infrastructure/envs/staging
% ../../../scripts/tf_init.sh --project gigascience/forks/kencho-gigadb-website --env staging --web-ec2-type t3.small --bastion-ec2-type t3.small
% terraform plan
% terraform apply
% terraform refresh
% ../../../scripts/ansible_init.sh --env staging
% env TF_KEY_NAME=private_ip OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook  -i ../../inventories webapp_playbook.yml -e="gigadb_env=staging"
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "gigadb_env=staging" -e "backupDate=latest"
% ansible-playbook -i ../../inventories users_playbook.yml -e "newuser=lily" -e "credentials_csv_path=~/Downloads/credentials.csv" --extra-vars="gigadb_env=staging"
```

### check the rclone config for the user centos 
```
% ssh -i ~/.ssh/id-rsa-aws-seoul-ken.pem centos@3.36.204.163
The authenticity of host '3.36.204.163 (3.36.204.163)' can't be established.
ED25519 key fingerprint is SHA256:UxM5oc3v5qTqQ2Rs+UMTYTAXb1utQe0eJeGIzLp8+dY.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '3.36.204.163' (ED25519) to the list of known hosts.
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Tue Apr 30 03:20:48 2024 from 3.36.204.163
[centos@ip-10-99-0-117 ~]$ ls -al .config/rclone/
total 4
drwxr-xr-x. 2 centos centos  25 Apr 30 02:57 .
drwxr-xr-x. 3 centos centos  20 Apr 30 02:57 ..
-rw-r--r--. 1 root   root   526 Apr 30 02:57 rclone.conf
[centos@ip-10-99-0-117 ~]$ cat .config/rclone/rclone.conf 
[s3_remote]
```

### check the rclone config for the user lily
```
 % ssh -i output/privkeys-3.36.204.163/lily lily@3.36.204.163
Activate the web console with: systemctl enable --now cockpit.socket

[lily@ip-10-99-0-117 ~]$ ls
uploadDir
[lily@ip-10-99-0-117 ~]$ ls .aws/
credentials
[lily@ip-10-99-0-117 ~]$ ls -al .aws/
total 4
drwxr-xr-x. 2 lily lily  25 Apr 30 03:20 .
drwx------. 5 lily lily 103 Apr 30 03:20 ..
-rw-r--r--. 1 lily lily 108 Apr 30 03:20 credentials
[lily@ip-10-99-0-117 ~]$ cat .aws/credentials 
lily@ip-10-99-0-117 ~]$ ls -al .config/
total 0
drwxrwxr-x. 3 lily lily  20 Apr 30 03:25 .
drwx------. 6 lily lily 139 Apr 30 03:42 ..
drwxr-xr-x. 2 lily lily  25 Apr 30 06:00 rclone
[lily@ip-10-99-0-117 ~]$ 
[lily@ip-10-99-0-117 ~]$ cat .config/rclone/rclone.conf
...
[wasabi_lily]
type = s3
env_auth = true
region = ap-northeast-1
endpoint = s3.ap-northeast-1.wasabisys.com
location_constraint =
acl = public-read
server_side_encryption =
storage_class =
provider = Other
no_check_bucket = true
...
[lily@ip-10-99-0-117 ~]$ rclone version
rclone v1.60.0
- os/version: centos 8 (64 bit)
- os/kernel: 4.18.0-545.el8.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none
# before assigning any group in wasabi dashboard
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:
2024/04/30 06:02:41 ERROR : : error listing: AccessDenied: User: arn:aws:iam::100000166496:user/lily is not authorized to perform: s3:ListAllMyBuckets on resource: arn:aws:s3:::
        status code: 403, request id: 1F811D7323941330:A, host id: TIVM6P6wRk5b/Swr01u9blRsMg8Y440wjdz2CBP9AYlZe6c1fd+035XQSu3Mg/9F/NWWHPi1hCjQ
2024/04/30 06:02:41 Failed to lsd with 2 errors: last error was: AccessDenied: User: arn:aws:iam::100000166496:user/lily is not authorized to perform: s3:ListAllMyBuckets on resource: arn:aws:s3:::
        status code: 403, request id: 1F811D7323941330:A, host id: TIVM6P6wRk5b/Swr01u9blRsMg8Y440wjdz2CBP9AYlZe6c1fd+035XQSu3Mg/9F/NWWHPi1hCjQ
# After assigning to `Curator` group in wasabi dashboard
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:
          -1 2023-10-19 07:00:33        -1 cms-assets
          -1 2022-10-24 08:32:33        -1 gigadb-datasets
          -1 2023-05-22 15:59:31        -1 gigadb-datasets-logs
          -1 2023-06-14 16:34:29        -1 gigadb-monitoring-resources
          -1 2024-04-24 19:13:29        -1 infra-resources
          -1 2022-10-07 07:30:21        -1 test-gigadb-datasets
          -1 2022-11-15 06:32:08        -1 test-sg-bucket
          -1 2022-11-15 06:34:04        -1 test-tyo-bucket
          -1 2022-11-17 07:58:16        -1 test-us-east1-bucket
[lily@ip-10-99-0-117 ~]$ 
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:cms-assets/
2024/04/30 06:07:45 ERROR : : error listing: AccessDenied: Access Denied
        status code: 403, request id: 8A0EF4A163940636:B, host id: jguDBlHoFVd+sF5w+8l5QigPXWbOrsBgzclbmCQu+rijswyCPl3jfgqRCaNx3jKYst9bLWDTcacC
2024/04/30 06:07:45 Failed to lsd with 2 errors: last error was: AccessDenied: Access Denied
        status code: 403, request id: 8A0EF4A163940636:B, host id: jguDBlHoFVd+sF5w+8l5QigPXWbOrsBgzclbmCQu+rijswyCPl3jfgqRCaNx3jKYst9bLWDTcacC
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:gigadb-datasets
           0 2024-04-30 06:07:56        -1 CI
           0 2024-04-30 06:07:56        -1 dev
           0 2024-04-30 06:07:56        -1 live
           0 2024-04-30 06:07:56        -1 staging
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:gigadb-datasets/dev
           0 2024-04-30 06:09:01        -1 pub
           0 2024-04-30 06:09:01        -1 tests
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:gigadb-datasets/staging
           0 2024-04-30 06:09:26        -1 pub
           0 2024-04-30 06:09:26        -1 test-folder
           0 2024-04-30 06:09:26        -1 tests
[lily@ip-10-99-0-117 ~]$ rclone lsd wasabi_lily:gigadb-datasets/live
           0 2024-04-30 06:09:42        -1 pub
           0 2024-04-30 06:09:42        -1 tests
[lily@ip-10-99-0-117 ~]$ 

```

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

By creating a template `rclone-user.conf.j2` specific for the bastion user, after running the user playbook, a rclone config will be found in `/home/{{ newuser }}/.config/rclone/rclone.conf` and its content would be similar to:
```
[wasabi_$bastion-user]
type = s3
env_auth = false
access_key_id = xxxxxxxxxxxxxxxxxxxxxxxxxxx
secret_access_key = yyyyyyyyyyyyyyyyyyyyyyyyyyy
region = ap-northeast-1
endpoint = s3.ap-northeast-1.wasabisys.com
location_constraint =
acl = public-read
server_side_encryption =
storage_class =
provider = Other
no_check_bucket = true
```

The values for the $bastion-user, access_key_id and secret_access_key would be replaced by the values in the `credential.csv` downloaded from the wasabi dashboard.

## Any issues with implementation?
Describe any problems with your implementation

## Any changes to automated tests?

None.

## Any changes to documentation?

None.

## Any technical debt repayment?

None.

## Any improvements to CI/CD pipeline?

None.

### CODE REVIEW

**Review by pli888 — APPROVED** [review]
**praise**: Functionality works as described. A new Wasabi user when added into `Curator` group has command line access to the Wasabi bucket directories using bastion server.
**praise**: Code looks good to me.

I approve this PR.

**Review by rija — CHANGES_REQUESTED** [review]
Hi @kencho51,

**praise**: functionality works as described in the "How to test" section
**praise**: I was able to perform other expected actions from curators without problems:
```
$ rclone copy athena_some_file.txt wasabi_athena:gigadb-datasets/dev/
2024/05/03 16:03:52 ERROR : Attempt 1/3 failed with 1 errors and: Forbidden: Forbidden
$ rclone copy athena_some_file.txt wasabi_athena:gigadb-datasets/staging/
$ rclone ls wasabi_athena:gigadb-datasets/staging/athena_some_file.txt
$ rclone delete wasabi_athena:gigadb-datasets/staging/athena_some_file.txt
$ rclone ls wasabi_athena:gigadb-datasets/staging/athena_some_file.txt
```
**issue**: the access key Id and the secret tokens are duplicated as they appear twice, first in the rclone config for the user and in their AWS user credentials file
**issue**: because you are not leveraging the existence of the AWS user credentials file, the Ansible code is not as simple as it could be
**suggestion**: If you read through the rclone S3 documentation at https://rclone.org/s3/#authentication, 
you will see that rclone can read the credentials in the AWS user credentials files at `~/.aws/credentials`, so you don't need to specify the `access_key_id` and the `secret_access_key` fields of the rclone config.
(You will also need to change `env_auth` from `false` to `true`  as mentioned in the docs)
**note**: When you do the above you will notice  rclone will throw an error: ``NoCredentialProviders: no valid providers in chain. Deprecated.``. This is because there happen to be formatting/typo bugs in the template for the AWS credentials file, the fix is easy and is shown here: https://serverfault.com/a/1055889/397195
**note**: I think it's worth remembering, this PR implements #1395, which was dependent on the already merged #1394.  The reason we implemented #1394 in the first place, is because in the bastion the curators will use multiple tools to interact with the Wasabi bucket, one of them is rclone, another one will a tool based on aws-cli or AWS/SDK PHP to switch role to Admin (that's #1396), and maybe other tools too. They are all able to leverage the `.aws/credentials`, and it's good because we don't want sensitive credentials to be copied other and other in every single tool that users may install and/or use.

**Comment by kencho51** [comment]
Hi @rija 

> **suggestion**: If you read through the rclone S3 documentation at https://rclone.org/s3/#authentication,

Thank you for the information, your suggestion is appreciated.

After the updating the `./aws/credentials` format and updating the rclone user config template according to the rclone docs, the rclone in user account can use the aws credentials to interact with the wasabi curator's  buckets.

One thing to note that a new template `/roles/bastion-users/tasks/rclone-user.conf.j2` was introduced, so the credentials in the `ops/configuration/rclone-conf/rclone.conf.j2` for the `centos` user would not be exposed.

**Review by rija — APPROVED** [review]
Hi @kencho51,

with the changes, I'm happy to approve this PR

**Pull request merged**
