### PR TITLE
Save changes and reload the same page

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1529

This is a pull request for the following functionalities:

After clicking the `Save` button for the private dataset in the admin dataset page, the same page will be reloaded.
After clicking the `Save` button for the published dataset in the admin dataset page, the page will be redirected to the  public dataset page.

## How to test?

Describe how the new functionalities can be tested by PR reviewers

##### Local dev environment
```
# spin up gigadb website
% cd gigadb-website
% ./up.sh
```

Then go to the admin page of a private dataset, eg: http://gigadb.gigasciencejournal.com:9170/adminDataset/update/id/668, make any changes and then click `Save`, the admin page of that private dataset will then be reloaded with the updated values, instead of redirecting the page to the public dataset page.

```
# execute the functional test
% docker-compose run --rm test ./vendor/codeception/codeception/codecept run functional AdminDatasetFormCest -v

# execute the acceptance test
% docker-compose run --rm codecept run --no-redirect -g flashmessage acceptance -v
```

##### Production environment
```
# spin up production servers, eg. staging
% cd ops/infrastructure/envs/staging
% ../../../scripts/tf_init.sh --project gigascience/forks/kencho-gigadb-website --env staging
% terraform apply
% terraform refresh
% ../../../scripts/ansible_init.sh --env staging
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging"
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" --extra-vars="gigadb_env=staging"
# execute the gitlab pipeline
```

When the staging gigadb website has been deployed, then log in  as an admin. Locate a private dataset in the `adminDataset/admin` page, go to that dateset page and make changes, then click `Save`, the admin page of that private dataset will then be reloaded with the updated values, instead of redirecting the page to the public dataset page.

## How have functionalities been implemented?

In the `protected/controllers/AdminDatasetController.php`, the redirected url in the `actiomUpdate()` function is invalid which always result the page cannot be found error.

With the latest implementation, the redirected url has been updated to the admin dataset update page with the exact id, so when the `actionUpdate()` is triggered by clicking the `Save` button, the private dataset with page type `hidden` will be reloaded to the same page with the updated values.

A new functional test `AdminDatasetFormCest.php` has been created as the acceptance criteria requires checking the values in the database.

New acceptance tests with tag `@flashmessage` have been created to test for the existence of the flash message on the page after pressing the `Save` button.

## Any issues with implementation?

None.

## Any changes to automated tests?

None.

## Any changes to documentation?

None.

## Any technical debt repayment?

None.

## Any improvements to CI/CD pipeline?

None.

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @kencho51,

issue: As mentioned in the VOH, not presenting a confirmation after the user has saved the form is going to be a problem with several error scenarios like problem in the backend, or network failure, the user will think erroneously that the change is saved when it is not. Also if users are working on a dataset page for a long time with multiple changes, They may forget whether a particular change has been saved and press save again, causing unnecessary bandwidth and server resource usage.

**Comment by kencho51** [comment]
Hi @rija,

> issue: As mentioned in the VOH, not presenting a confirmation after the user has saved the form is going to be a problem 

The issue has been fixed in the latest commits.

Regarding this issue, flash message feature has been introduced to the admin update page, the message needs to be set in the controller class using `setFlash()` function, then retrieve the message in the view class using  `getFlash()` function.

There is a tricky part on displaying the flash message is the page will be redirected to different page according to the `getPageType()` variable, which means the `getFlash()` function has be been implemented accordingly.

**Review by rija — CHANGES_REQUESTED** [review]
Hi @kencho51,


**praise**: advertised functionality is working and the user knows what's going on
**praise**: new acceptance tests scenario for user feedback and private dataset saving
**issue**: The changes to `protected/views/dataset/view.php` are not a good idea at this time: the success message is not as important, since we can see the result of the update, and upon failure it stays on the form anyways. Also the blocker issue this PR is for is specifically about private datasets staying on the form, nothing to do with the dataset view. Finally there are some layout issue about how the flash message appear on the dataset view, that we don't really want to tackle individually here.
**suggestion**: revert the changes made to `protected/views/dataset/view.php` and adjust the acceptance test scenarios accordingly
**nitpick**: the success message should probably be "Updated successfully"
**issue**: unless I'm missing something, the new functional test feels unnecessary and/or the wrong place for a coverage improvement. `AdminDatasetForm.feature` was created to test the various workflow action of the form, and if there are scenarios missing with respect to the user story described at the top, they should be added to the feature file as new scenarios (especially the feature steps are reusable and should drastically reduce the code needed for new scenarios). Looking at the functional tests in `AdminDatasetFormCest.php`, I fail to see what are they doing that is not already covered by a scenario in the updated `AdminDatasetForm.feature`?
Functional tests are best suited for cross-functionboundary or infrastructure-adjacent features and there are good candidates in the dataset update/creation workflow, but those are not the tests you wrote.
**suggestion**: remove the new Cest file
**praise**: all tests are passing

**Comment by kencho51** [comment]
Hi @rija 

> **suggestion**: revert the changes made to `protected/views/dataset/view.php` and adjust the acceptance test scenarios accordingly

The display of flash message on dataset page has been removed, the reason why I implemented it because some of the updates, eg. Dataset Size is not shown in the dataset page.

>suggestion: remove the new Cest file

The new Cest file aims to check the table `Dataset` contains the correct entries after the action of Save and Cancel, which was required in https://github.com/gigascience/gigadb-website/issues/1532.

**Comment by rija** [comment]
> Hi @rija
> 
> > **suggestion**: revert the changes made to `protected/views/dataset/view.php` and adjust the acceptance test scenarios accordingly
> 
> The display of flash message on dataset page has been removed, the reason why I implemented it because some of the updates, eg. Dataset Size is not shown in the dataset page.
> 
> > suggestion: remove the new Cest file
> 
> The new Cest file aims to check the table `Dataset` contains the correct entries after the action of Save and Cancel, which was required in #1532.

Hi @kencho51 

From the issue you mentioned, the requirement is to ensure the information is saved.
If you have an acceptance test scenario that already check for the flash message presence, you know the page has redirected and you can also then check the information saved is on the page, because when the form is loaded (e.g from a redirect), the data is pulled from the database. If the information is on page  you know  it has been saved successfully. If the saving didn't work, it cannot be pulled from the database on page load. 

You really don't need to write additional code for that. 
The tests in Cest file are therefore still unnecessary

**Review by rija — APPROVED** [review]
Hi @kencho51 

LGTM, approved.

**Review by pli888 — APPROVED** [review]
**praise**: Functionality is working as described and code looks good to me.

**Pull request merged**
