### PR TITLE
Fix curation log errors

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1169

This is a pull request for the following functionalities:

* Fix access to create, view, update and delete curation log record web pages from admin dataset page.

### Create new curation log record from dataset admin page

1. Deploy staging server on AWS
```
$ cd /path/to/ops/infrastructure/envs/staging

# Copy terraform files to staging environment
$ ../../../scripts/tf_init.sh --project gigascience/forks/your-gigadb-website --env staging

# Provision with Terraform
$ terraform plan
$ terraform apply
$ terraform refresh

# Copy ansible files
$ ../../../scripts/ansible_init.sh --env staging

# Provision bastion ec2 server and restore RDS with latest database backup
$ ansible-playbook -i ../../inventories bastion_playbook.yml

# Provision webapp ec2 server with ansible
$ TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml
```
2. Log into staging GigaDB website using an admin user account
3. Go to https://your.staging.gigadb/adminDataset/update/id/2571
4. Click on `Create New Log` button
5. Select `Comment` and write some text in comment text field. Click `Create` button.
6. You should now be able to see the newly created curation log entry

### View curation log record from dataset admin page

7. Go to https://your.staging.gigadb/adminDataset/update/id/2571
8. Click on view curation log entry icon

### Update curation log record from dataset admin page

7. Go to https://your.staging.gigadb/adminDataset/update/id/2571
8. Click on update curation log entry icon

### Delete curation log record from dataset admin page

7. Go to https://your.staging.gigadb/adminDataset/update/id/2571
8. Click on delete curation log entry icon
9. Click yes in delete confirmation pop-up window
10. Check on dataset admin page that the deleted curation log entry is not present

## How have functionalities been implemented?

The "unable to resolve request `curationlog/create/id/2571`" error message appears to be caused by the fact that URLs calling functions in Controller classes are case-sensitive (at least on AWS deployments of the GigaDB website). Therefore, it needs to be `curationLog/create/id/2571` in order for the URL to be resolvable on the staging server. To this end, `protected/views/adminDataset/curationlog.php` has been updated so its curation log URLs are in camelcase now.

## Any issues with implementation?

The surprising thing is that before I made the changes in this PR, the curation log functionality was working on my local dev deployment.

## Any changes to automated tests?

New acceptance tests have been added into AdminDatasetForm.feature to check creating, viewing, updating and deleting curation log records. `data/dev/curation_log.csv` has been updated with curation log entries.

I've added two new functions into AcceptanceTester class: `iShouldSeeAnImageWithAlternateTextIsLinkedTo($alt, $expectedUrl)` and `iClickOnImageWithAlternateText($alt)`. These functions are for interacting with the curation log image icon links that call the create, view, update and delete functions in  CurationLogController class.

## Any technical debt repayment?

I formatted the code in the curationlog view class into PSR-12 standard as it was messy making it hard to understand what was going on.

The directory name containing the curation log view class has been renamed so it is now written in `curationLog` camelcase which is now consistent with other directories containing view classes.

### CODE REVIEW

**Review by rija — APPROVED** [review]
Hi @pli888,

**praise:** I can validate the fix is working after following the instructions from the "How to test" section
**praise:** All the tests are passing, and it's great the test coverage has been improved
**suggestion (test,if-minor, non-blocking):** the scenario for updating the curation log doesn't go all the way (fill in the field with new value, and press the update button)
**polish:** since you made changes to them, might be worth checking PSR12 on the view files in the ``curationLog`` directory
**note:** I believe the issue is not happening on local environment because macOS file system is case-insensitive, while Linux's is case-sensitive

Overall, great work, happy to approve

**Comment by pli888** [comment]
> suggestion (test,if-minor, non-blocking): the scenario for updating the curation log doesn't go all the way (fill in the field with new value, and press the update button)

>polish: since you made changes to them, might be worth checking PSR12 on the view files in the curationLog directory

@rija Suggestion and polish have been done now.

**Review by kencho51 — APPROVED** [review]
Hi @pli888,

**praise:** The error `unable to resolve request to curationlog` has been fixed in staging.

**praise:** The updated code complies with PSR-12 standard.

**praise:** The updated acceptance tests are passing in both local dev and gitlab CICD pipeline.

**question(non-blocking):** The `protected/views/adminDataset/curationlog.php` is also better in camel case for consistency? 

The changes look good to me, happy to approve this PR.

**Comment by pli888** [comment]
>question(non-blocking): The protected/views/adminDataset/curationlog.php is also better in camel case for consistency?

@kencho51 It is `protected/views/adminDataset/curationLog.php` now.

**Pull request merged**
