### PR TITLE
Update data volume size on home page

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1595

This is a pull request for the following functionalities:

* Updated data volume size displayed on home page

## How to test?

Checkout the code in the this pull request into a new branch containing the latest develop code in your local fork of gigadb-website repo and spin up a local dev instance of GigaDB:
```
git checkout -b pli888-update-total-volume develop
git pull https://github.com/pli888/gigadb-website.git update-total-volume
./up.sh
```

Take a look at the home page on http://gigadb.gigasciencejournal.com:9170 and confirm you can see Data volume (TB) has a value of 65. The same change can also be seen on your staging server if you decide to test this PR on an AWS deployment.

## How have functionalities been implemented?

The size of the 100001_101000, 101001_102000, 102001_103000 and 200001_201000 directories containing published datasets was queried on the Tencent back up server. The total size of all 4 directories was calculated to be approximately 65 TB. This value was then used to update the `protected/views/site/index.php` file.

### CODE REVIEW

**Review by kencho51 — APPROVED** [review]
This temporary fix LGTM, happy to approve.

**Review by rija — APPROVED** [review]
Hi @pli888,

**praise**: manual change works on my local checkout
**praise**: code looks fine
**note**: running the command `rclone size wasabi:gigadb-datasets/live`  on bastion server will give the accurate size once all the dataset files have finished migrating. So we can then automate that value by writing regularly (daily cronjob) the output to a txt file uploaded to S3 and have the CDN-ized link included in the homepage's PHP view template.

Happy to approve!

**Review by rija — CHANGES_REQUESTED** [review]
Hi @pli888 ,

Sorry, I just noticed this PR is missing a CHANGELOG entry.
Do you mind adding one?

**Comment by pli888** [comment]
>Sorry, I just noticed this PR is missing a CHANGELOG entry.
Do you mind adding one?

@rija This is done now.

**Pull request merged**
