### PR TITLE
fixes issue#42 and issue#9

### PR DESCRIPTION
**Pull request by jessesiu**

### CODE REVIEW

**Comment by only1chunts** [comment]
@jessesiu I think these need to be split into separate pull requests, every update should be done individually to enable complete transparency in tracking.
#42 appears to be fixed in the public server - I've not checked on a VM
#9 -not checked yet.

**Comment by only1chunts** [comment]
@jessesiu , Issue #42 still exists when I try on the VM , i.e. I still get an error 500 when I try to delete files using the admin pages.
I followed the instructions to fetch the "develop" branch, but perhaps I've done something wrong?! or the fix hasn't worked?
I've not checked #9 yet because I cant remember how to upload the database to look at the example dataset.

**Comment by only1chunts** [comment]
@jessesiu , Its OK, I was looking at the gigascience:develop branch, not the jessesiu:develop branch. Now that I'm looking at the correct branch:
Issue #42 is fixed.
Issue #9 is part fixed. The linked samples now displays multiple samples which is the important bit, but there is no limit set to how many are shown, i.e. if more than 3 add the "+" button for users to expand the view if required (same as sample attributes table).

**Comment by jessesiu** [comment]
@only1chunts  the commit fixes issue #43 will only show 3 linked samples and the + button (same as sample attributes table)

**Comment by pli888** [comment]
@jessesiu Can you check the conflict problem with your chef/chef-cookbooks in this merge please?

**Comment by jessesiu** [comment]
@pli888  Fixed the conflict problem

**Pull request merged**
