### PR TITLE
Initial implementation of Fuw re-enabled

### PR DESCRIPTION
**Pull request by rija**
# Pull request for issue: #1603 

This is a pull request for the following functionalities:

* Re-enable the current state of File Upload Wizard workflow locally
* Add various fixes to the FUW workflow to enable it to function end-to-end as per the video tutorial from two years ago
* Add various fixes to issues that impede on the development
* Implement an easy to operate feature flag for File Upload Wizard using Gitlab Feature flag, currently set up to enable FUW on dev environment only

## How to test?

There are two changes to test: 
1. The feature flag
2. That the instructions shown in the video can still be executed

### Prerequisite

* Update the variable "HOME_URL" for the "dev" environment in the Gitlab variables for your fork of Gigadb website, so it doesn't have a `:9170` in it
* ensure you regenerate your `.env` from `env-sample`
* remove `.secrets`
* Set and export  environment variable `NODE_OPTIONS` with value `--openssl-legacy-provider` in your terminal
* Ensure you have [a recent chrome driver binary](https://googlechromelabs.github.io/chrome-for-testing/) installed at `/usr/local/bin/chromedriver` (you can copy the binary from the downloaded package `chrome-mac-arm64.zip` into `/usr/local/bin`)
* Start the local website with `./up.sh`

#### Automatically

After starting the local website with `up.sh`, run the test:
```
docker-compose run --rm test ./vendor/codeception/codeception/codecept run --debug unit DatasetTest
```

Tests should be passing and a debug output should say: "FUW is enabled "

Navigate to the Feature flag dashboard on Gitlab: https://gitlab.com/gigascience/upstream/gigadb-website/-/feature_flags, and turn the switch off.

**Wait a few seconds (~30s)** for the API to update its state, and run the same test again.
The tests should still be passing but the debug output should say: "FUW is NOT enabled".

Then turn on the switch in the dashboard again.

#### Manually

Navigate as admin to: http://gigadb.gigasciencejournal.com/adminDataset/update/id/668
Click on the upload status drop-down, you should see them all, including the ones used by File Upload Wizard:
 * AssigningFTPbox
 * UserUploadingData
 * DataAvailableForReview
 * DataPending

Navigate to the Feature flag dashboard on Gitlab: https://gitlab.com/gigascience/upstream/gigadb-website/-/feature_flags, and turn the switch off.

**Wait a few seconds (~30s to 1mn)** for the API to update its state, and refresh the dataset form.
The upload status related to the FUW should not be appearing in the drop-down list.

#### prepare dataset

The test dataset is going to be the one with DOI 200070.

* Navigate as admin to: http://gigadb.gigasciencejournal.com/adminDataset/update/id/668
* Change "Submitter" value to "user@gigadb.org" by selecting "user@gigadb.org" in the drop-down menu, save the form

#### prepare filesystem

The example files and metadata spreadsheets used in the video are located in `fuw/input-examples`

#### Follow  the instructions as per video

Follow instructions shown in [the video](https://drive.google.com/file/d/1xQX5_Z84Q_AzNMQqLo7dnrt6FYpN7Wjw/view?usp=share_link) but with three changes: 
* use the DOI 200070 prepared in the previous paragraph instead of the one mentioned in the video
* use the local checkout's deployment at `gigadb.gigasciencejournal.com`
* the author role to use is "John Smith" (user@gigadb.org)

https://drive.google.com/file/d/1xQX5_Z84Q_AzNMQqLo7dnrt6FYpN7Wjw/view?usp=share_link

### Feature flag

Gitlab feature flag uses [Unleash](https://www.getunleash.io), which is client-server software for managing feature flags at scale and for multiple strategies. Gitlab.com implements an Unleash server.

Developers' applications add an Unleash client in their codebase. There's an official Unleash SDK for many language including PHP that does the job. That's what we are using, so it's a matter of installing the Composer dependencies [as per the documentation](https://docs.getunleash.io/reference/sdks/php).

However the legacy nature of GigaDB codebase and the need to still keep old version of Composer dependencies complicate the installation and none of the two documented approaches worked. First problem was with http client, neither `guzzlehttp/guzzle` or `symfony/http-client` had a version that's old enough for our codebase but supports the requirements for Unleash. (The latter could be installed but it crashed when used).

Fortunately, the `unleash/client` Composer library implements PSR-7, PSR-17 and PSR-18 (and PSR-6),
So I was able to find a drop-in replacement PSR-18 http client (`kriswallsmith/buzz`) on packagist.org whose dependency tree is tolerant of legacy codebase and can work with the PSR-7 library that I was able to install (`nyholm/psr7`).

Similarly, I couldn't get `symfony/cache`to be installed, so I searched and found on packagist.org another PSR-6 compatible cache mechanism that could be installed: `cache/filesystem-adapter` whose only major dependency is Flysystem v1 which we are already using in our codebase.

Then, because we will very likely use feature flag for more feature in the future and because connection details need to be supplied for connecting to the server - there are new variables prefixed with `FF` in Gitlab variables now - , I have created a service `FeatureFlagService` as a Yii application component, so it's very easy to use in in the codebase without having to deal with configuration.

The last part of the implementation is to re-organise the list of upload status (that's the entry point for FUW workflow), so that we can use a feature flag around them. 

Unit tests and functional tests have been implemented for that functionality (see test section below).

### Re-enabling FUW and ensure it works end-to-end

No particular strategy.
Unfortunately, uncommenting things related to FUW that were commented was not enough.
Better check individual commits to see all the fix.

Some notable change that's worth mentioning though:

* the local website is now available at `gigadb.gigasciencejournal.com` to fix an issue with `tusd` not being reachable by the `Uppy` file upload component
* the Vue.js project was previously using Headless Firefox for component testing but it crashes on Macs with Apple silicon, now it uses Headless Chrome that needs to be installed separately
* The third-party Pure-ftpd Docker container for drop-box ftp we were using crashes on Mac with Apple silicon, so I've copied their Dockerfile code into our own so it can be built locally
* When creating a drop-box account for a given dataset in the gigadb website without having properly removed the various artefacts created in `$DATA_SAVE_PATH/pure-ftpd/` and `$DATA_SAVE_PATH/fuw/`, the application will misbehave and either crash or send user an email with incorrect credentials. The backend has been made idempotent by detecting first whether those artefacts exists (see commit 1346cfe)
* Several things were breaking (including installing unleash/client described in the above section) because with had reference to PHP `7.3.33` in `composer.json.dist` and in `ops/deployment/docker-compose.yml` (despite the fact that we do use `7.4.33`), which I have now replaced everywhere with `7.4.33`

## Any issues with implementation?

The file upload wizard is two years old and hasn't seen any update while the rest of the codebase and infrastructure has evolved. Because of that, I found several issues. I have decided not to fix them and instead will make them tasks in the upcoming File Upload Wizard milestone. The only issues that were fixed were the ones that blocked end-to-end or hampered development (and are described in the section above). The issues I found that remain unfixed (not exhaustive, there may be more):

* OpenSSL/Node.Js security issue, for which I have only put a stop-gap workaround that need proper fixing before deploying to cloud environments (there's a TODO in code for that)
* All the Javascript dependencies are at least two years old and in major ways that we cannot blind upgrade all (the front-end list of tasks for Luis already reflect my initial investigation about how far we can upgrade the critical dependencies, I probably missed some dependencies though)
* Controlling docker from PHP using the Docker client for PHP library is a bit brittle and that library is long deprecated (instead we should be installing pure-ftpd command line software inside the FUW backend container)
* Up-to-date developer docs is non-existent
* Pipeline deployment to AWS hasn't been tested again and is probably not working but will need update has our deployment procedures have changed in the last two years

## Any changes to automated tests?

Tests have been added to support the feature flag implementation:
* A functional test, `tests/functional/FeatureFlagCest.php`, was added to exercise the integration of the Yii configuration for feature flag connection details, the Gitlab API and the codebase.
* A Unit test, `tests/unit/DatasetTest.php`, has been added to test the refactoring of the upload status dropdown so it can be controlled by a feature flag

The functional test for FUW have been re-enabled in `functional_runner` after I fixed their configuration.

## Any technical debt repayment?

Finally fixed the issue that caused `gigadb/app/worker/file-worker/composer.lock` to change often.

### CODE REVIEW

**Comment by pli888** [comment]
@rija I managed to create a new dropbox for user@gigadb.org then changed dataset status to `UserUploadingData`. But when I am on http://gigadb.gigasciencejournal.com/user/view_profile#submitted and I click `Upload Files` link, I see this error below:
 
Screenshot 2024-01-04 at 12 41 47 PM

Any advice please?

**Comment by kencho51** [comment]
Hi @rija,

When I tried to create a dropbox for the user, I got the following error:
image


log of `deployment-application`:

```
in /var/www/protected/controllers/AdminDatasetController.php (248)

in /var/www/index.php (24)

Failed to set unsafe attribute "curator_id" of "Dataset".

in /var/www/protected/controllers/AdminDatasetController.php (249)

in /var/www/index.php (24)

Failed to set unsafe attribute "manuscript_id" of "Dataset".

in /var/www/protected/controllers/AdminDatasetController.php (249)

in /var/www/index.php (24)

Dataset is already associated with image :669

in /var/www/protected/controllers/AdminDatasetController.php (300)

in /var/www/index.php (24)

172.16.238.10 -  04/Jan/2024:08:53:33 +0000 "GET /index.php" 200

172.16.238.10 -  04/Jan/2024:08:53:37 +0000 "GET /index.php" 200

172.16.238.10 -  04/Jan/2024:08:53:39 +0000 "GET /index.php" 200

172.16.238.10 -  04/Jan/2024:08:53:40 +0000 "GET /index.php" 200

The requesting user doesn't have admin role

in /var/www/protected/components/FiledropService.php (77)

in /var/www/protected/controllers/adminDataset/AssignFTPBoxAction.php (32)

in /var/www/index.php (24)

172.16.238.10 -  04/Jan/2024:08:53:47 +0000 "GET /index.php" 302

172.16.238.10 -  04/Jan/2024:08:53:47 +0000 "GET /index.php" 200

```

**Comment by rija** [comment]
> @rija I managed to create a new dropbox for [user@gigadb.org](mailto:user@gigadb.org) then changed dataset status to `UserUploadingData`. But when I am on http://gigadb.gigasciencejournal.com/user/view_profile#submitted and I click `Upload Files` link, I see this error below:
> 
> Screenshot 2024-01-04 at 12 41 47 PM
> Any advice please?

Did you login as user@gigadb.org before clicking the link?

**Comment by rija** [comment]
> Hi @rija,
> 
> When I tried to create a dropbox for the user, I got the following error: image

Could you share the log for the container services:
* deployment-application
* deployment-fuw-admin

**Comment by kencho51** [comment]
Hi @rija,

> Could you share the log for the container services:
> 
>     * deployment-application
> 
>     * deployment-fuw-admin

After logging out and logging in again, I could click the button `New dropbox for the dataset` successfully.

**Comment by pli888** [comment]
>I managed to create a new dropbox for [user@gigadb.org](mailto:user@gigadb.org) then changed dataset status to UserUploadingData. But when I am on http://gigadb.gigasciencejournal.com/user/view_profile#submitted and I click Upload Files link, I see this error below:

@rija I switched to using Chrome and managed to create dropbox, upload a file then add file type and description metadata for it when I logged out from being admin and logged in as user. I will take a closer look at the FUW functionality and record my steps.

**Comment by rija** [comment]
Hi @pli888, @kencho51, 

the test failures on CI have now been fixed.

**Review by kencho51 — CHANGES_REQUESTED** [review]
Hi @rija,

**praise:** By following the steps in `how to test`, I could get `FUW` up and running in my dev.
**praise:** I could follow all the steps in the [video demonstration](https://drive.google.com/file/d/1xQX5_Z84Q_AzNMQqLo7dnrt6FYpN7Wjw/view).
**praise:** The `gigadb/app/worker/file-worker/composer.lock` will not be kept modifying when `./up.sh` every time. 
**issue:** The updated values cannot be seen in the mockup page, but the values reside n table `upload` of database `fuwdb` . It seems the mockup page has caching issue, may be related to https://github.com/gigascience/gigadb-website/pull/1560.
**suggestion:** Is it possible to disable caching for the fuw mockup page?
**issue: ** The functional test `ResetPasswordCest: Try reset password with valid token` is failing at `$I->see("Login","h4") at tests/functional/ResetPasswordCest.php:159` on both CI and dev.
**suggestion:** The CSS styel of the login page has been updated, the heading `h4` has been updated to `h1` due to the contractor's work. Better update the selector to `h1` or even just `$I->see('Login');` is enough.
**issue:** On CI, the `featureFlagCest: Try check is not enabled for env not enabled` is failing  at `1. $I->assertFalse(true) at tests/functional/FeatureFlagCest.php:52` when the `FUW` feature is turned in gitlab; while the `featureFlagCest: Try check is enabled for env enabled` is failing when the `FUW` feature is turned off in gitlab.

**Review by kencho51 — APPROVED** [review]
Hi @rija,

After some thoughts, this PR aims to merge the FUW into the dev branch, so the further dev works will not be blocked, since the FUW has been tested and can be spin up in my dev with all tests are passing locally, so I think it it reasonable to approve and merge it first, and then further work on the issues found as below:

- [ ]  #1644
- [ ] #1645
- [ ] #1646

**Review by pli888 — APPROVED** [review]
**praise**: I can use the file upload wizard which has been en-enabled on the `dev` environment to replicate the functionality demonstrated in the FUW video.
**issue**: featureFlagCest and ResetPasswordCest in unit_func_tests are also failing for me.
**suggestion**: @kencho51 has created tickets for the above two tests. In order for the contractor to start work on FUW, I suggest we approve and merge PR. We then fix the bugs later on in this current sprint.
**praise**: Code looks good to me.

**Pull request merged**
