### PR TITLE
Make script for calculating file size and md5 available

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1832

This is a pull request for the following functionalities:

* Made the script `calculate_checksum_sizes` available for the bastion user
* Configured the rclone for the bastion user to interact with curator's wasabi bucket and  aws s3 bucket `gigadb-datasets-metadata`
* Tested the script `calculate_checksum_sizes` against the live data copied from the production live efs
* Updated the bats tests on the script `md5.sh`

## How to test?

Describe how the new functionalities can be tested by PR reviewers

### Pre-requisite
1. A user is created with group `Curator` in the wasabi dashboard and the credentials.csv is download
2. Copy the live user pem to the testing bastion server
```
% scp -i output/privkeys-$bastion-ip/$bastion-user /path/to/live/bastion/$user-pem $bastion-user@$bastion-ip:/home/$bastion-user/.ssh/
```
3. Update the env file
```
% cd gigadb-website
% rm .env
% cp ops/configuration/variables/env-sample .env
# update the gitlab private token and the gitlab repo name
# spin up gigadb website
% ./up.sh
```

### bats test on the shell script `md5.sh`
```
% cd gigadb/app/tools/files-metadata-console 
% bats tests/bats/md5.bats
md5.bats
 ✓ No DOI provided
 ✓ DOI provided
 ✓ confirm the md5 and the file size values 

3 tests, 0 failures
```

### Spin up staging servers and make the bastion server ready for user
```
% cd ops/infrastructure/envs/staging
% ../../../scripts/tf_init.sh --project gigascience/forks/kencho-gigadb-website --env staging --web-ec2-type t3.small --bastion-ec2-type t3.small
% terraform plan
% terraform apply
% terraform refresh
% ../../../scripts/ansible_init.sh --env staging
% env TF_KEY_NAME=private_ip OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook  -i ../../inventories webapp_playbook.yml -e "gigadb_env=staging"
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "gigadb_env=staging" -e "backupDate=latest"
# login bastion as centos
% ssh -i ~/.ssh/$bastion-pem centos@$bastion-ip
# install aws efs utils and create mount points 
[centos@ip-10-99-0-88 ~]$ sudo yum -y install https://s3.ap-northeast-1.wasabisys.com/infra-resources/amazon-efs-utils-2.0.1-1.el8.x86_64.rpm
[centos@ip-10-99-0-88 ~]$ ls -al /share/
total 0
drwxr-xr-x.  4 centos centos  35 May  7 04:41 .
dr-xr-xr-x. 18 root   root   237 May  7 04:41 ..
drwxr-xr-x.  2 centos centos   6 May  7 04:41 config
drwxr-xr-x.  2 centos centos   6 May  7 04:41 dropbox
[centos@ip-10-99-0-88 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M   17M  854M   2% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  3.8G   27G  13% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
tmpfs          tmpfs     175M     0  175M   0% /run/user/1001
[centos@ip-10-99-0-88 ~]$ sudo mount -t efs -o tls,accesspoint=fsap-dropbox-id fs-id /share/dropbox
[centos@ip-10-99-0-88 ~]$ sudo mount -t efs -o tls,accesspoint=fsap-configuration-id fs-id /share/dropbox
[centos@ip-10-99-0-88 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M   17M  854M   2% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  3.8G   27G  13% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
tmpfs          tmpfs     175M     0  175M   0% /run/user/1001
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /share/config
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /share/dropbox
[centos@ip-10-99-0-88 ~]$ 
[centos@ip-10-99-0-88 ~]$ exit
```

### create a bastion user and test the rclone, script as a bastion user
```
% pwd
ops/infrastructure/envs/staging
% ansible-playbook -i ../../inventories users_playbook.yml -e "newuser=lily" -e "credentials_csv_path=~/Downloads/credentials.csv" -e "gigadb_env=staging"
# login bastion as lily
% ssh -i output/privkeys-$bastion-ip/lily lily@$bastion-ip
lily@ip-10-99-0-43 ~]$ 
[lily@ip-10-99-0-88 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M   17M  854M   2% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  3.8G   27G  13% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
tmpfs          tmpfs     175M     0  175M   0% /run/user/1001
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /share/config
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /share/dropbox
# confirm the rclone config file
[lily@ip-10-99-0-43 ~]$ cat .config/rclone/rclone.conf 
[aws_metadata]
type = s3
provider = AWS
env_auth = true
shared_credentials_file = /etc/aws/credentials
region = ap-northeast-1
location_constraint = ap-northeast-1
acl = private
no_check_bucket = true

[wasabi_lily]
type = s3
env_auth = true
region = ap-northeast-1
endpoint = s3.ap-northeast-1.wasabisys.com
location_constraint =
acl = public-read
server_side_encryption =
storage_class =
provider = Other
no_check_bucket = true
[lily@ip-10-99-0-43 ~]$ rclone ls aws_metadata:
2024/05/03 07:03:38 Failed to ls: AccessDenied: Access Denied
        status code: 403, request id: ZYMF9KE7S86AFHD3, host id: olW4l9tqYpPY0OBH0yWCb1sDQpx2Rnf2xz4E8Qqu23rE293zIT/j5q907YDNCu6chus8JPElIPY=
[lily@ip-10-99-0-43 ~]$ rclone ls aws_metadata:gigadb-datasets-metadata
      352 100006.filesizes
      596 100006.md5
      137 100039.filesizes
      107 100142.filesizes
       68 102480.filesizes
      118 102480.md5
      105 102499.filesizes
      161 102499.md5
     3825 102515.filesizes
     5420 102515.md5
     2704 102519.filesizes
     2330 102519.md5
     2213 102520.filesizes
     3483 102520.md5
     1698 102522.filesizes
     1303 102522.md5
     4622 102523.filesizes
     7371 102523.md5
      764 102524.filesizes
      692 102524.md5
     5141 102526.filesizes
     9251 102526.md5

# create an extra endpoint in rclone config pointing to the production live efs 
[lily@ip-10-99-0-43 ~]$ vi .config/rclone/rclone.conf
[live-efs]
type = sftp
host = $live-bastion-ip
user = $live-bastion-user
key_file = /home/lily/.ssh/$user-pem
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
[lily@ip-10-99-0-43 ~]$ rclone lsd live-efs:/share/dropbox
          -1 2024-04-27 07:46:35        -1 user1
          -1 2024-04-26 09:44:58        -1 user10
          -1 2024-04-26 09:28:16        -1 user103
          -1 2024-04-26 09:42:26        -1 user106
          -1 2024-04-26 09:50:33        -1 user108
          -1 2024-04-26 09:55:48        -1 user109
          -1 2024-04-26 09:55:59        -1 user110
          -1 2024-04-26 10:04:19        -1 user112
          -1 2024-04-27 09:21:59        -1 user113
          -1 2024-04-26 10:10:03        -1 user116
          -1 2024-04-26 10:13:40        -1 user120
          -1 2024-04-27 08:15:54        -1 user16
          -1 2024-04-26 10:19:42        -1 user18
          -1 2024-04-26 10:20:28        -1 user2
          -1 2024-04-26 10:20:42        -1 user22
          -1 2024-04-26 10:20:51        -1 user24
          -1 2024-04-29 09:24:09        -1 user27
          -1 2024-04-26 10:35:10        -1 user29
          -1 2024-04-26 10:35:43        -1 user32
          -1 2024-04-26 10:43:58        -1 user35
          -1 2024-04-26 10:49:39        -1 user38
          -1 2024-04-26 11:12:33        -1 user39
          -1 2024-04-26 11:19:12        -1 user4
          -1 2024-04-26 11:24:11        -1 user40
          -1 2024-04-26 11:24:48        -1 user42
          -1 2024-04-26 11:27:49        -1 user43
          -1 2024-04-26 12:01:43        -1 user44
          -1 2024-04-26 12:14:58        -1 user47
          -1 2024-04-26 12:15:12        -1 user49
          -1 2024-04-26 12:19:22        -1 user5
          -1 2024-04-26 13:16:01        -1 user50
          -1 2024-04-26 12:28:58        -1 user51
          -1 2024-04-26 12:14:26        -1 user55
          -1 2024-04-26 13:30:06        -1 user58
          -1 2024-04-26 12:12:50        -1 user6
          -1 2024-04-26 12:13:28        -1 user63
          -1 2024-04-26 13:32:05        -1 user64
          -1 2024-04-26 13:32:18        -1 user67
          -1 2024-04-26 21:41:00        -1 user69
          -1 2024-04-26 13:34:34        -1 user72
          -1 2024-04-26 13:35:45        -1 user74
          -1 2024-04-26 13:43:42        -1 user75
          -1 2024-04-26 14:11:25        -1 user76
          -1 2024-04-27 01:47:51        -1 user78
          -1 2024-04-26 14:33:37        -1 user8
          -1 2024-04-26 14:38:34        -1 user83
          -1 2024-04-26 23:00:32        -1 user85
          -1 2024-04-27 02:41:53        -1 user86
          -1 2024-04-27 02:43:14        -1 user89
          -1 2024-04-27 02:43:36        -1 user9
          -1 2024-04-27 05:54:38        -1 user92
          -1 2024-04-26 12:14:00        -1 user93
          -1 2024-04-27 05:55:14        -1 user94
          -1 2024-04-27 06:26:30        -1 user95
          -1 2024-04-27 06:31:30        -1 user96
          -1 2024-04-27 06:42:22        -1 user97
          -1 2024-04-27 06:43:27        -1 user99
[lily@ip-10-99-0-88 ~]$ 
# copy a few user dropbxes into developer's fs with different size
[lily@ip-10-99-0-88 ~]$ rclone copy -v live-efs:/share/dropbox/user103 /share/dropbox/user103 (size: 17K)
[lily@ip-10-99-0-88 ~]$ rclone copy -v live-efs:/share/dropbox/user27 /share/dropbox/user27 (size: 556M)
[lily@ip-10-99-0-88 ~]$ rclone copy -v live-efs:/share/dropbox/user116 /share/dropbox/use116 (size: 1.1G)
[lily@ip-10-99-0-88 ~]$ ls -al /share/dropbox/
total 16
drwxr-xr-x. 5 centos centos 6144 May  7 08:18 .
drwxr-xr-x. 4 centos centos   35 May  7 04:41 ..
drwxrwxr-x. 2 centos centos 6144 May  7 08:19 use116
drwxrwxr-x. 2 centos centos 6144 May  7 08:14 user103
drwxrwxr-x. 4 centos centos 6144 May  7 08:17 user27
[lily@ip-10-99-0-88 ~]$ 
[lily@ip-10-99-0-88 ~]$ cd /share/dropbox/user103/
[lily@ip-10-99-0-88 user103]$  /usr/local/bin/calculateChecksumSizes
Error: DOI is required!
Usage: /usr/local/bin/calculate_checksum_sizes <DOI>
Calculates and uploads MD5 checksums values and file sizes for the given DOI to the aws s3 bucket - gigadb-datasets-metadata.
[lily@ip-10-99-0-88 user103]$ /usr/local/bin/calculateChecksumSizes 111111
Created 1111111.md5
Created 1111111.filesizes
2024/05/07 08:22:59 INFO  : 1111111.filesizes: Copied (new)
2024/05/07 08:22:59 INFO  : 
Transferred:             65 B / 65 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.3s

2024/05/07 08:23:00 INFO  : 1111111.md5: Copied (new)
2024/05/07 08:23:00 INFO  : 
Transferred:            185 B / 185 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.3s
[lily@ip-10-99-0-88 user103]$ rclone ls aws_metadata:gigadb-datasets-metadata
      352 100006.filesizes
      596 100006.md5
      164 100039.filesizes
      137 100039.filesizes.original
      107 100142.filesizes
       68 102480.filesizes
      118 102480.md5
      105 102499.filesizes
      161 102499.md5
     3825 102515.filesizes
     5420 102515.md5
     2704 102519.filesizes
     2330 102519.md5
     2213 102520.filesizes
     3483 102520.md5
     1698 102522.filesizes
     1303 102522.md5
     4622 102523.filesizes
     7371 102523.md5
      764 102524.filesizes
      692 102524.md5
     5141 102526.filesizes
     9251 102526.md5
       65 1111111.filesizes
      185 1111111.md5
[lily@ip-10-99-0-88 user103]$ rclone delete aws_metadata:gigadb-datasets-metadata/1111111.filesizes -v
2024/05/07 08:20:06 INFO  : 1111111.filesizes: Deleted
[lily@ip-10-99-0-88 user103]$ rclone delete aws_metadata:gigadb-datasets-metadata/1111111.md5 -v
2024/05/07 08:25:06 INFO  : 1111111.md5: Deleted
[lily@ip-10-99-0-88 user103]$ 
[lily@ip-10-99-0-88 user103]$ rclone ls aws_metadata:gigadb-datasets-metadata
      352 100006.filesizes
      596 100006.md5
      164 100039.filesizes
      137 100039.filesizes.original
      107 100142.filesizes
       68 102480.filesizes
      118 102480.md5
      105 102499.filesizes
      161 102499.md5
     3825 102515.filesizes
     5420 102515.md5
     2704 102519.filesizes
     2330 102519.md5
     2213 102520.filesizes
     3483 102520.md5
     1698 102522.filesizes
     1303 102522.md5
     4622 102523.filesizes
     7371 102523.md5
      764 102524.filesizes
      692 102524.md5
     5141 102526.filesizes
     9251 102526.md5
[lily@ip-10-99-0-88 ~]$
```

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

A file `/etc/aws/credentials` was created manually in the bastion server as it is in the cngb ftp server, which provides credentials for user to interact with the aws s3 bucket `gigadb-datasets-metadata`, this credentials file will be shared with all the bastion users who need to access the  bucket `gigadb-datasets-metadata`.

In this implementation, bastion user will use rclone only to interact both wasabi and aws buckets, the only config `/home/$user/.config/rclone/rclone.conf` contains just the end points without credentials which will be retrieved as environment variables by setting `env_auth = true`, this helps to reduce chance of credential leakage and make rclone more robust.

Also the `no_check_bucket = true` is necessary, otherwise, when `rclone copy` will throw out this error:
```
Failed to copy: failed to prepare upload: AccessDenied: Access Denied
```

## Any issues with implementation?

The $doi.filesizes and the $doi.md5  files will be eventually moved to the wasabi bucket alongside with their corresponding files, there is ticket #1846 for it which will be implemented in future. After that, as a result, the `/etc/aws/credentials` file could be removed as only the wasabi credentials will be needed by the users.

The manual mounting of the efs in this PR just for creating an environment for testing the script `calculateChecksumSizes` and it is just one-off, as the auto-mounting will be implemented in the PR https://github.com/gigascience/gigadb-website/pull/1828.

## Any changes to automated tests?

None.

## Any changes to documentation?

None.

## Any technical debt repayment?

All the customized scripts has been moved to `/usr/local/bin` and the suffix `.sh` has been removed, and the script can be executed as below:

### As a centos user
```
[centos@ip-10-99-0-88 ~]$ ls /usr/local/bin/
__pycache__  calculateChecksumSizes  createReadme  databaseReset  datasetUpload  docker-compose  node_exporter  postUpload  rclone  updateUrls  wsdump.py
[centos@ip-10-99-0-88 ~]$ 
[centos@ip-10-99-0-88 ~]$ /usr/local/bin/databaseReset
...
+ source .env
++ PGDATABASE=gigadb
.
.
.
+ docker stop pg9_3
pg9_3
+ rm -f /home/centos/converted/gigadbv3_20240506.backup
+ rm -f /home/centos/downloads/gigadbv3_20240506.backup
...
[centos@ip-10-99-0-88 ~]$
```

### As a bastion user
```
[lily@ip-10-99-0-88 ~]$ ls
uploadDir
[lily@ip-10-99-0-88 ~]$ ls /usr/local/bin/
__pycache__  calculateChecksumSizes  createReadme  databaseReset  datasetUpload  docker-compose  node_exporter  postUpload  rclone  updateUrls  wsdump.py
[lily@ip-10-99-0-88 ~]$ 

[lily@ip-10-99-0-88 ~]$ cd /share/dropbox/user103/
[lily@ip-10-99-0-88 user103]$ /usr/local/bin/calculateChecksumSizes
Usage: /usr/local/bin/calculateChecksumSizes <DOI>
Calculates and uploads MD5 checksums values and file sizes for the given DOI to the aws s3 bucket - gigadb-datasets-metadata.
[lily@ip-10-99-0-88 user103]$ /usr/local/bin/calculateChecksumSizes 111111
Created 111111.md5
Created 111111.filesizes
2024/05/07 14:14:46 INFO  : 111111.filesizes: Copied (new)
2024/05/07 14:14:46 INFO  : 
Transferred:            106 B / 106 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.3s

2024/05/07 14:14:47 INFO  : 111111.md5: Copied (new)
2024/05/07 14:14:47 INFO  : 
Transferred:            287 B / 287 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.3s
[lily@ip-10-99-0-88 user103]$ ls
111111.filesizes  111111.md5  AD25.txt  NO25.txt  readme.txt  user103.md5
[lily@ip-10-99-0-88 user103]$ /usr/local/bin/calculateChecksumSizes 111111
Created 111111.md5
Created 111111.filesizes
2024/05/07 14:22:23 INFO  : 111111.filesizes: Updated modification time in destination
2024/05/07 14:22:23 INFO  : 
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.2s

2024/05/07 14:22:23 INFO  : 111111.md5: Updated modification time in destination
2024/05/07 14:22:23 INFO  : 
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.2s

[lily@ip-10-99-0-88 user103]$ ls
111111.filesizes  111111.md5  AD25.txt  NO25.txt  readme.txt  user103.md5
```

## Any improvements to CI/CD pipeline?

None.

### CODE REVIEW

**Comment by rija** [comment]
@kencho51 you can mention #1846 in your Known issues section now.

**Review by rija — COMMENTED** [review]
Hi @kencho51

**praise**: functionality works
**praise**: there is SOP for developers
**praise**: code looks mostly fine

**issue**: the steps for creating directory `/etc/aws/` and populating `/etc/aws/credentials` are manual, which means there will be human errors.
**suggestion**: Those should be done as Ansible tasks in the bastion playbook. You could retrieve the credentials from Gitlab API (cnhk-infra is just a different project so has a different project id). But given this part of the functionality has limited life time,  it's also fine if the Ansible task creates the shared credentials file with explanative placeholders values (e.g: "here goes value of gigadb_dataset_metadata_aws_access_key_id from cnhk-infra project")

**issue**: There is a functional test failing (both locally and on CI) on this branch (`FilesCommandCest: Try to update md5 file attributes`) will need fixing. To be fair, it's' failing on `develop` too, but this failure is blocking any pipeline deployment to staging on Forks and Upstream
**suggestion**: see if it's easy fix, otherwise disable it, and create a Github issue labelled as high impact bug and mention it in the known issues

**issue**: the SOP feels incomplete as focused on using the tools, rather than setting it up
**suggestion**: Whoever is going to deploy this on Upstream staging and live may not have enough information with the SOP's current content, try to ensure the SOP explains the setup (which part of bastion playbook to run, do we need to run users playbook?, ...)

**issue**: this tool is to be used by the curators, not developers
**suggestion**: Make a tutorial like for them and link it from GigaScience intranet

**issue** (non-blocking): the `display_usage()` function  in `md5.sh` serves no purpose, as it's only called once (premature optimisation)
**suggestion**: better inline the usage text where it is being used

**nitpick**: the preparation stage is unnecessarily complicated and dangerous
**suggestion**: it is easier (no need to manually create a rclone config on the server) and safer (no need to move private keys to Upstream live environment around to remote places) to download (with scp or sftp) the droboxes on your local dev machine and upload (with scp or sftp) them from there to the destination server

**chore**: rebase and fix conflict on CHANGELOG.md

**issue (security)**: in `md5.sh`, the rclone command is called without specifying full path. We cannot assume the shell script will always know where to find the `rclone` command (e.g: prefix the shell script with `sudo`). It's also a security risk, as if bad actor gets in and figures out bash PATH, they can put a compromised `rclone` at higher position to trick users in calling their version of the command)
**suggestion**: use absolute path to the location of `rclone` when calling it


**question**: the `rclone delete` commands didn't work for me on DOI 111111. It didn't delete the files.
```
$ rclone delete aws_metadata:gigadb-datasets-metadata/1111111.md5 -vvv
2024/05/15 15:51:47 DEBUG : rclone: Version "v1.60.0" starting with parameters ["rclone" "delete" "aws_metadata:gigadb-datasets-metadata/1111111.md5" "-vvv"]
2024/05/15 15:51:47 DEBUG : Creating backend with remote "aws_metadata:gigadb-datasets-metadata/1111111.md5"
2024/05/15 15:51:47 DEBUG : Using config file from "/home/minerve/.config/rclone/rclone.conf"
2024/05/15 15:51:48 DEBUG : Waiting for deletions to finish
2024/05/15 15:51:48 DEBUG : 4 go routines active
```
It worked when I used a different DOI
```
$ rclone delete aws_metadata:gigadb-datasets-metadata/222222.filesizes -vvv
2024/05/15 16:10:31 DEBUG : rclone: Version "v1.60.0" starting with parameters ["rclone" "delete" "aws_metadata:gigadb-datasets-metadata/222222.filesizes" "-vvv"]
2024/05/15 16:10:31 DEBUG : Creating backend with remote "aws_metadata:gigadb-datasets-metadata/222222.filesizes"
2024/05/15 16:10:31 DEBUG : Using config file from "/home/minerve/.config/rclone/rclone.conf"
2024/05/15 16:10:31 DEBUG : fs cache: adding new entry for parent of "aws_metadata:gigadb-datasets-metadata/222222.filesizes", "aws_metadata:gigadb-datasets-metadata"
2024/05/15 16:10:31 DEBUG : Waiting for deletions to finish
2024/05/15 16:10:32 DEBUG : 100006.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 100006.md5: Excluded
2024/05/15 16:10:32 DEBUG : 100039.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 100039.filesizes.modified: Excluded
2024/05/15 16:10:32 DEBUG : 100142.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102480.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102480.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102499.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102499.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102515.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102515.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102519.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102519.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102520.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102520.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102522.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102522.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102523.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102523.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102524.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102524.md5: Excluded
2024/05/15 16:10:32 DEBUG : 102526.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 102526.md5: Excluded
2024/05/15 16:10:32 DEBUG : 111111.filesizes: Excluded
2024/05/15 16:10:32 DEBUG : 111111.md5: Excluded
2024/05/15 16:10:32 INFO  : 222222.filesizes: Deleted
```

Not quite sure what is going on, and whether it's just me, will wait to see if @pli888 is seeing the same thing


**praise**: all tools are now in a more appropriate location
**note**: some of the docs on the GigaScience intranet will need updating to reflect the change of location of the tools
**praise**: the addition of new bats unit tests is excellent

**Comment by kencho51** [comment]
Hi @rija 

> **question**: the `rclone delete` commands didn't work for me on DOI 111111. It didn't delete the files.

I could delete the files `111111.*` after log in bastion as user `lily`:
```
[lily@ip-10-99-0-240 ~]$ rclone delete -v aws_metadata:gigadb-datasets-metadata/111111.filesizes --dry-run
2024/05/16 07:39:17 NOTICE: 111111.filesizes: Skipped delete as --dry-run is set (size 65)
[lily@ip-10-99-0-240 ~]$ rclone delete -v aws_metadata:gigadb-datasets-metadata/111111.filesizes
2024/05/16 07:39:22 INFO  : 111111.filesizes: Deleted
[lily@ip-10-99-0-240 ~]$ rclone delete -v aws_metadata:gigadb-datasets-metadata/111111.md5
2024/05/16 07:39:38 INFO  : 111111.md5: Deleted
[lily@ip-10-99-0-240 ~]$ rclone ls aws_metadata:gigadb-datasets-metadata
      352 100006.filesizes
      596 100006.md5
      647 100006.md5.modified
      137 100039.filesizes
      164 100039.filesizes.modified
      107 100142.filesizes
       68 102480.filesizes
      118 102480.md5
      105 102499.filesizes
      161 102499.md5
     3825 102515.filesizes
     5420 102515.md5
     2704 102519.filesizes
     2330 102519.md5
     2213 102520.filesizes
     3483 102520.md5
      849 102522.filesizes
     1303 102522.md5
     4622 102523.filesizes
     7371 102523.md5
      764 102524.filesizes
      692 102524.md5
     5141 102526.filesizes
     9205 102526.md5
[lily@ip-10-99-0-240 ~]$
```

**Comment by kencho51** [comment]
Hi @rija ,


> **issue**: the SOP feels incomplete as focused on using the tools, rather than setting it up **suggestion**: Whoever is going to deploy this on Upstream staging and live may not have enough information with the SOP's current content, try to ensure the SOP explains the setup (which part of bastion playbook to run, do we need to run users playbook?, ...)

Just follow the steps in the SOP `PRODUCTION_DEPLOY.md` to deploy tools and and `PRODUCTION_TROUBLESHOOT.md` to create the bastion user, and the user can follow the step in `PRODUCTION_USE_CUSTOMIZED_TOOLS.md` to use the customized tools

> **issue**: this tool is to be used by the curators, not developers **suggestion**: Make a tutorial like for them and link it from GigaScience intranet

The SOP was created for the Curators, the way of setting it up has already documented in SOP `PRODUCTION_DEPLOY.md` and and `PRODUCTION_TROUBLESHOOT.md`.

**Comment by rija** [comment]
> Hi @rija ,
> 
> > **issue**: the SOP feels incomplete as focused on using the tools, rather than setting it up **suggestion**: Whoever is going to deploy this on Upstream staging and live may not have enough information with the SOP's current content, try to ensure the SOP explains the setup (which part of bastion playbook to run, do we need to run users playbook?, ...)
> 
> Just follow the steps in the SOP `PRODUCTION_DEPLOY.md` to deploy tools and and `PRODUCTION_TROUBLESHOOT.md` to create the bastion user, and the user can follow the step in `PRODUCTION_USE_CUSTOMIZED_TOOLS.md` to use the customized tools
> 

When the manual serverside preps already mentioned have been incorporated into the bastion playbook, and the PRODUCTION_DEPLOY.md is updated to mention as a note  the need to replace the placeholder value in `/etc/aws/credentials`, then it should be fine.

> > **issue**: this tool is to be used by the curators, not developers **suggestion**: Make a tutorial like for them and link it from GigaScience intranet
> 
> The SOP was created for the Curators, the way of setting it up has already documented in SOP `PRODUCTION_DEPLOY.md` and and `PRODUCTION_TROUBLESHOOT.md`.

I can see two problems there:

1) The `docs/sop/`, were meant for holding the information needed by us developers (when wearing the devops hat) to assist us in safely operating GigaDB infrastructure (hence the name SOP), it wasn't meant to hold documentation for end users nor guidance for development stuff. That's also why I've recently created a `docs/developers` to move there the more development related docs. Otherwise it's going to be confusing about what docs is for whom and why it's called SOP

2) The curators made it very clear that's not the place they want to go to for the documentation about the tools they are using.

**Comment by rija** [comment]
@kencho51,

**suggestion**: Move the content of `docs/sop/PRODUCTION_USE_CUSTOMIZED_TOOLS.md` in `docs/users/calculate_md5_filesizes.md` and add a link to it on Giganet

**Comment by rija** [comment]
**suggestion**: for the user doc, it's best to have highly focused documentation files, so the `docs/users/calculate_md5_filesizes.md` should only be about running that script. Anything about rclone should be elsewhere (also I believe @pli888 has already got a draft of an rclone user docs)

**Comment by kencho51** [comment]
Hi @rija,

> 2\. The curators made it very clear that's not the place they want to go to for the documentation about the tools they are using.

Based on this, I think I better remove this doc, as the curators prefer to have it in the [intranet page](https://sites.google.com/gigasciencejournal.com/giganet/gigadb/curation/gs-curation-step-by-step?authuser=0).

**Review by rija — APPROVED** [review]
Hi @kencho51 

praise: happy with the changes made to remove all manual steps and curators docs

Based on that, I'm happy to approve.

**Review by pli888 — CHANGES_REQUESTED** [review]
**praise**: Functionality is working as described.
**praise**: Code looks good.
**note**: @rija wasn't able to execute `rclone delete aws_metadata:gigadb-datasets-metadata/1111111.md5 -vvv` because there is an extra `1` in `1111111.md5`.
**question**: Should the mint DOI functional and acceptance tests be unskipped now because DataCite have fixed the problem with their API?
**note**: Once this PR has been deployed to staging environment then curators' gs-curation-step-by-step intranet documentation needs to be updated with the correct command line calls to scripts in /usr/local/bin directory.
**chore**: Rebase with latest code in develop branch to resolve conflict with `CHANGELOG.md`.

**Comment by kencho51** [comment]
Hi @pli888,

> **question**: Should the mint DOI functional and acceptance tests be unskipped now because DataCite have fixed the problem with their API?

The commit for skipping the tests has been reverted.

>**chore**: Rebase with latest code in develop branch to resolve conflict with CHANGELOG.md.

The CHANGELOG.md has been updated.

**Review by pli888 — APPROVED** [review]
This PR looks good to approve now.

**Pull request merged**
