### PR TITLE
Update GigaDBUpload-template_v18.xls

### PR DESCRIPTION
**Pull request by only1chunts**
fix: updated the CV tab with new attributes from database attribute table

# Pull request for issue: no issue ticket created

This is a pull request for the following functionalities:

* enables spreadsheet users to utilise new valid attributes in the sample table

## How to test?
Enter one of the new attribute names (e.g. alt_acc_GSA_sample) in the blue cells of the heading row of the sample table
see the grey cell in row 3 under the one you have just edited change to show the relevant description of that attribute

### CODE REVIEW

**Comment by kencho51** [comment]
Hi @only1chunts,


**question:** Is the template in this PR as the same as found in https://github.com/gigascience/gigadb-website/blob/develop/gigadb/app/tools/excel-spreadsheet-uploader/template/GigaDBUpload-template_v18.xls?
**suggestion:**  If it is the same, this PR can be approved without merging, as the file has been uploaded to the upstream develop branch already.
**suggestion:** In future PR for updating the template version, please also attach sample spreadsheet file with data using the updated temple for testing purpose.

**Comment by only1chunts** [comment]
Answer to question, no it's not identical there are some new attributes
added. I did mention that in the comments, do those comments not get seen
anywhere?
I like your suggestion, I'll try to prepare an example sheet next time.
Thanks

**Comment by kencho51** [comment]
Hi @only1chunts, 

> Answer to question, no it's not identical there are some new attributes

**suggestion:** Then would be better to update the file name of the template in this PR, eg. GigaDBUpload-template_v19.xls, otherwise a merge conflict may happen.
**suggestion:** Also remove all the template files in `gigadb/app/tools/excel-spreadsheet-uploader/template`, which are not longer valid.
**suggestion:** And also, can you prepare a sample spreadsheet file to `gigadb/app/tools/excel-spreadsheet-uploader/xls`, so we can download it for testing?

**Comment by only1chunts** [comment]
attached is an example of the new spreadsheet utilising some of the newly added sample attributes
[GigaDBUpload-template_v18-test-example.xls](https://github.com/gigascience/gigadb-website/files/13857858/GigaDBUpload-template_v18-test-example.xls)
I would like the file name to remain unchanged as the functionality of the file has not changed so its still v18.
I'm Ok with the older version (v16) being removed / deleted. not sure how I'm meant to do that here though!?

**Comment by kencho51** [comment]
Hi @only1chunts 

**suggestion:** This is the github official doc: https://docs.github.com/en/desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop 

> attached is an example of the new spreadsheet utilising some of the newly added sample attributes [GigaDBUpload-template_v18-test-example.xls](https://github.com/gigascience/gigadb-website/files/13857858/GigaDBUpload-template_v18-test-example.xls)

**suggestion:** Please save this file to `gigadb/app/tools/excel-spreadsheet-uploader/xls` in this branch `updated-upload-spreadsheet-with-new-attributes` in your computer using github deskop, then commit and push it to this PR.

 > I would like the file name to remain unchanged as the functionality of the file has not changed so its still v18. 

**suggestion:** Then can you delete the already existing old v18 template in `gigadb/app/tools/excel-spreadsheet-uploader/template`  and put in new v18 template  in this branch `updated-upload-spreadsheet-with-new-attributes` in your computer using github deskop, then commit and push it to this PR?

> I'm Ok with the older version (v16) being removed / deleted. not sure how I'm meant to do that here though!?

**suggestion:** Go into `gigadb/app/tools/excel-spreadsheet-uploader/template` in this branch `updated-upload-spreadsheet-with-new-attributes` in your computer using github deskop, then delete v16 template, then commit and put it to this PR.

**Comment by rija** [comment]
Closing this one as superseded by PR #1890

**Pull request closed without merging**
