### PR TITLE
PostgreSQL database setup using CSV files

### LINKED ISSUE #6: YiiSession and yiisession tables in Postgresql database schema
There is a YiiSession table and a yiisession table in the Postgresql database schema. Both of these tables contain the same column names (id, expire and data). Are these two tables required or should one of them be removed?

@jessesiu and @only1chunts to decide what to do.

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #344, #6 

This is a pull request for the following functionalities:

* Export of data from a `gigadb` (production) PostreSQL database tables as CSV files
* Transformation of CSV files into Yii migration scripts
* Execution of Yii migration scripts to create a `gigadb` database containing 4 datasets for development work
* Execution of Yii migration scripts to create a `gigadb` production-like database for running tests and staging server deployment

## Changes to the database schema

The schema for the PostreSQL database is now created by Yii migration scripts in `protected/migrations/schema/`. Most of the scripts in this directory are responsible for creating a single table, with a tabular structure consistent with those in the current production PostgreSQL database.

At present, the `develop` branch contains 4 migration scripts in `protected/migrations/schema/`:
* `m181108_105104_widen_user_password_column.php`
* `m181128_090415_setup_curation_log_sequence.php`
* `m190527_025615_dataset_upload_status.php`
* `m191015_013705_alter_curation_comments.php`

These 4 migration scripts have been deleted in this pull request since they are no longer needed. Their schema changes are included in the `protected/migrations/schema/` Yii migration scripts.

`ops/configuration/yii-conf/main.php.dist` has been updated so that its configuration is not to auto-create the `YiiSession` table. Instead, this `YiiSession` table is created by a Yii migration script. This closes #6.

## Changes to the tests

Acceptance, functional and unit tests require data to be tested against and these come from `gigadb_testdata.pgdmp` and `production_like.pgdmp`. Both of these `pgdmp` files have been recreated with the schema defined by the Yii migration scripts in `protected/migrations/schema`. Using the original `pgdmp` files led to errors with their `pg_restore` process when executed against a database implemented with the new Yii migration scripts, which seem to be caused by conflicts between the original and latest schemas.

### Local dev build and deployment

Previously, `ops/configuration/postgresql-conf/bootstrap.sql` was used to deploy the PostgreSQL database in a `dev` deployment of GigaDB application. A `dev` PostgreSQL database is now deployed using Yii migration scripts in `protected/migrations/schema/` directory. Data is provided by Yii migration scripts in `protected/migrations/data/dev` which consists of datasets with the following identifiers: 100006, 100020, 100094, 100142 and 100213. These datasets are identical to those previously used to deploy a `dev` database. A database with production-like data can be deployed using Yii migration scripts in `protected/migrations/data/prod_like`. The datasets providing `prod_like` data were roughly selected by taking the latest 3 datasets from each dataset type. 

These data upload Yii migration scripts are created by `csv_yii_migration.js`, a NodeJS Javascript program that converts the CSV files in the `data/dev` folder. Again, prod_like data upload Yii migration scripts need to be created first by the `csv_yii_migration.js` NodeJS Javascript program using the CSV files in the `data/prod_like` folder. Execution of `csv_yii_migration.js` is automated as a step in `generate_config.sh` which itself is executed by `docker-compose run --rm config`. Prior to running `csv_yii_migration.js`, the `ops/scripts/generate_config.sh` script is also responsible for  installing `nodejs` and `npm` in the `config` container.

@rija please consider if it would be better if these commands to install these dependencies would be better located in the docker image file, otherwise installation of `nodejs` and `npm` happens every time we wish to run `generate_config.sh` in order to create/update CSV files.

The CSV files in the `protected/migrations/data/dev` and `protected/migrations/data/prod_like` directories have been created using `data/scripts/export_csv.sh`. This script was used to export the `dev` and `prod_like` CSV files from a production GigaDB PostgreSQL database restored from a pgdmp dump file obtained on 10/02/2020. `export_csv.sh` tries to ensure anonymity of user information, for example, email addresses have been replaced with a test gigasciencejournal.com account.

Documentation on how to use `export_csv.sh` and `csv_yii_migration.js` is available in `docs/DATABASE.md`. Information on how to use the schema and data Yii migration scripts can be found in the updated `gigadb-website/README.md` file.

`ops/configuration/variables/env-sample` has been updated with a new variable: `CSV_DIR=dev`. This is required by `generate.config.sh` which passes the `CSV_DIR` to the `export_csv.sh` script.

`ops/configuration/postgresql-conf/bootstrap.sql` is no longer provided as a volume to the `database` service in `ops/deployment/docker-compose.yml`. It  is no longer used to initialise the `dev` PostgreSQL database with schema and data which is now done by Yii migration scripts.

### Gitlab CI/CD build and deployment

The `csv_yii_migration.js` script requires a command-line argument defining the name of the directory in `gigadb-website/data` that contains the CSV files it should convert to Yii migration scripts. For the GitLab CI/CD pipeline, the directory name is provided by a variable called `CSV_DIR` with a value `prod_like` in the `gitlab-ci.yml` file.

The `gitlab-ci.yml` file has been updated to use the Yii migration scripts for creating the schema and uploading data into the tables in the `gigadb` PostgreSQL database on the [staging server](https://gigadb-staging.gigatools.net). The database is initially created using `gigadb-website/sql/production_like.pgdmp` using an `Ansible` role but two extra migration steps in `gitlab-ci.yml` will now:

1. Delete all tables and database objects in the `gigadb` database.
2. Reset the `tbl_migration` table.

The schema and data upload migration scripts are then executed by `gitlab-ci.yml`.

#### Docker Host on AWS server deployment using Terraform and Ansible

`docs/SETUP_CI_CD_PIPELINE.md` has been updated to state that Terraform version 0.11 should be used for creating an AWS EC2 server. It seems that Terraform 0.12 is not compatible with the 0.6.1 version of the `terraform-inventory` tool in use. 

Updated `ops/infrastructure/roles/postgres-preinstall/tasks/main.yml` with a working link to download the PostgreSQL database 9.6 package. The previous [https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm](https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm) link was broken and produces an error 404.

## Bug fixes

Corrected exclusion of @ORCID tests in `tests/acceptance` bash script.

## Future work

Data used for acceptance, functional and unit tests should be converted from their current formats to CSV files or Yii migration scripts. The test harness should also be updated to use such CSV files or Yii migration scripts.

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @pli888,

This looks great. Here are a few observations.

### (1) When I run the ``export_csv.sh`` as per described in ``DATABASE.md`` I get an error:

```
> data/scripts/export_csv.sh -i "8 22 144 200" -o custom -d gigadb
...
Creating: dataset.csv
data/scripts/export_csv.sh: line 175: psql: command not found

```

So the script assumes ``psql`` is installed on user's system. Could be a good idea to mention it in the docs or add a ``-s|--server`` option so we can run it through container service execution and thus fix the error below:

```
> docker-compose run --rm test data/scripts/export_csv.sh -i "8 22 144 200" -o custom -d gigadb
...
Creating: dataset.csv
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 54321?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 54321?
```

### (2) Regarding loading and executing node in the configuration script:

The ``csv_yii_migration.js`` works very well for me, stand alone or within ``generate_config.sh``.
However the code in ``generate_config.sh`` may have a couple of downsides:
 
 * using ``npm install x`` for dependencies make it harder to track and manage them. Better have them in a ``package.json`` file so that we (and CI/CD pipeline) can list/monitor them and manage their versions.
 * installing node on-demand as a side-effect of config template generation is counter-intuitive and restrictive.

 One approach (that I used in my feature branch) would be to create a container service in ``ops/deployment/docker-compose.yml`` for running the conversion. Something like this:

```
csv-to-migrations:
    image: node:13.5-buster
    volumes:
      - ${APPLICATION}/:/var/www
    shm_size: '1gb' # to avoid a known issue
    command: npm install && node /var/www/data/scripts/csv_yii_migration.js $CSV_DIR
```

Then we can call it as below any time we think we need to do so (without regenerating all the configuration files)

```
> docker-compose exec csv-to-migrations # uses the value of $CSV_DIR in .env
> docker-compose exec -e CSV_DIR=prod_like csv-to-migrations
```

### (3) Regarding the way the migration scripts are constructed:

I'm wondering whether programmatically constructing the Yii migration file with javascript will make our life harder in the future as the PHP code is inter-twinned with the Javascript code. An alternative approach would be to use a templating system: 

We make a template with the boilerplate Yii migration PHP code and use variables for the varying parts and ``csv_yii_migration.js`` will load the template and interpolate the variables. I don't expect lots of changes to the boiler plate, but we may want to improve them from time to time with potential new features from updated migration API, or use transactions or change/condition the way we handle downgrades, fix issues, etc...

It would also make debugging and code change easier as the migration script only contain JS and the PHP stays in the template. It's already a recurring idiom in the code base (Yii MVC, generate_config.sh and its *.dist, email TWIG templates and Vue.js in my feature branch, Ansible and its *.j2 files). If taking that approach, better select a syntax similar to the template we already that make extensive use of ``{}``. In Javascript, that include ``mustache`` and ``handlebars`` libraries.

**Comment by pli888** [comment]
Addressing @rija's observations:

### (1) Issues with running export_csv.sh

The `export_csv.sh` has been updated so that it should now only be executed using the `test` container as suggested:
```
$ docker-compose run --rm test data/scripts/export_csv.sh -i "8 22 144 200" -o custom -d gigadb
```

### (2) Regarding loading and executing node in the configuration script

As suggested, a `csv-to-migrations` service has been defined in `docker-compose.yml` and is used to run the `csv_yii_migration.js` JS script.

### (3) Regarding the way the migration scripts are constructed

As suggested, `csv_yii_migration.js` has been updated to use `handlebars` to dynamically generate Yii migration scripts. It uses a single template `ops/configuration/yii-conf/migration.php.dist` which is able to transform all CSV files containing GigaDB PostgreSQL data into Yii migration scripts.

**Comment by rija** [comment]
Hi @pli888,

It works fine now and the changes look good.

I was wondering, since we have the following environment variables in ``.secrets``

```
GIGADB_HOST=
GIGADB_USER=
GIGADB_PASSWORD=
GIGADB_DB=
```

that can be configured differently per environment or for other reasons,
maybe we could use them in ``export_csv.sh`` instead of the hard-coded defaults.

The way it's been done in the other shell scripts is by adding this snippet near the top:

```
set -a
source /var/www/.secrets
set +a
```

**Comment by pli888** [comment]
@rija I've added the following new database variables into the `ops/configuration/variables/secrets-sample` file for use by `export_csv.sh`. The reason for these new variables is because `$GIGADB_DB` isn't usually the database I export CSV files from. 
```
EXPORT_CSV_GIGADB_DB=
EXPORT_CSV_GIGADB_HOST=
EXPORT_CSV_GIGADB_USER=
EXPORT_CSV_GIGADB_PASSWORD=
```

**Comment by pli888** [comment]
@rija I've added the use of the `csv-to-migrations` service into `.gitlab-ci.yml` for generating Yii migration scripts for the staging server so I think this pull request is ready to be merged into the `develop` branch now.

**Review by rija — APPROVED** [review]
Yes,that makes sense to me too.
All good.

**Pull request merged**
