### PR TITLE
feature:456 update datacite schema

### PR DESCRIPTION
**Pull request by alli83**
# Pull request for issue: #456 

This is a pull request for the following functionalities:

Improve DataCite metadata by migrating to Datacite version 4.6 + order authors by rank (for dataset as xml) 

## How to test?

connect as admin
go to Dataset page
click "mint DOI" 
you should see the xml saved following Datacite schema version 4.6

## Any changes to automated tests?

test added

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @alli83,

**praise**: the XML schema sent to Datacite is updated to latest schema capabilities
**praise**: all tests are passing locally and on CI
**issue**: it looks like the XML generator is adding Sample information inside the `subjects` section used for the dataset types, which doesn't seems right

example for dataset 102614:

```
<subjects>
    <subject xml:lang="en-US">
      Genomic
    </subject>
    <subject xml:lang="en-US">
      Transcriptomic
    </subject>
    <subject xml:lang="en-US">
      <subject xml:lang="en-US" subjectscheme="NCBI taxonomy" schemeuri="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi" classificationcode="51549">
      </subject>
    </subject>
  </subjects>
```

we can see the dataset types for 102614: Genomic, Transcriptomic
but there is a third element which is a dataset sample.

**suggestion**: should sample info be a related identifier that's part of some collection ?  
It is not present in the legacy XML and it is not mentioned in #456,  can we just remove the code that does this until we've flesh out how to represent it  ?  (@only1chunts feel free to comment)

**Comment by only1chunts** [comment]
I think it's safe to remove the code relating to the samples table.

**Comment by alli83** [comment]
@rija @only1chunts ok I'll look into it then.

**Comment by alli83** [comment]
@rija which part is causing the issue exactly?

**Review by rija — APPROVED** [review]
Hi @alli83,

**praise**: the issue with extraneous subject element is no more

based on that, I'm happy to approve this PR

**Comment by rija** [comment]
@alli83,
merged now. Thank you.

**Pull request merged**
