### PR TITLE
feature:1667 when minting, add log entry

### PR DESCRIPTION
**Pull request by alli83**
# Pull request for issue: #1667 

Add log entry when minting

## How to test?
 when I press "Mint DOI" button on a dataset form
I will have a record of when a DOI was created or refreshed

## Any changes to automated tests?

tests added

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @alli83,

**praise**: the functionality works
**praise**: tests are passing
**issue**: I think the database schema change was not necessary, as the `curation_log` table has an `action` and a `comments` columns that can be leveraged together.
**suggestion**: in the `action` column, put "DOI minting" and in the `comments` you can put the rest of the log message
**issue**: the minting is about the DOI (10006), not about the internal database id (8) which curators do not care about
**suggestion**: in the comments column, put `Dataset 100006 - Check DOI: OK - update md response: OK`
**chore**: rebase to resolve conflicts

**Review by rija — COMMENTED** [review]
Hi @alli83,

**praise**: action and comments are used for the curation log entry of doi minting action
**praise**: DOI is used in curation log entry instead of dataset id
**question**: I was trying on my AWS deployment with various DOIs, and for one of them I got an inline error message 
"DOI status: 204. An error occurred" 
but the curation log entry only said "Dataset 200081 - Check DOI: DOI doesn't exist - create md response: OK"
shouldn't the curation log entry also mention that error?

**Comment by alli83** [comment]
@rija I reckon the problem doesn't come from the backend but from how the returned data is being interpreted

**Review by rija — APPROVED** [review]
Hi @alli83,

based on the latest changes, I'm happy to approve this PR.

**Review by pli888 — APPROVED** [review]
**praise**: Functionality works on my dev environment. After clicking on mint doi button, I can see new record created in curation_log table. If there is an error message returned from DataCite about an DOI then information is logged in comments column; action column records `DOI Minting`. This curation log entry is displayed on the dataset's admin page.
**praise**: Functionality works on my staging server
**praise**: Acceptance test passes on my CI pipelines
**praise**: Code looks good to me

PR is good to approve.

**Comment by kencho51** [comment]
**note(non-blocking):** The `created_by` is hardcoded to `system` in the curation_log table, there is already a PR #1753 for it

**Pull request merged**
