### PR TITLE
Task 1211 remove public submissionwizard pages

### PR DESCRIPTION
**Pull request by rija**
# Pull request for issue: #1211

This is a pull request for the following functionalities:

* Hide the online submission form in the admin page `/datasetSubmission/upload` as per screenshot shown on #1211
* Migrate four legacy unit tests into Codeception
* Fixed Gitlab pipeline for Gigareview
* Add link to our community chat in the README file

## How to test?

* Login as an admin user
* Navigate to `/datasetSubmission/upload`
* The page will only show the spreadsheet upload form

I have tested on my local dev, as well as on my staging and on live AWS deployments. 
In the later two, you may need to create an admin user as pre-requisite (e.g: by running the query in `sql/joe_bloggs.sql` after  changing the value for `id` to the max(id)+1)

## How have functionalities been implemented?

Deleted the online submission form's code in `protected/views/datasetSubmission/upload.php`

## Any issues with implementation?

None

## Any changes to automated tests?

None (the spreadsheet upload form had already an acceptance test scenario `DatasetUpload.feature` and it's passing)

## Any changes to documentation?

Added link to Gigascience community chat on Matrix in the `README.md` file

## Any technical debt repayment?

Move the following unit tests from `protected/tests/unit` (managed by PHPUnit 5) to `tests/unit` (managed by Codeception):
* `DatasetFiledropTest.php`
* `TokenServiceTest.php`
* `StoredDatasetSamplesTest.php`
* `FiledropServiceTest.php`

## Any improvements to CI/CD pipeline?

Fixed pipeline failure in Gigareview by detecting (with `uname`) whether the platform is `amd64` or `arm`, so we can use the correct version of the headless browser container image (`selenium/standalone-chrome` and `seleniarm/standalone-chromium` respectively). That trick is already in use in the main GigaDB app automated tests

### CODE REVIEW

**Review by kencho51 — APPROVED** [review]
Hi @rija,

**praise:** The submission wizard has been hidden in both my dev and staging.
**praise:** All tests are passing locally and in gitlab CI/CD pipeline, including the legacy unit tests.
**praise:** GigaReview can be deployed to staging now after using the correct version of the headless browser container image.
**praise:** The updated matrix bage is working.
**issue(non-blocking):** The gitlab badges for pipeline status and coverage report are not showing.  

The code changes look good to me, so happy to approve this PR.

**Review by pli888 — COMMENTED** [review]
**praise:** The public submission wizard is now not present on the `/datasetSubmission/upload` page.

**issue:** I'm not able to instantiate my AWS staging environment in a clean `ops/infrastructure/envs/staging` directory as I get the error below when I execute `terraform plan`:

```
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_dockerhost.data.aws_ami.centos,
│   on ../../modules/aws-instance/aws-instance.tf line 67, in data "aws_ami" "centos":
│   67: data "aws_ami" "centos" {
│ 
╵
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_bastion.data.aws_ami.centos,
│   on ../../modules/bastion-aws-instance/bastion-aws-instance.tf line 35, in data "aws_ami" "centos":
│   35: data "aws_ami" "centos" {
```

**suggestion:** It feels like the `CentOS 8.4.2105 x86_64` AMI cannot be found anymore at least in `ap-northeast-1` region. When I filter for `CentOS Stream 8 x86_64` on line 72 in `aws-instance.tf` then the error for the application server disappears. I will try again tomorrow in case this is an intermittent problem.

Also tried looking for CentOS 8 AMI using:
```
# 125523088429 is used in aws-instance.tf and bastion-aws-instance.tf
$ aws ec2 describe-images --region ap-northeast-1 --owners 125523088429
$ aws ec2 describe-images --region ap-northeast-1 --filters "Name=name, Values=CentOS 8.4.2105 x86_64"
```

**Comment by kencho51** [comment]
Hi,

I have the same problem as below:
```
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_dockerhost.data.aws_ami.centos,
│   on ../../modules/aws-instance/aws-instance.tf line 67, in data "aws_ami" "centos":
│   67: data "aws_ami" "centos" {
│ 
╵
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_bastion.data.aws_ami.centos,
│   on ../../modules/bastion-aws-instance/bastion-aws-instance.tf line 35, in data "aws_ami" "centos":
│   35: data "aws_ami" "centos" {
│ 
```

And I have checked in AWS ec2 console in [ap-northeast2](https://ap-northeast-2.console.aws.amazon.com/ec2/home?region=ap-northeast-2#Images:visibility=public-images;owner=125523088429;v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false) that the owner  `125523088429` does not have `CentOS 8.4.2105 x86_64` ami anymore.

After I have updated the ami to `CentOS Stream 8 x86_64 20230530` in `aws-instance.tf` and `bastion-aws-instance.tf`, `terraform apply` could work.

Therefore, I think it is not an issue related to this PR.

**Comment by rija** [comment]
Hi @kencho51, @pli888,

I've resolved the Centos issue by applying the change suggested by Ken.

**Review by pli888 — APPROVED** [review]
**praise:** I can see the removal of the code submission wizard code from `views/datasetSubmission/upload.php` has stopped the submission wizard from being displayed on the /datasetSubmission/upload page on my staging server. The other code changes relating to fixing the pipeline for GigaReview, the relocation of the legacy unit tests and PSR-12 code formatting look fine to me. I approve this PR.

**Pull request merged**
