### PR TITLE
feat: make aws efs can be mounted to bastion server maunally

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1770

This is a pull request for the following functionalities:

* Make aws efs can be accessed from the bastion server by allowing the efs accepts ingress from the public subnets
* Can mount the aws efs to the bastion server
* The mounted aws efs can be managed as a SFTP through rclone
 
## How to test?

Describe how the new functionalities can be tested by PR reviewers

### Pre-requisite 
1. install rclone in local and also in the cngb ftp server
2. create `rclone.conf` as below:
```
[aws-efs]
type = sftp
host = $bastion-ip
user = $bastion-user
key_file = /path/to/$bastion-user-pem (will know after executing ansible user script)
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
```

### Spin up the staging instances and efs
 ```
% rm -rf ops/infrastructure/envs/staging
% mkdir ops/infrastructure/envs/staging
% cd ops/infrastructure/envs/staging/
% ../../../scripts/tf_init.sh --project \<your gitlab project path\>  --env staging --web-ec2-type t3.small --bastion-ec2-type t3.small
% terraform plan
% terraform apply
% terraform refresh
% ssh -i $bastion-centos-pem centos@$bastion-ip
[centos@ip-10-99-0-28 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M  8.5M  862M   1% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  1.6G   29G   6% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
# install aws efs utils for mounting the accesspoints
[centos@ip-10-99-0-140 ~]$ sudo yum update -y
[centos@ip-10-99-0-140 ~]$ sudo yum -y install git rpm-build make rust cargo openssl-devel
[centos@ip-10-99-0-140 ~]$ git clone https://github.com/aws/efs-utils
[centos@ip-10-99-0-140 ~]$ cd efs-utils
[centos@ip-10-99-0-140 ~]$ sudo make rpm
[centos@ip-10-99-0-140 ~]$ sudo yum -y install build/amazon-efs-utils*rpm
[centos@ip-10-99-0-164 ~]$ ls -al
total 16
drwx------.  5 centos centos  113 Apr 23 03:26 .
drwxr-xr-x.  3 root   root     20 Apr 23 03:16 ..
-rw-r--r--.  1 centos centos   18 Feb 10 08:05 .bash_logout
-rw-r--r--.  1 centos centos  141 Feb 10 08:05 .bash_profile
-rw-r--r--.  1 centos centos  376 Feb 10 08:05 .bashrc
drwx------.  2 centos centos   29 Apr 23 03:16 .ssh
drwxrwxr-x. 11 centos centos 4096 Apr 23 03:27 efs-utils
[centos@ip-10-99-0-164 ~]$ ls -al /efs-mountpoint/
total 0
drwxr-xr-x. 4 centos centos  35 Apr 23 03:16 .
drwx------. 5 centos centos 113 Apr 23 03:26 ..
drwxr-xr-x. 2 centos centos   6 Apr 23 03:16 config
drwxr-xr-x. 2 centos centos   6 Apr 23 03:16 dropbox
[centos@ip-10-99-0-164 ~]$ 
# get the file system id from terraform output or from aws efs dashboard
[centos@ip-10-99-0-164 ~]$ sudo mount -t efs -o tls,accesspoint=fsap-dropbox-id fs-id /efs-mountpoint/dropbox
[centos@ip-10-99-0-164 ~]$ sudo mount -t efs -o tls,accesspoint=fsap-confix-id fs-id /efs-mountpoint/config
[centos@ip-10-99-0-164 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M  8.6M  862M   1% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  2.7G   28G   9% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /efs-mountpoint/dropbox
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /efs-mountpoint/config
[centos@ip-10-99-0-164 ~]$  mount | grep efs-mountpoint
127.0.0.1:/ on /efs-mountpoint/dropbox type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20612,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
127.0.0.1:/ on /efs-mountpoint/config type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20291,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
[centos@ip-10-99-0-164 ~]$ 
[centos@ip-10-99-0-164 ~]$ sudo umount /efs-mountpoint/config
[centos@ip-10-99-0-164 ~]$ mount | grep efs-mountpoint/config
[centos@ip-10-99-0-164 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M  8.6M  862M   1% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  2.7G   28G   9% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
127.0.0.1:/    nfs4      8.0E     0  8.0E   0% /efs-mountpoint/dropbox
[centos@ip-10-99-0-164 ~]$ 
[centos@ip-10-99-0-164 ~]$ cd /efs-mountpoint/dropbox
[centos@ip-10-99-0-164 dropbox]$ curl http://212.183.159.230/100MB.zip --output 100MB.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  2228k      0  0:00:45  0:00:45 --:--:-- 6478k
[centos@ip-10-99-0-164 dropbox]$ 
[centos@ip-10-99-0-164 dropbox]$ ls -al
total 102404
drwxr-xr-x. 2 centos centos      6144 Apr 23 03:43 .
drwxr-xr-x. 4 centos centos        35 Apr 23 03:16 ..
-rw-rw-r--. 1 centos centos 104857600 Apr 23 03:43 100MB.zip
[centos@ip-10-99-0-164 dropbox]$ 
# use aws cli to check the size
% aws efs describe-file-systems --file-system-id fs-id
# or go to aws efs dashboard to confirm the size is 100MiB in `Size in Standard`.
```

### Create a bastion user for copy/delete files using rclone
```
% cd ops/infrastructure/envs/staging
% ../../../scripts/ansible_init.sh --env staging
% ansible-playbook -i ../../inventories users_playbook.yml -e "newuser=mary" --extra-vars="gigadb_env=staging"
% chmod 500 output/privkeys-$bastion-ip/mary
% ssh -i output/privkeys-$bastion-ip/mary mary@$bastion-ip
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Tue Apr 23 13:40:56 2024 from 14.199.148.232
[mary@ip-10-99-0-129 ~]$ ls -al
total 16
drwx------. 4 mary mary 112 Apr 23 09:13 .
drwxr-xr-x. 4 root root  32 Apr 23 09:11 ..
-rw-------. 1 mary mary 158 Apr 23 14:18 .bash_history
-rw-r--r--. 1 mary mary  18 Feb 10 08:05 .bash_logout
-rw-r--r--. 1 mary mary 141 Feb 10 08:05 .bash_profile
-rw-r--r--. 1 mary mary 376 Feb 10 08:05 .bashrc
drwx------. 2 mary mary  29 Apr 23 09:12 .ssh
drwx------. 2 mary mary   6 Apr 23 09:11 uploadDir
[mary@ip-10-99-0-129 ~]$ ls -al /efs-mountpoint/
total 4
drwxr-xr-x.  4 centos centos   35 Apr 23 09:07 .
dr-xr-xr-x. 18 root   root    246 Apr 23 09:07 ..
drwxr-xr-x.  2 centos centos    6 Apr 23 09:07 config
drwxr-xr-x.  2 centos centos 6144 Apr 23 14:10 dropbox
[mary@ip-10-99-0-129 ~]$ ls -al /efs-mountpoint/dropbox/
total 102404
drwxr-xr-x. 2 centos centos      6144 Apr 23 14:10 .
drwxr-xr-x. 4 centos centos        35 Apr 23 09:07 ..
-rw-rw-r--. 1 centos centos 104857600 Apr 23 13:43 100MB.zip
[mary@ip-10-99-0-129 ~]$ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  838M     0  838M   0% /dev
tmpfs          tmpfs     871M     0  871M   0% /dev/shm
tmpfs          tmpfs     871M  8.6M  862M   1% /run
tmpfs          tmpfs     871M     0  871M   0% /sys/fs/cgroup
/dev/nvme0n1p1 xfs        30G  2.7G   28G   9% /
tmpfs          tmpfs     175M     0  175M   0% /run/user/1000
127.0.0.1:/    nfs4      8.0E  100M  8.0E   1% /efs-mountpoint/dropbox
tmpfs          tmpfs     175M     0  175M   0% /run/user/1001
[mary@ip-10-99-0-129 ~]$ mount | grep efs-mountpoint
127.0.0.1:/ on /efs-mountpoint/dropbox type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20559,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
[mary@ip-10-99-0-129 ~]$ 
```

### Test the rclone config in local computer, make sure the rclone.conf mentioned in pre-requiste is reachable
```
% cd gigadb-website
% rclone --version
% rclone --config /path/to/rclone.conf lsd aws-efs:/efs-mountpoint
          -1 2024-04-23 17:07:10        -1 config
          -1 2024-04-23 22:10:44        -1 dropbox
% rclone --config rclone.conf ls aws-efs:/efs-mountpoint/dropbox
104857600 100MB.zip
% rclone --config /path/to/rclone.conf copy -v gigadb/app/tools/excel-spreadsheet-uploader/xls/100679newversion.xls  aws-efs:/efs-mountpoint/dropbox
2024/04/24 10:41:59 INFO  : 100679newversion.xls: Copied (new)
2024/04/24 10:41:59 INFO  : 
Transferred:           72 KiB / 72 KiB, 100%, 71.921 KiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         3.0s
 % rclone --config /path/to/rclone.conf -v gigadb/app/tools/excel-spreadsheet-uploader/xls/100679newversion.xls  aws-efs:/efs-mountpoint/dropbox
2024/04/24 10:42:04 INFO  : 
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         1.5s
% rclone --config /path/to/rclone.confls aws-efs:/efs-mountpoint/dropbox
    73728 100679newversion.xls
104857600 100MB.zip
% rclone --config /path/to/rclone.conf -v delete aws-efs:/efs-mountpoint/dropbox/100679newversion.xls 
2024/04/24 10:43:21 INFO  : 100679newversion.xls: Deleted
 % rclone --config rclone.conf -v delete aws-efs:/efs-mountpoint/dropbox/100679newversion.xls 
2024/04/24 10:43:27 ERROR : : error listing: directory not found
2024/04/24 10:43:27 ERROR : Attempt 1/3 failed with 2 errors and: directory not found
2024/04/24 10:43:27 ERROR : : error listing: directory not found
2024/04/24 10:43:27 ERROR : Attempt 2/3 failed with 2 errors and: directory not found
2024/04/24 10:43:27 ERROR : : error listing: directory not found
2024/04/24 10:43:27 ERROR : Attempt 3/3 failed with 2 errors and: directory not found
2024/04/24 10:43:28 Failed to delete with 2 errors: last error was: directory not found
% rclone --config r/path/to/rclone.conf ls aws-efs:/efs-mountpoint/dropbox                            
104857600 100MB.zip
```
### Login to cngb ftp server via https://uomc.genomics.cn/ after bgi vpn connected 
```
login: ken
ken@192.168.28.205's password: 
Last login: Tue Apr 23 11:59:22 2024 from 10.17.24.13

Welcome to Alibaba Cloud Elastic Compute Service !

-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[ken@cngb-gigadb-ftp ~]$ uname -a
Linux cngb-gigadb-ftp 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[ken@cngb-gigadb-ftp ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core
[ken@cngb-gigadb-ftp ~]$ df -hT
Filesystem                                                 Type      Size  Used Avail Use% Mounted on
/dev/vda1                                                  ext4       50G   17G   31G  36% /
devtmpfs                                                   devtmpfs   16G     0   16G   0% /dev
tmpfs                                                      tmpfs      16G     0   16G   0% /dev/shm
tmpfs                                                      tmpfs      16G  580K   16G   1% /run
tmpfs                                                      tmpfs      16G     0   16G   0% /sys/fs/cgroup
240704b1c5-eey91.cn-shenzhen.nas.aliyuncs.com:/data_upload nfs        10P  6.9T   10P   1% /data
192.168.56.61:/data/gigadb                                 nfs4      191T  166T   15T  92% /var/ftp/gigadb
tmpfs                                                      tmpfs     3.1G     0  3.1G   0% /run/user/5057
[ken@cngb-gigadb-ftp ~]$ 
[ken@cngb-gigadb-ftp ~]$ ls
logs
[ken@cngb-gigadb-ftp ~]$ ls /data/
JBrowse  data_upload  https_log
[ken@cngb-gigadb-ftp ~]$ ls /data/data_upload/
user1    user111  user16  user29  user41  user54  user67  user8   user92
user10   user112  user17  user3   user42  user55  user68  user80  user93
user100  user113  user18  user30  user43  user56  user69  user81  user94
user101  user114  user19  user31  user44  user57  user7   user82  user95
user102  user115  user2   user32  user45  user58  user70  user83  user96
user103  user116  user20  user33  user46  user59  user71  user84  user97
user104  user117  user21  user34  user47  user6   user72  user85  user98
user105  user118  user22  user35  user48  user60  user73  user86  user99
user106  user119  user23  user36  user49  user61  user74  user87  user_gaofei
user107  user12   user24  user37  user5   user62  user75  user88
user108  user120  user25  user38  user50  user63  user76  user89
user109  user13   user26  user39  user51  user64  user77  user9
user11   user14   user27  user4   user52  user65  user78  user90
user110  user15   user28  user40  user53  user66  user79  user91
[ken@cngb-gigadb-ftp ~]$ 
# install go and rclone by following https://go.dev/doc/install#requirements if not
[ken@cngb-gigadb-ftp ~]$ sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
[ken@cngb-gigadb-ftp ~]$ export PATH=$PATH:/usr/local/go/bin
[ken@cngb-gigadb-ftp ~]$ go version
go version go1.22.2 linux/amd64
[ken@cngb-gigadb-ftp ~]$ curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.1M  100 20.1M    0     0  2116k      0  0:00:09  0:00:09 --:--:-- 4154k
[ken@cngb-gigadb-ftp ~]$ unzip rclone-current-linux-amd64.zip
[ken@cngb-gigadb-ftp ~]$ cd rclone-*-linux-amd64
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo cp rclone /usr/bin/
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo chown root:root /usr/bin/rclone
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo chmod 755 /usr/bin/rclone
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo mkdir -p /usr/local/share/man/man1
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo cp rclone.1 /usr/local/share/man/man1/
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ sudo mandb
[ken@cngb-gigadb-ftp rclone-v1.66.0-linux-amd64]$ cd ..
[ken@cngb-gigadb-ftp ~]$ rclone version
rclone v1.66.0
- os/version: centos 7.5.1804 (64 bit)
- os/kernel: 3.10.0-862.14.4.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: none
[ken@cngb-gigadb-ftp ~]$ 
# copy the rclone.conf and the $bastion-user-pem in local to the cngb ftp server manually
[ken@cngb-gigadb-ftp ~]$ vi rclone.config
[ken@cngb-gigadb-ftp ~]$ vi $bastion-user-pem
[ken@cngb-gigadb-ftp ~]$ ls
efs-utils  go1.22.2.linux-amd64.tar.gz  logs  rclone-current-linux-amd64.zip  rclone-v1.66.0-linux-amd64  $bastion-user-pem rclone.config
[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf lsd aws-efs:/efs-mountpoint
          -1 2024-04-23 17:07:10        -1 config
          -1 2024-04-23 22:03:44        -1 dropbox
 [ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf ls aws-efs:/efs-mountpoint/dropbox 
104857600 100MB.zip
[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf copy -v rclone-current-linux-amd64.zip aws-efs:/efs-mountpoint/dropbox
2024/04/23 22:09:40 INFO  : rclone-current-linux-amd64.zip: Copied (new)
2024/04/23 22:09:40 INFO  : 
Transferred:   	   20.158 MiB / 20.158 MiB, 100%, 6.719 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         4.6s

[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf ls aws-efs:/efs-mountpoint/dropbox
104857600 100MB.zip
 21137057 rclone-current-linux-amd64.zip
[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf copy -v rclone-current-linux-amd64.zip aws-efs:/efs-mountpoint/dropbox
2024/04/23 22:10:31 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         1.4s

[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf delete -v aws-efs:/efs-mountpoint/dropbox/rclone-current-linux-amd64.zip
2024/04/23 22:10:44 INFO  : rclone-current-linux-amd64.zip: Deleted
[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf delete -v aws-efs:/efs-mountpoint/dropbox/rclone-current-linux-amd64.zip
2024/04/23 22:10:50 ERROR : : error listing: directory not found
2024/04/23 22:10:50 ERROR : Attempt 1/3 failed with 2 errors and: directory not found
2024/04/23 22:10:50 ERROR : : error listing: directory not found
2024/04/23 22:10:50 ERROR : Attempt 2/3 failed with 2 errors and: directory not found
2024/04/23 22:10:50 ERROR : : error listing: directory not found
2024/04/23 22:10:50 ERROR : Attempt 3/3 failed with 2 errors and: directory not found
2024/04/23 22:10:51 Failed to delete with 2 errors: last error was: directory not found
[ken@cngb-gigadb-ftp ~]$ rclone --config rclone.conf ls aws-efs:/efs-mountpoint/dropbox
104857600 100MB.zip

```

## How have functionalities been implemented?

Firstly, udpate the aws efs module to accept ingress from the public subnets of the VPC where the bastion server located. And also create the directory `/efs-mountpoint` with two sub directories `dropbox` and `config` during `terraform apply`, so when it is done, the `/efs-mountpoint/dropbox` and `/efs-mountpoint/config` would be already existed.

Then, in order to mount the accesspoint of the aws efs, [Amazon EFS client](https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html) needs to be installed in the bastion server. After it, the [accesspoint can be mounted](https://docs.aws.amazon.com/efs/latest/ug/mounting-access-points.html) using:
```
$ sudo mount -t efs -o tls,accesspoint=access-point-id file-system-id efs-mount-point
```

The aws efs can also be manged by using rclone after it is configured to have a sftp endpoint pointing to the bastion server. Details for setting up a sftp endpoint can refer to [here](https://rclone.org/sftp/).

For the basic steps of mounting, automounting and unmounting of the aws efs can refer to [here](https://repost.aws/knowledge-center/efs-mount-automount-unmount-steps)

## Any issues with implementation?

The `mount-efs.sh` is created for the `user_data` in the terraform script which aims to create mount directories and mount them to the aws efs automatically, further work is required in #1771 .

## Any changes to automated tests?
None

## Any changes to documentation?

None

## Any technical debt repayment?

None

## Any improvements to CI/CD pipeline?

None

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @kencho51,

Have only started looking into this, but here are some early remarks:

**issue**: The mount points that were agreed upon are not `/efs-mountpoint/dropbox` and `/efs-mountpoint/config` 
**suggestion**: Use the agreed upon mount points `/share/dropbox` and `/share/config`
**issue**: Given the approach I'm taking in #1826, we will  need the EFS to mounted on private subnets sooner than foreseen
**suggestion**:  The code `cidr_blocks = var.vpc.public_subnets_cidr_blocks` should be replaced with `cidr_blocks = [var.vpc.private_subnets_cidr_blocks, var.vpc.public_subnets_cidr_blocks]`

**Comment by kencho51** [comment]
Hi,

> **suggestion**: The code `cidr_blocks = var.vpc.public_subnets_cidr_blocks` should be replaced with `cidr_blocks = [var.vpc.private_subnets_cidr_blocks, var.vpc.public_subnets_cidr_blocks]`

You may encounter the following error if you have an existing efs:
```
╷
│ Error: [WARN] A duplicate Security Group rule was found on (sg-007b65a92b80e94f7). This may be
│ a side effect of a now-fixed Terraform issue causing two security groups with
│ identical attributes but different source_security_group_ids to overwrite each
│ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
│ information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 10.99.0.0/24, TCP, from port: 2049, to port: 2049, ALLOW" already exists
│       status code: 400, request id: 93807b23-8db0-4800-bcf4-54b737cb1f8b
│ 
│   with module.gigadb_efs.module.efs.aws_security_group_rule.this["vpc"],
│   on .terraform/modules/gigadb_efs.efs/main.tf line 180, in resource "aws_security_group_rule" "this":
│  180: resource "aws_security_group_rule" "this" {
│ 
╵
Releasing state lock. This may take a few moments...
```

The way to fix it is to destroy and recreate the efs as below:
```
% terraform destroy -target=module.gigadb_efs --auto-approve
% terraform apply -target=module.gigadb_efs --auto-approve
...
 # module.gigadb_efs.module.efs.aws_security_group_rule.this["vpc"] will be created
  + resource "aws_security_group_rule" "this" {
      + cidr_blocks              = [
          + "10.99.0.0/24",
          + "10.99.1.0/24",
          + "10.99.2.0/24",
          + "10.99.3.0/24",
          + "10.99.4.0/24",
          + "10.99.5.0/24",
        ]
      + description              = "NFS ingress from VPC subnets"
      + from_port                = 2049
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + security_group_rule_id   = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 2049
      + type                     = "ingress"
    }

Plan: 9 to add, 0 to change, 0 to destroy.
...

**Review by rija — APPROVED** [review]
Hi @kencho51,

**praise**: I have tested all the aspects of this PR (except the CNGB part) and it all worked as described
**praise**: I was also able to manually mount the EFS on the Web EC2 instance from private subnets.
**praise**: good idea clearly labelling the access-points Id outputs from terraform
**suggestion** (non-blocking): It would be beneficial for the instructions for manually listing and mounting the EFS access-points to be added to the `PRODUCTION_TROUBLESHOOTING.md` docs and for the CNGB instructions to be added to a new `EFS_DATA_MIGRATION.md` (and include the link to the Google spreadsheets listing dropboxes)

Based on the above, I'm happy to approve

**Comment by rija** [comment]
Hi @kencho51,

**note**: if you navigate to the AWS EFS dashboard, then click further on to the File Systems and select the one there,  then click the big "Attach" button on the top-right, you will see that you don't necessary need the AWS mount helper to manually mount the EFS as shown in the last example on that screen. It doesn't change anything for this PR (although the `nfs4` variant should probably be added in our documentation too), but when we get to automate this in the user_data, it's preferable sticking to the `nfs4` variant that doesn't requires the AWS mount helper.

**Comment by rija** [comment]
> Hi,
> 
> > **suggestion**: The code `cidr_blocks = var.vpc.public_subnets_cidr_blocks` should be replaced with `cidr_blocks = [var.vpc.private_subnets_cidr_blocks, var.vpc.public_subnets_cidr_blocks]`
> 
> You may encounter the following error if you have an existing efs:
> 
> ```
> ╷
> │ Error: [WARN] A duplicate Security Group rule was found on (sg-007b65a92b80e94f7). This may be
> │ a side effect of a now-fixed Terraform issue causing two security groups with
> │ identical attributes but different source_security_group_ids to overwrite each
> │ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
> │ information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 10.99.0.0/24, TCP, from port: 2049, to port: 2049, ALLOW" already exists
> │       status code: 400, request id: 93807b23-8db0-4800-bcf4-54b737cb1f8b
> │ 
> │   with module.gigadb_efs.module.efs.aws_security_group_rule.this["vpc"],
> │   on .terraform/modules/gigadb_efs.efs/main.tf line 180, in resource "aws_security_group_rule" "this":
> │  180: resource "aws_security_group_rule" "this" {
> │ 
> ╵
> Releasing state lock. This may take a few moments...
> ```
> 
> The way to fix it is to destroy and recreate the efs as below:
> 
> ```
> % terraform destroy -target=module.gigadb_efs --auto-approve
> % terraform apply -target=module.gigadb_efs --auto-approve
> ...


**thought**: We have to be careful with that kind of change when on production. When we already have data in the EFS, and make changes to that part of our terraform config that create such situation (not that we expect lots of change there), destroying the EFS is not an option.

**Comment by rija** [comment]
Hi again,

**note**: after playing around (see AWS Backup in the EFS dashboard), there is workaround the issue I was talking about. 
We can use AWS Backup to make a manual backup of EFS content before destructive changes, and then restore the backup to the newly recreated EFS

**Comment by rija** [comment]
> Hi @kencho51,
> 
> **note**: if you navigate to the AWS EFS dashboard, then click further on to the File Systems and select the one there, then click the big "Attach" button on the top-right, you will see that you don't necessary need the AWS mount helper to manually mount the EFS as shown in the last example on that screen. It doesn't change anything for this PR (although the `nfs4` variant should probably be added in our documentation too), but when we get to automate this in the user_data, it's preferable sticking to the `nfs4` variant that doesn't requires the AWS mount helper.
Hi 

Hi @kencho51,
You can ignore my comment above, if want to use access points (and not just filesystems), we will have to use the AWS mount helper

**Comment by rija** [comment]
Hi @kencho51,

So we don't have to build it every time,  I have saved the binary `/home/centos/efs-utils/build/amazon-efs-utils-2.0.1-1.el8.x86_64.rpm` here:

[https://s3.ap-northeast-1.wasabisys.com/infra-resources/amazon-efs-utils-2.0.1-1.el8.x86_64.rpm](https://s3.ap-northeast-1.wasabisys.com/infra-resources/amazon-efs-utils-2.0.1-1.el8.x86_64.rpm)

**Pull request merged**
