### PR TITLE
CI/CD pipeline to deploy readme tool to bastion server

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1179

This is a pull request for the following functionalities:

* CI/CD pipeline for deploying readme generator tool to bastion server on staging and live environments

### 1. Deploy staging server on AWS
```
$ cd /path/to/ops/infrastructure/envs/staging

# Copy terraform files to staging environment
$ ../../../scripts/tf_init.sh --project gigascience/forks/your-gigadb-website --env staging

# Provision with Terraform
$ terraform plan
$ terraform apply
$ terraform refresh

# Copy ansible files
$ ../../../scripts/ansible_init.sh --env staging

# Provision bastion ec2 server and restore RDS with latest database backup
$ ansible-playbook -i ../../inventories bastion_playbook.yml

# Provision webapp ec2 server with ansible
$ TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml
```

### 2. Log into your staging bastion server
```
# Get public IP address for bastion server
$ terraform output
ec2_bastion_private_ip = "10.88.8.888"
ec2_bastion_public_ip = "88.888.888.888"

# Log into bastion server
$ ssh -i ~/.ssh/your-private-key.pem centos@88.888.888.888
```

### 3a. Test readme tool using docker run command
```
$ docker run --rm -v /home/centos/readmeFiles:/app/readmeFiles registry.gitlab.com/$GITLAB_PROJECT/production_tool:staging /app/yii readme/create --doi 100142 --outdir /app/readmeFiles
```

You should see a new readme file for dataset 100142 in the readmeFiles folder:
```
[centos@10.88.8.888 ~]$ ls /home/centos/readmeFiles/
readme_100142.txt
```

### 3b. Test readme tool using shell script

There is shell script that has been written for the curators to use the readme tool:
```
$ ./createReadme.sh --doi 100142 --outdir /app/readmeFiles
```

You should see a new readme file for dataset 100142 in the readmeFiles folder:
```
[centos@10.88.8.888 ~]$ ls /home/centos/readmeFiles/
readme_100142.txt
```

### 4. Deploy live server on AWS
```
$ cd /path/to/ops/infrastructure/envs/live

# Copy terraform files to staging environment
$ ../../../scripts/tf_init.sh --project gigascience/forks/your-gigadb-website --env live

# Provision with Terraform
$ terraform plan
$ terraform apply
$ terraform refresh

# Copy ansible files
$ ../../../scripts/ansible_init.sh --env live

# Provision bastion ec2 server and restore RDS with latest database backup
$ ansible-playbook -i ../../inventories bastion_playbook.yml

# Provision webapp ec2 server with ansible
$ TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml
```

### 5. Log into your live bastion server
```
# Get public IP address for bastion server
$ terraform output
ec2_bastion_private_ip = "10.88.8.888"
ec2_bastion_public_ip = "88.888.888.888"

# Log into bastion server
$ ssh -i ~/.ssh/your-private-key.pem centos@88.888.888.888
```

### 6a. Test readme tool using docker run command
```
$ docker run --rm -v /home/centos/readmeFiles:/app/readmeFiles registry.gitlab.com/$GITLAB_PROJECT/production_tool:staging /app/yii readme/create --doi 100142 --outdir /app/readmeFiles
```

You should see a new readme file for dataset 100142 in the readmeFiles folder:
```
[centos@10.88.8.888 ~]$ ls /home/centos/readmeFiles/
readme_100142.txt
```

### 6b. Test readme tool using shell script

There is shell script that has been written for the curators to use the readme tool:
```
$ ./createReadme.sh --doi 100142 --outdir /app/readmeFiles
```

You should see a new readme file for dataset 100142 in the readmeFiles folder:
```
[centos@10.88.8.888 ~]$ ls /home/centos/readmeFiles/
readme_100142.txt
```

## How have functionalities been implemented?

There are 3 new Gitlab yaml files representing the pipelines for testing and deploying the readme tool on the bastion server in the staging and live environments:
* gitlab-config-test.yml
* gitlab-config-staging.yml
* gitlab-config-live.yml

These files are referred to in `gitlab-ci.yml` so they are integrated into the test, build staging, deploy staging, build live and deploy live stages of the GigaDB CI/CD pipeline.

A Docker image containing the source code for the readme tool is built using `Dockerfile-Production` and then stored in the Gitlab docker registry. This image is fetched by the Bastion server when the tool is first run. The tool can be used via a docker run command and also using the `createReadme.sh` shell script which wraps the docker run command.

Finally, the bastion ansible playbook has been updated with a step to copy the `createReadme.sh` shell script into the centos user's home directory where it can be executed by curators. Another new step in the bastion ansible playbook creates a readmeFiles directory where readme files can be saved to.

## Any issues with implementation?

The steps involving the files url tool in the `postUpload.sh` script appear to take a long time to run. This makes it difficult to test the execution of the readme tool in `postUpload.sh` so I have not included the tool in this shell script at this time. 

## Any changes to documentation?

The readme tool's [README.md](https://github.com/pli888/gigadb-website/blob/readme-tool-pipeline/gigadb/app/tools/readme-generator/README.md) file contains information on how to use the tool when deployed on the staging and live server.

## Any technical debt repayment?

GigaDB model and service class files used by the readme tool are now located in `gigadb-website/gigadb/app/models` and `gigadb-website/gigadb/app/services`, a more sensible location than in the `gigadb/app/worker/file-worker` directory. The namespace and path to the classes are mapped to each other in the readme tool's composer.json file. The GigaDB model and service classes are mounted as volumes in a local deployment whereas they are copied into /gigadb/app/ in the Docker production image for use in staging and live environment.

The GigaDB model and service classes are used in tests so these classes have been updated to reflect the change in namespaces for the GigaDB model and service classes.

## Any improvements to CI/CD pipeline?

The GigaDB CI/CD pipeline now contains pipelines for testing, building and deploying the readme tool on staging and live servers as described above.

### CODE REVIEW

**Review by rija — CHANGES_REQUESTED** [review]
Hi @pli888,

**praise**: tests suite are passing and CI/CD pipeline is green on my staging and live environments
**praise**: the code involved in implementing the functionality or adjacent to it follow PSR12
**praise**: several of the GigaDB Yii2 models classes are now in the correct place where they could be used by multiple applications
**praise**: The implementation of  code and deployment  configuration (PSR-4, Docker, Ansible, bash, Gitlab)  is nicely done

**issue**: the `ReadmeGeneratorBuildLive` job executes automatically.

Instead, it should be a manual job (like all jobs in the `live build` stage should, because we need to control deployment to live).
I know you took inspiration from  the job `XLSUploaderBuildLive`, which has the same problematic behaviour that need corrected. The `FilesUrlsUpdaterBuildLive` job is the example to emulate in that area.

**suggestion**: I think services classes are intended for functionalities that have the potential to be useful across the board (think download, email, url operations, captcha,...) without being specific to the domain. Generating readme doesn't really fit that pattern. It's probably best to place the readme generator backend method in a `component` directory inside the Readme generator tool directory instead of in a `DatasetService` class (I've made the same correction in my current work that you took inspiration from).

**polish**: for each environment, I'd put the build and deploy jobs in separate gitlab configuration files, to avoid accidentally altering the wrong job when we meant to change the other one, and make it instant to find the right job when search-by-typing the file name in the IDE

**Comment by pli888** [comment]
@rija

> The ReadmeGeneratorBuildLive job executes automatically. Instead, it should be a manual job (like all jobs in the live build stage should, because we need to control deployment to live).

The `ReadmeGeneratorBuildLive` job is now a manual job. I have also updated `XLSUploaderBuildLive` to be a manual job as technical debt.

>It's probably best to place the readme generator backend method in a component directory inside the Readme generator tool directory instead of in a DatasetService class (I've made the same correction in my current work that you took inspiration from).

The readme generator code can now be found in a `ReadmeGenerator.php` class within a `components` directory inside the `readme-generator` tool directory.

>for each environment, I'd put the build and deploy jobs in separate gitlab configuration files

This is now done for the readme tool. It is also done for the spreadsheet upload tool as technical debt.

**Review by kencho51 — CHANGES_REQUESTED** [review]
Hi @pli888,

**praise:** Readme tool is working on both staging and live bastion servers.

**praise:** Units test and functional tests for Readme generator are passing locally and in gitlab pipeline.

**praise:** Splitting each gitlab stage into a single file which makes it modular, it is easier for integrating into the main CI/CD pipeline by just `include` them into the main `gitlab-ci.yml` file.

**suggestion:** Update the command in README.md at line 121 to `docker-compose run --rm tool ./vendor/bin/codecept run --debug tests/unit/components/ReadmeGeneratorTest.php`

**suggestion:** Make `components/ReadmeGenerator.php` conform to PSR12.

**question:** Since the readme generator backend method  has been relocated to `readme-generator/components/ReadmeGenerator.php`, this file `gigadb/app/worker/file-worker/components/DatasetService.php` can be removed as the code is duplicated?

**Comment by pli888** [comment]
>suggestion: Update the command in README.md at line 121 to docker-compose run --rm tool ./vendor/bin/codecept run --debug tests/unit/components/ReadmeGeneratorTest.php

Done.

>suggestion: Make components/ReadmeGenerator.php conform to PSR12.

Done

>question: Since the readme generator backend method has been relocated to readme-generator/components/ReadmeGenerator.php, this file gigadb/app/worker/file-worker/components/DatasetService.php can be removed as the code is duplicated?

Good spot - `gigadb/app/worker/file-worker/components/DatasetService.php` has been deleted now.

**Review by rija — APPROVED** [review]
praise: functionality is working on my staging and live AWS deployment
praise: suggestions were implemented
polish:  PSR12 for the controller (`FOUND 13 ERRORS AND 1 WARNING AFFECTING 7 LINES`)

On that basis, happy to approve

**Review by kencho51 — APPROVED** [review]
Hi @pli888,

**praise:** Extra component class has been remove, typo in readme has been fixed, PSR12 conformity has been made.

All changes look good to me, happy to approve this PR.

**Pull request merged**
