### PR TITLE
Review workers

### PR DESCRIPTION
**Pull request by rija**
# Pull request for issue: #1041

This is a pull request for the following functionalities:

1. Setup boilerplate project files for new application Gigareview
2. Initial setup of devops infrastructure for new application Gigareview
3. Implement Yii2 command to fetch Editorial Manager reports

### Locally

As prerequisite, ensure the following variables are defined in Gitlab at project level

| Key | Value    | Masked | Environments |
| --- |----------|--------|--------------|
| REVIEW_DB_DATABASE | reviewdb | no     | dev|
| REVIEW_DB_HOST | reviewdb | no     | dev|
| REVIEW_DB_PASSWORD | reviewdb | yes    | dev|
| REVIEW_DB_PORT | 5432     | no | dev|
| REVIEW_DB_USERNAME | reviewdb | no | dev|

Start the app:

```
$ cd gigareview
$ ./up.sh

```
Run the tests:

```
$ ./tests/unit_runner
$ ./tests/functional_runner
$ ./tests/acceptance_runner
```

List the files on the sftp server for reports with pattern "latest" using the ``yii`` utility:
```
$ docker-compose run --rm console ./yii fetch-reports/list latest 
```

List the files from the test data using ``yii_test`` utility:
```
$ docker-compose run --rm console ./yii_test fetch-reports/list latest

```

Fetch the latest reports of each of the five types and publish them to the message queue:
```
$ docker-compose run --rm console ./yii fetch-reports/fetch
```

### On staging

As prerequisite, ensure the following variables are defined in Gitlab at project level:

| Key | Value            | Masked  | Environments |
| --- |------------------|---------|--------------|
| REVIEW_DB_DATABASE | reviewdb         | staging | staging      |
| REVIEW_DB_HOST | reviewdb         | no      | staging      |
| REVIEW_DB_PASSWORD | (choose a value) | yes     | staging      |
| REVIEW_DB_PORT | 5432             | no      | staging      |
| REVIEW_DB_USERNAME | reviewdb         | no      | staging      |

Provision a staging environment the usual way:

```
$ cd /Users/owner/code/gigadb-website/ops/infrastructure/envs/staging
$ ../../../scripts/tf_init.sh --project gigascience/forks/rija-gigadb-website --env staging 
$ terraform plan
$ terraform apply
$ terraform refresh
$ ../../../scripts/ansible_init.sh --env staging
$ env TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml
$ ansible-playbook -i ../../inventories bastion_playbook.yml -vvv -e "backupDate=20220509"
```

#### Manual testing

SSH to the bastion server then change to gigareview directory

```
$ cd /home/centos/gigadb-website-review-workers/gigareview
```

Then run the list and fetch commands like in on local environment:
```
$ docker-compose run --rm console ./yii fetch-reports/list latest 
$ docker-compose run --rm console ./yii fetch-reports/fetch latest
```

>Note: ``yiit_test`` is not installed on bastion as we are not running automated tests in that environment

#### Cronjob

List active cronjobs:
```
$ crontab -l
```

You should see: 

```
#Ansible: Fetch latest EM reports
00 13 * * * cd /home/centos/gigadb-website-review-workers/gigareview ; /usr/local/bin/docker-compose run --rm console ./yii fetch-reports/fetch latest 2> $HOME/logs/em_reports_ingest_errors.log 1> $HOME/logs/em_reports_ingest_output.log
```

You can alter the time to something near future to ensure the cronjob function

### On CI

When deploying to CI, ensure that the jobs `` GigaReviewTest`` and ``GigaReviewBuildStaging`` pass.

### 1. Setup boilerplate project files for new application Gigareview

I used composer to setup a Yii2 advanced template. The exact command is described in the README.
Unlike with File Upload Wizard, I sticked to the Yii2 prescribed way of handling configuration file which is described here:
https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/structure-environments

The key project resources for handling the configurations are:

* ``gigareview/config-sources``: contains configuration templates and examples files
* ``gigareview/generate_config.sh``: generate configuration file populated with gitlab variables for a given environment
* ``gigareview/environments``: the directory referred to in the link above
* ``gigareview/environments/index.php``: List of supported environments and the files associated with it
* ``database.sh``: bootstrap the Gigareview's RDBMS
* ``docker-compose.yml``: describe the container service the application is made of. Also refers to the dockerfiles needed to build those services.
* ``up.sh``: launch the application and its dependencies after configuring everything that need configuring
* ``composer.json`` and ``composer.lock``: handle PHP dependencies

### 2. Initial setup of devops infrastructure for new application Gigareview

The important changes are the ones made to ``ops/infrastructure/bastion_playbook.yml``

It implements what's necessary for the EM reports ingester to run on a staging environment.
The pattern should be familiar as it follow the other recent additions to the bastion playbook.

``gigareview/gitlab-config.yml`` was created to implement a deployment pipeline (and included in ``.gitlab-config.yml``), but is not finished and only do:

* run automated tests (continuous integration)
* build a production container image for GigaReview and push it to Gitlab Registry

### 3. Implement Yii2 command to fetch Editorial Manager reports

Only two files are needed to implement the main functionality, a controller and a model class:

* ``gigareview/console/controllers/FetchReportsController.php``
* ``gigareview/common/models/Ingest.php``

Together they implement the essence of what's described in the workflow diagram I've added to the project (it's not updated - it's from the prototype days -, but the message queue based backoffice workers workflow is unchanged):

For each type of reports, download the latest, read the content and publish it to a specific message queue for that report type.
Along the way, we store workflow status in the database for debugging, auditing, and housekeeping.

## Any issues with implementation?

1. At the moment, Gigareview doesn't share its infrastructure systems (RDBMS and MQ). 
The sharing is tied to a fully functional deployment pipeline which was just started in this PR (see next functionality) and is far from complete

2. Gigareview doesn't have an immutable deployment artefacts yet like GigaDB has for its web app (this problem is shared by the  dataset spreadsheet uploader too). This will be fixed when we complete the pipeline work.

## Any changes to automated tests?

It's a new yii2 application with a Codeception setup.
The automated tests are kept closed to the code under tests:

* the functional tests and acceptance tests for the reports fetching functionality are in ``gigareview/console/tests`` as the GigaReview's CLI subsystem is where the functionality is implemented
* Unit tests for the ``Ingest`` model class are in ``gigareview/common/tests`` as model classes are kept in ``common`` because they are  shared across all subsystems of the Gigareview application (CLI, public web, api).

## Any changes to documentation?

I have added all the diagrams I made for the data model and workflow pertaining to the GigaReview application in ``gigareview``.
And I have added the overall system architecture diagram in ``docs``.
The ``gigareview/README.md`` has a getting started section and how it was created section (more infos).

## Any technical debt repayment?

N/a

## Any improvements to CI/CD pipeline?

Because I've implemented it in ``gigareview/generate_config.sh``, I have simplified the block in ``ops/scripts/generate_config.sh`` for fetching Gitlab variables so that:

* The jq filtering is more concise
* We can download more than 100 project level variables from Gitlab (up to 200 now)
* The variables from ``cnhk-infra`` group are now downloaded too

### CODE REVIEW

**Comment by rija** [comment]
Hi @pli888, @kencho51,

I did forgot about it, so
I've updated this branch to add mention of which Gitlab variables need to be set, both in the ``gigareview/README.md`` and in the text of this PR.
Sorry about that.

**Comment by rija** [comment]
Hi @pli888, @kencho51,
I've just added a final commit to this PR with a diagram showing the EM Report Ingest architecture and workflow that we aim to implement eventually.
Thanks.

**Review by pli888 — APPROVED** [review]
After reviewing the code, I can see that GigaReview is a Yii2 advanced project. A cronjob will call the `actionFetch()` function in `FetchReportsController` to retrieve the latest Manuscript EM report from the SFTP server. It also pushes an `EMReport` job into the manuscript queue. There is a manuscript worker class which is currently empty but will contain implementation for ingesting the report when it is detected that a job is in the manuscript queue. All tests are passing locally and on my CI/CD pipeline. I approve this PR.

There are several files in this PR which seem superfluous:

* gigareview/frontend/tests/functional/ResendVerificationEmailCest.php
* gigareview/backend/tests/_data/login_data.php
* gigareview/backend/views/site/*.php
* gigareview/common/fixtures/UserFixture.php
* gigareview/common/mail/emailVerify-html.php
* gigareview/common/widgets/Alert.php
* gigareview/console/migrations/m130524_201442_init.php
* gigareview/console/migrations/m190124_110200_add_verification_token_column_to_user_table.php
* gigareview/environments/dev/backend/web/index.php
* gigareview/frontend/tests/_data/login_data.php
* gigareview/frontend/tests/functional/LoginCest.php and gigareview/frontend/tests/functional/* .php

These files have probably been automatically created as part of a Yii2 project. They might be required later so it might be easier to leave them in this PR.

**Comment by rija** [comment]
Hi @pli888,

Thanks. There are indeed boiler plate code created by Yii2 and I thought same as you initially.
However, after our PB refinement workshop on Friday where we talked about authentication service, 
I think the login/user related code in this project will never be used as I want to use Gigareview as testbed for a separate authentication.
So I'll remove the related redundant code.

Things like:

* gigareview/common/widgets/Alert.php
* gigareview/*/views/site/error.php

are generic and will be used when we start adding view layers in Gigareview, so I'll keep them.

 Those files:

* gigareview/*/views/site/index.php
* gigareview/frontend/web/css/site.css
* gigareview/frontend/web/favicon.ico

Are placeholder files. We will need the files with the same name but we will replace the content. 
I'll keep those files as well so we remember they will be needed.

**Review by kencho51 — APPROVED** [review]
Hi @rija,

All tests are passing locally and in gitlab pipelines, and this PR work could be deployed to my staging successfully. And the specific cron job for fetching the lates EM reports could be installed to bastion server using the updated bastion playbook.

After going through the code, what I understand is 
`gigareview/common/models/EMReportJob.php` is the worker for getting the content of the reports, `gigareview/console/controllers/FetchReportsController.php`  contains the action `fetch` that pushes the EM reports to the related queue regarding to the report type and action `list` that lists the EM reports in the remote ftp server, and `gigareview/common/models/Ingest.php` keeps track of the job state.

This PR provides an infrastructure for the `Review Workers`, it has the essential element to show how to connect different pieces together. I understand that future work based on  this PR will be needed like how to parse the manuscript report through the `manuscripts_q`.

All code looks to me, so I would like to approve this PR.

**Pull request merged**
