### PR TITLE
Fix update password error

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #859

This is a pull request for the following functionalities:

* A fix for updating password by a user on a staging deployment of GigaDB when provisioned with data from a current PostgreSQL database dump file.

In a database dump from the current live server, the `password` column in the `gigadb_user` table is `character varying(64)` but the password hash can be longer than 64 characters and therefore we see `ERROR: value too long for type character varying(64)`. This problem is not seen in a vanilla local dev installation because the `password` column in the `gigadb_user` table has already been set to `character varying(128)`.

## Changes to the database schema

A fix for the above problem is provided in the form of a `m300000_000100_update_password_column_gigadb_user_tab.php` migration script in the `fix_import` directory which changes the password column to `character varying(128)`.

## Changes to the provisioning

A new step has been added into `gigadb-deploy-jobs.yml` to execute the `m500000_000100_update_password_column_gigadb_user_tab` migration script during the deployment of a staging and a live server. This step fixes the `password` column in the `gigadb_user` table in the RDS instance. 

## Changes to the tests

`changePassword.feature` has been created to test the functionality of a user updating their password. Tests to check the creation of a new user account already exists in `NewUser.feature`.

### CODE REVIEW

**Review by rija — CHANGES_REQUESTED** [review]
Hi @pli888,

A couple of observations:

(1) This kind of database migration falls in the category of non revertible change because the data inserted after migration will likely be too big for the old column size.
So that if we are to revert migration to an older level, that migration's down method will fail:

```
> docker-compose run --rm application ./protected/yiic migrate down 1 --migrationPath=application.migrations.fix_import --interactive=0

Yii Migration Tool v1.0 (based on Yii v1.1.20)

Total 1 migration to be reverted:
    m500000_000100_update_password_column_gigadb_user_tab

*** reverting m500000_000100_update_password_column_gigadb_user_tab
    > execute SQL: ALTER TABLE gigadb_user
            ALTER COLUMN password TYPE character varying(64); ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(64). The SQL statement executed was: ALTER TABLE gigadb_user
            ALTER COLUMN password TYPE character varying(64); (/var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php:358)
#0 /var/www/vendor/yiisoft/yii/framework/db/CDbMigration.php(164): CDbCommand->execute(Array)
#1 /var/www/protected/migrations/fix_import/m500000_000100_update_password_column_gigadb_user_tab.php(13): CDbMigration->execute('ALTER TABLE gig...')
#2 /var/www/vendor/yiisoft/yii/framework/db/CDbMigration.php(79): m500000_000100_update_password_column_gigadb_user_tab->safeDown()
#3 /var/www/vendor/yiisoft/yii/framework/cli/commands/MigrateCommand.php(440): CDbMigration->down()
#4 /var/www/vendor/yiisoft/yii/framework/cli/commands/MigrateCommand.php(145): MigrateCommand->migrateDown('m500000_000100_...')
#5 [internal function]: MigrateCommand->actionDown(Array)
#6 /var/www/vendor/yiisoft/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /var/www/vendor/yiisoft/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#8 /var/www/vendor/yiisoft/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#9 /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#10 /var/www/vendor/yiisoft/yii/framework/yiic.php(33): CApplication->run()
#11 /var/www/protected/yiic.php(12): require_once('/var/www/vendor...')
#12 /var/www/protected/yiic(4): require_once('/var/www/protec...')
#13 {main}
*** failed to revert m500000_000100_update_password_column_gigadb_user_tab (time: 0.060s)
```

For this kind of change, the down method needs to be kept empty, so that revert operations can proceed all the way to target level.


(2) We probably should keep the name of Codeception features consistent and since the other Codeception features already use PascalCase, we should name the feature file ``ChangePassword.feature``

**Comment by pli888** [comment]
@rija

>This kind of database migration falls in the category of non revertible change because the data inserted after migration will likely be too big for the old column size.

Ok, I should have realised this. The `safeDown()` function is now empty.

>We probably should keep the name of Codeception features consistent and since the other Codeception features already use PascalCase, we should name the feature file ChangePassword.feature

This is done now.

**Comment by rija** [comment]
Hi @pli888,

migrations work great now, can do up and down no problem.

However I have two unrelated acceptance scenarios failing both on my local environment and CI 


```
1) Dataset spreadsheet upload: Allow users to upload dataset spreadsheet
 Test  tests/acceptance/DatasetUpload.feature:Allow users to upload dataset spreadsheet
 Step  I should see "dataset upload" 
 Fail  Failed asserting that  on page /site/login
--> Login / Signup
Search
Home
About 
Help 
Terms of use
Home login
Login
Please fill out the following form with your login credentials:
Fields with * are required.
Email Address *
Password *
Remember me next time Lost Password
Create account
database@gigasciencejournal.com
--> contains "Dataset Upload".

Scenario Steps:

 12. $I->see("Dataset Upload") at tests/_support/AcceptanceTester.php:53
 11. $I->amOnPage("/datasetSubmission/upload") at tests/_support/AcceptanceTester.php:37
 10. $I->click("Login") at tests/_support/AcceptanceTester.php:157
 9. $I->fillField("LoginForm[password]","gigadb") at tests/_support/AuthorSteps.php:26
 8. $I->fillField("LoginForm[username]","user@gigadb.org") at tests/_support/AuthorSteps.php:25
 7. $I->amOnPage("/site/login") at tests/_support/AuthorSteps.php:24

Artifacts:

Png: /var/www/tests/_output/DatasetUpload.Allow.users.to.upload.dataset.spreadsheet.fail.png
Html: /var/www/tests/_output/DatasetUpload.Allow.users.to.upload.dataset.spreadsheet.fail.html

---------
2) Dataset spreadsheet upload: Upload dataset metadata with an Excel spreadsheet
 Test  tests/acceptance/DatasetUpload.feature:Upload dataset metadata with an Excel spreadsheet
 Step  I check the field "agree-checkbox" 
 Fail  CSS or XPath element with id 'agree-checkbox' was not found.

Scenario Steps:

 12. $I->checkOption({"id":"agree-checkbox"}) at tests/_support/AcceptanceTester.php:149
 11. $I->amOnPage("/datasetSubmission/upload") at tests/_support/AcceptanceTester.php:37
 10. $I->click("Login") at tests/_support/AcceptanceTester.php:157
 9. $I->fillField("LoginForm[password]","gigadb") at tests/_support/AuthorSteps.php:26
 8. $I->fillField("LoginForm[username]","user@gigadb.org") at tests/_support/AuthorSteps.php:25
 7. $I->amOnPage("/site/login") at tests/_support/AuthorSteps.php:24

Artifacts:

Png: /var/www/tests/_output/DatasetUpload.Upload.dataset.metadata.with.an.Excel.spreadsheet.fail.png
Html: /var/www/tests/_output/DatasetUpload.Upload.dataset.metadata.with.an.Excel.spreadsheet.fail.html
```

**Comment by pli888** [comment]
@rija

> However I have two unrelated acceptance scenarios failing both on my local environment and CI

There is now a new test in `ChangePassword.feature` to fix this problem which was caused by the preceding test altering the password for `user@gigadb.org` that led to the Dataset spreadsheet upload tests failing since it was expecting `user@gigadb.org` to log in with the original password. The new test in `ChangePassword.feature` returns the original password to `user@gigadb.org`.

**Review by rija — APPROVED** [review]
Hi @pli888, 
The tests are all passing now, and the scenarios for that feature works well.
I'm happy to approve this PR.

**Review by kencho51 — APPROVED** [review]
Hi @pli888 ,

All tests are passing in my dev env and my CI/CD pipelines are passing as well.
And I could create a new user on staging server as expected. 
So, I would like to approve this PR.

**Pull request merged**
