### PR TITLE
Make tideways to monitor production environment

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1222 and #1223

This is a pull request for the following functionalities:

Configure `tideways` to monitor production environments (upstream staging and live).

## How to test?

Describe how the new functionalities can be tested by PR reviewers

#### EC2 webapp servers provisioning

```
1. Instantiate the staging servers
/gigascience/gigadb-website (deploy-tideways-from-upstream%=) % cd ops/infrastructure/envs/staging
# copy the updated aws-instance config
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % ../../../scripts/tf_
init.sh --project gigascience/upstream/gigadb-website --env staging
# open egress port 9135 
/gigascience/gigadb-website/ops/infrastructure/envs/staging (deploy-tideways-from-upstream%=) % terraform apply
/gigascience/gigadb-website/ops/infrastructure/envs/staging (deploy-tideways-from-upstream%=) % terraform refresh
/gigascience/gigadb-website/ops/infrastructure/envs/staging (deploy-tideways-from-upstream%=) % ../../../scripts/ansible_init.sh --env staging
/gigascience/gigadb-website/ops/infrastructure/envs/staging (deploy-tideways-from-upstream%=) % TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories -v webapp_playbook.yml -v
/gigascience/gigadb-website/ops/infrastructure/envs/staging (deploy-tideways-from-upstream%=) % ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" -v

# go to gitlab dashboard, run these jobs: TidewaysBuildStaging, TidewaysDeployStaging

3. live server
/gigascience/gigadb-website (deploy-tideways-from-upstream%=) % cd ops/infrastructure/envs/live
# copy the updated aws-instance config
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % ../../../scripts/tf_
init.sh --project gigascience/upstream/gigadb-website --env live
# open egress port 9135 
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % terraform apply
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % terraform refresh
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % ../../../scripts/ansible_init.sh --env live
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) % TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories -v webapp_playbook.yml -v
/gigascience/gigadb-website/ops/infrastructure/envs/live (deploy-tideways-from-upstream%=) %  ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" -v

# go to gitlab dashboard, run these jobs: TidewaysBuildLive, TidewaysDeployLive
```

#### Gitlab dashboard
The following new stages in gitlab `upstream` pipeline can be seen:

| staging build | staging deploy | live build | live deploy |
| ------------- | --------------- | -------- | ----------- |
| TidewaysBuildStaging | TidewaysDeployStaging | TidewaysBuildStaging | TidewaysDeployLive | 

#### Tideways dashboard
Go to [here](https://app.tideways.io/login) with credentials found in [here](https://gitlab.com/gigascience/cnhk-infra/-/settings/ci_cd)

#### AWS console EC2 dashboard
To confirm that the port `9135` is enabled with destination as the VPC cidr block `10.99.0.0/18`

image

## How have functionalities been implemented?

By following the official installation steps at [here](https://support.tideways.com/documentation/setup/installation/docker-with-compose.html), briefly:

1. Install the tideways extension in the Production-Dockerfile
2. Create Tideways-Dockerfile for tideways daemon
4. Create tideways-daemon service in docker compose file with `web-tier` network as same as the application service, so it can collect data from application and send it to tideways dashboard.

In order to make the data send out from the ec2 `webapp` server through the tideways daemon, a specific egress port needs to be opened for the data transfer.

## Any issues with implementation?

Have to found the way to push the code from the upstream to trigger the pipeline.

## Any changes to automated tests?

None.

## Any changes to documentation?

Store `TIDEWAYS_APIKEY` to the [gigascience/upstream](https://gitlab.com/groups/gigascience/upstream/-/settings/ci_cd) variable list.

And stored the variables `tideways_username` and `tideways_password` to the [cnhk-infra](https://gitlab.com/gigascience/cnhk-infra/-/settings/ci_cd) variable list.

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

1. Since the tideways monitoring is not a must functionality for deploying staging or live, especially when for development. Therefore, the gitlab CI/CD pipeline has been updated, the build and deploy of tideways for staging or live are manual.
2. Make tideways deployment depends on the `build_[staging|live]` and `[sd|ld]_live`, tideways service can be builded and deploy only if its dependant jobs succeed. 
4. Make tideways only available for upstream staging and live by adding this condition block:
```
rules:
    - if: '$CI_PROJECT_PATH == "gigascience/upstream/gigadb-website"'
```

## CI/CD results
- [x] Fork - All green
- [ ] Upstream - All green

### CODE REVIEW

**Comment by rija** [comment]
Hi @kencho51 
could you rebase this branch with the latest changes from develop, otherwise I won't be able to update beta.gigadb.org while keeping APM active.

**Review by rija — CHANGES_REQUESTED** [review]
Hi @kencho51,

**praise**: the integration with the deployment pipeline works on Upstream live and has been doing so for a while, well done!

**issue (ci)**: Tideways can not be easily switched off in control planes (Gitlab, docker-compose) if the need arises
**suggestion**:  In `ops/packaging/Production-Dockerfile`,
We need to be able to switch off/on functionality easily using environment variables from docker-compose and Gitlab, so the code that install `tideways-php` need to be wrapped in an ``RUN if...;fi`` clause on the value of  INSTALL_TIDEWAYSPHP similarly to all the other snippets in that file

**issue (ci)**: Interspacing Tideways and GigaDB in Gitlab configuration make it hard to reason and maintain
**suggestion**: Gitlab configuration for all Tideways jobs needs to be in a separate Gitlab configuration file `ops/pipelines/gitlab-tideways-jobs.yml` to make it easier to read and maintain

**issue (security)**: Tideways daemon may be running with too many privileges
**suggestion**: remove `NET_ADMIN` and `SYS_ADMIN` capabilities from the `tideways-daemon` service like for the other services in `ops/deployment/docker-compose.production-envs.yml`

**issue (ci)**: we want to maintain our docker as immutable as possible between deployments but images built with `ops/packaging/Tideways-Dockerfile` might change without us knowing
**suggestion**: Replace `debian:stable-slim` with `debian:stable-20230502-slim`

**issue (security)**: looking at the `egress` setting in `ops/infrastructure/modules/aws-instance/aws-instance.tf`, I think using  `0.0.0.0/0` as origin may be too permissive.
**suggestion**: I believe it is only the application container running the Tideways PHP extension that connects to the Tideways daemon, so the source can therefore be limited to the CIDR block of the VPC

**Comment by kencho51** [comment]
Hi @rija,

This PR has refactored the following items:
- [x] installed tideways-php need to be wrapped in an `RUN if...;fi` clause on the value of `INSTALL_TIDEWAYSPHP`
- [x] aggregated tideways jobs into `ops/pipelines/gitlab-tideways-jobs.yml`
- [x] dropped NET_ADMIN and SYS_ADMIN capabilities from the tideways-daemon service
- [x] replaced debian:stable-slim with debian:stable-20230502-slim
- [x] opened port `9135` from the VPC cidr block only

Now is ready for review again.

**Review by pli888 — APPROVED** [review]
**praise:** The Tideways functionality seems to be working fine after I followed the instructions to manually start the build and deploy pipeline jobs for Tideways on Gitlab. We already have received email notifications from Tideways re: a new Exception and slow SQL detected.

**praise:** The code looks fine to me with @rija's comments having been implemented. I approve this PR.

**note:** Not all stages in the pipeline are green, e.g. GigaReview Test, but I think it's best we merge the Tideways code and look into the pipeline problems as Sprint 20 progresses during next few weeks.

**Review by rija — APPROVED** [review]
Hi @kencho51

**praise**: I can see that all the issues have been resolved

Happy to approve

**note**: Don't worry a bout the `GigaReviewTest` failure, this is fixed in PR #1285 which is in the "reviewing required" section of the sprint 20 backlog

**Pull request merged**
