### PR TITLE
Make bastion playbook and webapp playbook can run plays separately using tags

### PR DESCRIPTION
**Pull request by kencho51**
# Pull request for issue: #1443 

This is a pull request for the following functionalities:

- Make the playbook flexible and more practical by adding `tags` to each play. 
- Make the playbooks get rid of the `[WARNING]: Could not match supplied host pattern, ignoring: name_gigadb_server_l*` .

## How to test?

Describe how the new functionalities can be tested by PR reviewers

##### Spin up staging servers as usual
```
% cd staging
# clear everything in the staging dir, except the .gitignore file.
% ../../../scripts/tf_init.sh --project gigascience/forks/kencho-gigadb-website --env staging
% terraform plan
% terraform apply
% terraform refresh
% terraform output
% ../../../scripts/ansible_init.sh --env staging
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging"
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" --extra-vars="gigadb_env=staging
```

##### Try to execute different plays separately
```
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging" --tags setup-fail2ban
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" --extra-vars="gigadb_env=staging" --tags rclone-tool
```

##### Try to skip plays
```
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging" --skip-tags fix-centos-eol-issues,setup-fail2ban,setup-docker-ce
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest --extra-vars="gigadb_env=staging" --skip-tags load-latest-db,rclone-tool
```

##### Spin up live servers as usual
```
% cd live
# clear everything in the staging dir, except the .gitignore file.
% ../../../scripts/tf_init.sh --project gigascience/forks/kencho-gigadb-website --env live
% terraform plan
% terraform apply
% terraform refresh
% terraform output
% ../../../scripts/ansible_init.sh --env live
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=live"
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" --extra-vars="gigadb_env=live"
```

##### Try to execute different plays separately
```
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=live" --tags setup-fail2ban
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest" --extra-vars="gigadb_env=live" --tags rclone-tool
```

##### Try to skip plays
```
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=live" --skip-tags fix-centos-eol-issues,setup-fail2ban,setup-docker-ce
% env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "backupDate=latest --extra-vars="gigadb_env=live" --skip-tags load-latest-db,rclone-tool
```

## How have functionalities been implemented?

Added [tags](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html) to the bastion playbook and webapp playbook, so each play in the playbooks can be executed separately, it saves time when a user just want to execute  a certain plays from the playbook, this makes the playbook more versatile. 

 The `hosts` in the playbooks has been refactored, so it will only try to connect the {{gigadb_env}} hosts, which will help to fix the `[WARNING]: Could not match supplied host pattern` as the redundant host has been removed.

## Any issues with implementation?

None.

## Any changes to automated tests?

None.

## Any changes to documentation?

Updated ansible usage will be updated in PR #1468.

## Any technical debt repayment?
None.

## Any improvements to CI/CD pipeline?

None.

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @kencho51,

**praise**: glad to see the one less warning when executing playbook. It also removes remove a risky situation where both the staging and live environment were set to be hosts relying on the dynamic inventory to not make mistake
**note**: a better way of testing is to NOT create a new staging environment with Terraform, instead, use one that's been fully provisioned beforehand (with both terraform and ansible) and then use `tf_init.sh` to download the existing state on this branch. Then try to run Ansible playbook again. In my case, I will get an error (because issue with Centos's dnf tools), so if I want to go past that, I should be able to use `--skip-tags` and list all the tags that do not involve dnf. That's the idea behind this ticket.
**issue**:  In `bastion_playbook.yml`, The `files-url-updater` play is doing too much: it's setting up file-url-updater but it also installs Docker, so I cannot skip docker install (which uses dnf tools) play without skipping the files-url-updater play
**suggestion**: Follow the example of `webapp_playbook.yml` by making Docker install its own play in `bastion_playbook.yml`, that can be skipped with the same tag (`setup-docker-ce`)
**praise**: executing `bastion_playbook.yml` with `--tags` to selectively run specific plays (those that don't involve installing anything using dnf) works as expected

**Comment by kencho51** [comment]
Hi @rija,

> **suggestion**: Follow the example of `webapp_playbook.yml` by making Docker install its own play in `bastion_playbook.yml`, that can be skipped with the same tag (`setup-docker-ce`)

The `Setup Docker CE` is an individual play now.

**Review by rija — APPROVED** [review]
Hi @kencho51,

running the following commands now works fine for me:
```
$ env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "gigadb_env=staging" -e "backupDate=latest" --tags="load-latest-db,excel-spreadsheet-uploader,files-url-updater"


$ env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml -e "gigadb_env=staging" -e "backupDate=latest" --skip-tags "fix-centos-eol-issues,setup-fail2ban,restore-db-on-rds,setup-docker-ce,swatch-tool,rclone-tool,node-exporter"

$ env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging" --tags="fix-centos-eol-issues,setup-fail2ban,setup-docker-ce,node-exporter"
```

LGTM now, so happy to approve

**Comment by pli888** [comment]
>note: a better way of testing is to NOT create a new staging environment with Terraform, instead, use one that's been fully provisioned beforehand (with both terraform and ansible) and then use tf_init.sh to download the existing state on this branch. Then try to run Ansible playbook again. In my case, I will get an error (because issue with Centos's dnf tools), so if I want to go past that, I should be able to use --skip-tags and list all the tags that do not involve dnf. That's the idea behind this ticket.

**praise**: I tested this PR using the above suggestion. After deploying my bastion server, I deleted the contents of my `ops/infrastructure/envs/staging` directory and then executed `tf_init.sh` again in there. I experienced a `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED` error message when I tried to SSH to the bastion server but this was fixed by deleting the entry in my `.ssh/known_hosts` file for my bastion IP address. Using the command below, I could then re-run the bastion playbook:
```
$ env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook -i ../../inventories bastion_playbook.yml --extra-vars="gigadb_env=staging" --skip-tags="restore-db-on-rds,swatch-tool,fix-centos-eol-issues,setup-fail2ban,setup-docker-ce,rclone-tool,load-latest-db,node-exporter"
```

**Review by pli888 — APPROVED** [review]
**praise**: I was also successful in re-running the webapp playbook using the command below:
```
$ env OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES TF_KEY_NAME=private_ip ansible-playbook -i ../../inventories webapp_playbook.yml --extra-vars="gigadb_env=staging" --tags="fix-centos-eol-issues,setup-fail2ban,setup-docker-ce,node-exporter"
```
**praise**: Code looks good to me.
~~**suggestion**: I think it would be good if this functionality was described in `BETA_DEPLOY.md` SOP file.~~
**thought**: Actually, ignore my idea to update SOP documentation as it doesn't make sense.
**chore**: Rebase with latest `develop` code as there seems to be a conflict with `CHANGELOG.md` then happy to approve this PR.

**Pull request merged**
