### PR TITLE
Test data for submission wizard development

### PR DESCRIPTION
**Pull request by jessesiu**
# Pull request for issue: #292 

This is a pull request for the following functionalities:

The `production_like.pgdmp` database dump file contains sensitive GigaDB users' info in the `gigadb_user` table. This commit changes the problematic users' names and email addresses so that email addresses are in the format: `test+gigadb#@gigasciencejournal.com`, where `#` denotes a number based on its database table ID. Their first names and last names are replaced with `test` and `gigadb#`, respectively.

The `GIGADB_admin_tester_email`, `local-gigadb-admin@rijam.ml1.net` and all users with email addresses ending with `gigasciencejournal.com` have been kept for testing purposes. The example user with `gigadb_user` table `id` = `2` has been set with an email address `exampleuser@madeup.com`.  You can use `exampleuser@madeup.com` to log into its user account in the GigaDB application with `gigadb` as the password.

To restore the `production_like.pgdmp` backup in a local deployment of GigaDB, the following steps are required: 
```
# Drop into bash in the test container
$ docker-compose run --rm test bash
# Access the postgres database using `vagrant` as the password
bash-4.4# psql -h database -p 5432 -U gigadb postgres
Password for user gigadb: 
psql (9.4.21)
Type "help" for help.

postgres=# select pg_terminate_backend(pg_stat_activity.pid) from pg_stat_activity where datname='gigadb';
 pg_terminate_backend 
----------------------
 t
 t
 t
 t
 t
(5 rows)

postgres=# drop database gigadb;
DROP DATABASE
postgres=# create database gigadb owner gigadb;
CREATE DATABASE
postgres-# \q
# Restore the `production_like.pgdmp` database
root@9aece9101f03:/var/www# pg_restore -h database -p 5432 -U gigadb -d gigadb -v ./sql/production_like.pgdmp 
```

## Changes to the tests

The dataset-view.feature:
```
PHPUnit_Framework_Assert::assertEquals("mailto:liuxin@genomics.org.cn", $contactButton->getAttribute('href') );
```

Since the email address changed, it has been updated to `test+gigadb112@gigasciencejournal.com`.

### CODE REVIEW

**Comment by pli888** [comment]
@jessesiu Even if the users' data are removed from the `production_like.pgdmp` file, these data from the file will still be present in the repo's history. We might have to do [this](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) to remove versions of `production_like.pgdmp` that contain sensitive data completely from the repo.

Based on this [docker-compose.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/deployment/docker-compose.yml), [bootstrap.sql](https://github.com/gigascience/gigadb-website/blob/develop/ops/configuration/postgresql-conf/bootstrap.sql) is used to create the data in the PostgreSQL database for a local install of GigaDB. What tables needs to be changed so that it can be used for developing the [submission wizard](#241 )? This is so that the developer won't need to run `docker-compose run --rm test` which can take a while.

**Comment by jessesiu** [comment]
@pli888 The tables in the bootstrap.sql are same as the production_like.pgdmp. so should be enough for them to start  up

**Comment by jessesiu** [comment]
@pli888 @only1chunts  the new dump file changed the fake email address to "test+gigadb"+ID+"@gigasciencejournal.com"

**Comment by pli888** [comment]
@jessesiu Can you do a `Find in Path...` on your IDE to check if there are files containing the `liuxin@genomics.org.cn` string please? You should see a hit in the `DatasetViewContext.php.txt` file. Can you check if this file should be updated?

**Comment by pli888** [comment]
@jessesiu Do you think it might be useful to have the `first_name` and `last_name` to be `test` and `gigadb#` in the `gigadb_user` table (where # is the `id`)?

**Comment by jessesiu** [comment]
@pli888 The DatasetViewContext.php.txt is to generate some documents, I already changed the email address in this file.
It's OK to keep the current email format, as we already have the test account in the secrets file also in the sql folder it has the gigadb_testdata dump file which contains first_name and last_name.

**Comment by pli888** [comment]
@rija @only1chunts I've just deployed this on a staging server. The entry for `exampleuser@madeup.com` in the `gigadb_user` table looks like this:

| id  | email | password | first_name | last_name | affiliation | role | is_activated | newsletter | previous_newsletter_state |
| -- | ----- | ---------- | -----------| ---------- | --------- | ---- | ------------ | ---------- | -------------------------------------- |
| 2  | `exampleuser@madeup.com` | | example | user | BGI | | false | true | true |

If WhiteLabel will use `exampleuser` for testing, does it need a password to log into the test GigaDB web site and does it need to be activated?

**Comment by pli888** [comment]
> Do you think it might be useful to have the first_name and last_name to be test and gigadb# in the gigadb_user table (where # is the id)?
>It's OK to keep the current email format, as we already have the test account in the secrets file also in the sql folder it has the gigadb_testdata dump file which contains first_name and last_name.

@jessesiu @only1chunts The reason I suggested having the `first_name` and `last_name` to be `test` and `gigadb#` in the `gigadb_user` table (where # is the id) is so that we can easily relate a user's first_name and last_name with their email address in the test database. This would conform with the other more real `gigasciencejournal.com` user entries in the `gigadb_user` table.

**Pull request merged**
