### PR TITLE
Fix/bugs

### PR DESCRIPTION
**Pull request by jessesiu**
fix some bugs in website

### CODE REVIEW

**Comment by pli888** [comment]
This [commit](https://github.com/gigascience/gigadb-website/pull/35/commits/55c9471a32c9c518dd6b773b8fbf2f0fd2f37c30) seems to have deleted the chef/site-cookbooks/gigadb/attributes/default.rb.sample but this file should be present. Can you check this please?

**Comment by pli888** [comment]
Can you also check if the commits are fixes for any GitHub issues. If so, the issue number should be reported in the commit message so that we can relate it to the issue.

**Comment by jessesiu** [comment]
I add the issue number in the commit message, and restore the default.rb.sample file

**Comment by pli888** [comment]
@only1chunts can you check that this [branch](https://github.com/jessesiu/gigadb-website/tree/fix/bugs) now fixes the associated issues please?

**Pull request merged**
