### PR TITLE
Add Ready and Done checklist to Product Backlog Item github issue template

### PR DESCRIPTION
**Pull request by rija**
Improve the Product Backlog Item template with a ready and done checklist.
Also tweak the user story and acceptance criteria and added an additional info section.

### CODE REVIEW

**Comment by pli888** [comment]
@rija The template file looks fine to me. I don't understand the reason for the `.gitlab-ci.yml` commit though?

**Comment by kencho51** [comment]
@rija The template file looks good to me too. But, I would also like to know why you want to include `Static Application Security Testing` here?

**Comment by rija** [comment]
@pli888 @kencho51 

Thanks for spotting that. A 3 years old mistake that comes to bite me now. 
I've removed the .gitlab.yml that should not be there.

**Review by pli888 — APPROVED** [review]
All looks fine to me.

**Pull request merged**
