### PR TITLE
Fix dataset spreadsheet upload

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #862

This is a pull request for the following functionalities:

* Fix spreadsheet upload by user on `/datasetSubmission/upload` page

## Changes to the controller classes

The actionUpload() function in DatasetSubmissionController.php now uses MailService component for sending emails containing dataset spreadsheet to curators.

## Changes to the view template files

The datasetSubmission/upload.php class has been updated so that the form for spreadsheet upload now includes the terms and conditions checkbox. 

## Changes to the tests

`DatasetUpload.feature` contains new acceptance tests to check the HTML structure of the `/datasetSubmission/upload` page and that a user is able to upload a dataset spreadsheet file.

A tests/_support/UserSteps.php file has been created to provide the implementation for checking that a user is able to sign into GigaDB website.

## Changes to the Component classes

protected/components/MailService.php has a new sendHTMLEmailWithAttachment() function that allows an email to be sent with a file attachment. This is used by the actionUpload() function in DatasetSubmissionController class to send the uploaded spreadsheet to curators as an email attachment.

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @pli888

I have tested the functionalities.

* When using Safari or Chrome, it works and the file is uploaded and email is sent (or written in an .eml file in my setup).
On Firefox, I cannot open the dialog box to browse for a file to upload.
There is no javascript error, the "Browse..." button  just doesn't do anything.

* On a separate note, the change made to ``protected/controllers/SiteController.php``, I don't think it's necessary as that will come with PR #884

* now to a minor point, the acceptance tests are passing locally after I've set ``useFileTransport`` to ``true`` in ``protected/config/yii2/web.php``. It feels to me that should be default on dev and CI, while it being set to ``false`` should be the default on staging and live deployment.

**Comment by pli888** [comment]
>On a separate note, the change made to protected/controllers/SiteController.php, I don't think it's necessary as that will come with PR #884

This change disappears now that I have rebased this PR with the latest `develop` branch code.

>On Firefox, I cannot open the dialog box to browse for a file to upload.
There is no javascript error, the "Browse..." button just doesn't do anything.

On my local GigaDB installation, Firefox (version 95.0.2) is able to browse for a file to upload that leads to a successful email notification.

On testing for this problem on my staging server, I found that it cannot send email notifications and instead returns this error message: `The view file does not exist: /var/www/mail/template.php`.

**Comment by pli888** [comment]
>now to a minor point, the acceptance tests are passing locally after I've set useFileTransport to true in protected/config/yii2/web.php. It feels to me that should be default on dev and CI, while it being set to false should be the default on staging and live deployment.

There is a now a `web.staging.live.php.dist` file and a `web.dev.CI.php.dist` file in the `ops/configuration/yii-conf` directory. These 2 files are used in the `generate_config.sh` script within an if/then/else conditional block to configure the deployment environments with the suggested `useFileTransport` settings.

**Review by rija — APPROVED** [review]
It's all working now. Happy to approve

**Review by kencho51 — APPROVED** [review]
Hi @pli888 ,

Functional tests and acceptance tests are passing on my dev, and this fix is working when I tried to upload test spreadsheet manually from page `datasetSubmission/upload`. So, I would like to approve this PR.

**Comment by rija** [comment]
@pli888, maybe you can merge it yourself if you wish to ensure that PR makes its way to staging in time?

**Pull request merged**
