### PR TITLE
Configure flySystem with Yii2 and AWS PHP SDK v3

### PR DESCRIPTION
**Pull request by rija**
# Pull request for issue: #964

This is a pull request for the following functionalities:

## (I) Configure Flysystem as an application component to the Yii application( using ``creocoder/yii2-flysystem`` as glue). 

* composer.lock
* ops/configuration/php-conf/composer.json.dist

## (II) Configure two storage adapters:

   * Local storage adapter that's rooted to the directory `images/``
   * S3 storage adapter that's rooted to the ``assets.gigadb-cdn.net`` bucket

## The configuration files changed are:

* ops/configuration/yii-conf/web.dev.CI.php.dist
* ops/configuration/yii-conf/web.staging.live.php.dist
* ops/configuration/yii-conf/test.php.dist
* ops/scripts/generate_config.sh

## (III) There are also a functional test and status endpoint that check the configuration works end-to-end with both adapters
and act as a tutorial for basic usage. 

* tests/functional/FlysystemCest.php
* protected/controllers/Site/FlysystemAction.php
* protected/controllers/SiteController.php
* .gitignore
* images/no_image.png

## (IV) There is an IAM policy document that's used to give the developers group programmatic access to the bucket for the needed actions

* docs/awsdocs/policy-s3.md

## (V) Restrict the flysystem testing endoint (``/site/flysystem-status``) to local users only

The status endpoint is only made for test, and end-users won't be able to access it as it is restricted to local IPs.

This is done with an update to the ``accessRules()`` method of ``protected/controllers/SiteController.php`` 

## (VI) Configure Gitlab pipeline to work with the update cloud deployment of Gitlab runner

The first change is to ``.gitlab-cy.yml``, where we replace ``/builds/$CI_PROJECT_PATH``
with ``$CI_PROJECT_DIR``, this is because by using a host directory as gitlab runner's build cache, the path to the build is no longer ``/builds/<codebase>`` but ``/builds/<partial runner token>/<some number>/<codebase>`` and
the predefined variable ``$CI_PROJECT_DIR`` always contains the correct value.

The second change is to build and test jobs (``gigadb-build-jobs.yml`` and ``gigadb-test-jobs.yml``):

We ensure the cache they set is minimal and consistent (only for dependencies that take a long time to install with Composer and NPM).
We also move the ``legacy_tests`` jobs to run on DO's Gitlab runner as its the slowest and could benefit from better resources. The two other jobs of the ``Test`` stage are left on Gitlab.com shared runners so they can run in parallel.

## (VII) Fix some issues with Composer configuration 

There was some inconsistencies between the lock file and the composer file, made worse by migrating to PHP 7.2 and then 7.3. There were now incompatibilies between the various dependencies. Had to remove the ``friendsofphp/php-cs-fixer`` library for now. Also I had to relax the version constraint on some of the dev dependencies (^ for ~) that use semantic versioning to silence convention violation warnings and help with sorting out the dependency mess.

Also is now mandatory for security purpose to have an ``allow-plugins`` clause in the composer files.

## (VIII) Fix an issue when installing node module with NPM

An error message was shown and extra communictations  with the registry was performed because the package log was for an old version of NPM. 

So updated ``gigadb/app/client/web/package-lock.json`` to use the new version, and also ensure the package lock as up-to-date version of packages from the package file.

### CODE REVIEW

**Comment by pli888** [comment]
@rija Unfortunately, the `tryFlysystemEndToEnd` test in `FlysystemCest` keeps failing even when I clear the `runner cache` on my CI pipeline. The same problem also occurs when I try to execute the test on my `local` environment. Do you see the same problem @kencho51?
```
✔ DownloadTemplateFilesCest: Try to download example file2 (0.10s)
[8794](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8794)✔ EmailCest: Try send activation email (1.11s)
[8795](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8795)✔ EmailCest: Try send notification email (0.36s)
[8796](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8796)✖ FlysystemCest: Try flysystem end to end (1.94s)
[8797](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8797)------------------------------------------------------------
[8798](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8798)DEPRECATION: Calling the "Codeception\Lib\Connector\Guzzle::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /var/www/vendor/symfony/browser-kit/Client.php:217
[8799](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8799)Time: 4.85 seconds, Memory: 16.00MB
[8800](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8800)There was 1 failure:
[8801](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8801)---------
[8802](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8802)1) FlysystemCest: Try flysystem end to end
[8803](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8803) Test  tests/functional/FlysystemCest.php:tryFlysystemEndToEnd
[8804](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8804) Step  Assert equals "image/png","text/html"
[8805](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8805) Fail  Failed asserting that two strings are equal.
[8806](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8806)- Expected | + Actual
[8807](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8807)@@ @@
[8808](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8808)-'image/png'
[8809](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8809)+'text/html'
[8810](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8810)Scenario Steps:
[8811](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8811) 1. $I->assertEquals("image/png","text/html") at tests/functional/FlysystemCest.php:19
[8812](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8812)FAILURES!
[8813](https://gitlab.com/gigascience/forks/pli888-gigadb-website/-/jobs/2170740645#L8813)Tests: 8, Assertions: 18, Failures: 1.
```

**Comment by rija** [comment]
Thanks for the feedback @pli888,

What do you get on you navigate to /site/flysystem-status/ on your local environment?

**Comment by rija** [comment]
As there is a new composer library, on your local environment, you may need to install it since it's likely absent from your ``vendor`` library

**Comment by pli888** [comment]
>What do you get when you navigate to /site/flysystem-status/ on your local environment?

I get this error message:
```
Aws\S3\Exception\S3Exception

Error executing "PutObject" on "https://s3.ap-east-1.amazonaws.com/assets.gigadb-cdn.net/live/images/datasets/fce51719-34e1-5134-9eb2-22ac84b34217.png"; AWS HTTP error: Client error: `PUT https://s3.ap-east-1.amazonaws.com/assets.gigadb-cdn.net/live/images/datasets/fce51719-34e1-5134-9eb2-22ac84b34217.png` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided (truncated...)
InvalidAccessKeyId (client): The AWS Access Key Id you provided does not exist in our records. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>0</AWSAccessKeyId><RequestId>QFP8JMQAJK18RBKS</RequestId><HostId>ncox1tYuXH4ZZp9EbE2HFFwr0qDlXH3YmLCf...</HostId></Error>
```

**Comment by kencho51** [comment]
Hi @rija and @pli888,

I got `FlysystemCest` not passing in my gitlab pipeline as well.

```
✖ FlysystemCest: Try flysystem end to end (1.66s)
------------------------------------------------------------
DEPRECATION: Calling the "Codeception\Lib\Connector\Guzzle::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /var/www/vendor/symfony/browser-kit/Client.php:217
Time: 4.6 seconds, Memory: 16.00MB
There was 1 failure:
---------
1) FlysystemCest: Try flysystem end to end
 Test  tests/functional/FlysystemCest.php:tryFlysystemEndToEnd
 Step  Assert equals "image/png","text/html"
 Fail  Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'image/png'
+'text/html'
Scenario Steps:
 1. $I->assertEquals("image/png","text/html") at tests/functional/FlysystemCest.php:19
FAILURES!
Tests: 8, Assertions: 18, Failures: 1.
Cleaning up project directory and file based variables
00:02
ERROR: Job failed: exit code 1
```

**Comment by pli888** [comment]
>What do you get when you navigate to /site/flysystem-status/ on your local environment?

@rija After providing values to the Gitlab `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables in my Gitlab project, I can see the generic no image png file displayed at `/site/flysystem-status/`. The `tryFlysystemEndToEnd` test in `FlysystemCest` can now pass on my local environment too.

**Review by pli888 — APPROVED** [review]
With the successful local and CI pipeline execution of the `tryFlysystemEndToEnd` test in FlysystemCest, all of the configuration code in this PR looks good to me. I approve this PR.

**Comment by rija** [comment]
Thanks @pli888,

I've just pushed a couple of commits that add the AWS credentials variables to the documentation, 
and more importantly they add a functional test that check that the variables are populated in the Yii2 config file.

@kencho51,

Feel free to test again after pulling the aforementioned changes: until you setup CICD variables for AWS credentials, you will see two failing functional tests failing.

The first one because the AWS credentials are not set up where they should be
The second one because the expected file is not image, in which case the failing test will show you the content of the file, so you can quickly access the error message displayed by the endpoint

**Review by kencho51 — APPROVED** [review]
Hi @rija,

After adding the aws credentials to gitlab variables, `FlysystemCest` tests are passing both locally and in gitlab pipeline.
The code looks good to me, so I would like approve this PR.

**Pull request merged**
