### PR TITLE
Feat: Code refactoring to separate upload status transition and notifications (e.g: email) in preparation for upcoming work on dataset status overhaul

### PR DESCRIPTION
**Pull request by alli83**
# Pull request for issue: #701

This is a pull request for the following functionalities:

separate the transition and notification concerning upload_status update. 
If the transition is not allowed, the model shouldn't be saved.

It's temporary, while waiting for a PR creating a dedicated service 

## How to test?

- Go to a dataset form
- try  "UserStartedIncomplete" to "Submitted" or to "DataPending"
- Scroll down to Save
- changes should not been saved.

### CODE REVIEW

**Comment by alli83** [comment]
next step (PR) will be to create a dedicated service for the "workflow" and email handling, followed by another PR to set up a more effective workflow.

**Review by rija — COMMENTED** [review]
Hi @alli83,

**praise**: code change is an improvement in maintainability and expandability
**issue**: the function `checkTransition()`'s name is not ideal as it is not just checking, it it is also assigning an upload status to the dataset model
**suggestion**: rename to `checkAndSetTransition()`
**chore**: add a CHANGELOG.md entry

**Review by rija — COMMENTED** [review]
Hi @alli83,

**praise**: thanks for carrying out the requested change
**chore**: you put the new entry to CHANGELOG.md in the wrong section, it should be in the Unreleased section (you put in the release v4.3.7)

**Review by rija — APPROVED** [review]
Hi @alli83,

LGTM!
happy to approve

**Comment by kencho51** [comment]
Hi @alli83,

**question:** I have tried to follow your `How to test` in my local dev environment, given the status is `UserStartedIncomplete`, when I changed to `dataAvailableForReview` and updated the values in Source, Tag and Photographer fields, the changes were saved as you can see below:
image
So, I want to know whether the changes should be saved or not?
**chore:** Rebase this PR with the `gigascience/develop` branch.

**Comment by alli83** [comment]
@kencho51 there was an error in the description. I updated it

**Review by kencho51 — APPROVED** [review]
Hi @alli83,

**praise:** I could follow the `How to test` step to complete the test.
**praise:** I can tell from the `checkAndSetTransition()` that it makes sure status changes from only `DataAvailableForReview` to `Submitted`, and `Submitted` to `DataPending` are allowed.
**question(non-blocking):** This PR was meant for https://github.com/gigascience/gigadb-website/issues/1848, so how this PR relate to? Anyway, it seems that this PR is just temporary, so non blocking. But your explanation will be appreciated.

**Comment by alli83** [comment]
I think it's related to a rewrite but maybe there was another intermediate issue. I'll look into it.

**Review by pli888 — COMMENTED** [review]
**thought**: I don't think this PR #1999 relates to ticket #1848 `Datasets Admin page - image metafields - changes not saved` which already has PR #1916 as its fix. It feels like it might be related to ticket #701 `Implement the transitions between Dataset Upload Statuses`.
**thought**: If this PR affects functionality on the dataset admin  page then having acceptance tests to ensure that it is not possible to transition from a `UserStartedIncomplete` dataset status to either `Submitted` or `DataPending` would be useful?

**Pull request merged**
