### PR TITLE
Create readme tool

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1178 Create Console Controller class for Readme tool

This is a pull request for the following functionalities:

* Generate and save Readme information into a file

## How to test?

See the tool's [README file](https://github.com/pli888/gigadb-website/blob/readme-generator/gigadb/app/tools/readme-generator/README.md).

## How have functionalities been implemented?

A Yii2 basic project directory was created for the readme tool.

The functionality resides in the `ReadmeController` class. There is a private function called `getReadme($doi)` which takes a DOI and uses it to retrieve dataset information from the `database` container. The strings making up the readme are stored in an Array when the information for the readme is being collated.

`getReadme($doi)` is called by the `actionCreate()` function which is what is executed from the command-line when using this tool:
```
$ docker-compose run --rm tool /app/yii readme/create --doi 100142
```

The tool's `docker-compose.yml` contains a network that is a proxy for the `db-tier` network in `ops/docker-compose.yml`. This enables the readme tool to be deployed in the `ops/docker-compose.yml` `db-tier` network, thereby to connect to the `database` container.

## Any issues with implementation?

* A step has not been added into `postUpload.sh` yet. This will be done as part of [Create pipeline for console command #1179](https://github.com/gigascience/gigadb-website/issues/1179).
* The `file-worker` model classes will be moved to a more sensible location in the repo at a later date.

## Any changes to automated tests?

There is a unit test which checks the `testGetAuthors()` function in the Dataset model class for its ability to query authors relating to a given dataset.

There is also a functional test in `ReadmeCest` class which checks the functionality of the `ReadmeController` class. This functional test uses the `gigadb_testdata` database in the dev Docker `database` container which is automatically created when `up.sh` is executed.

## Any changes to documentation?

The tool has its own [README file](https://github.com/pli888/gigadb-website/blob/readme-generator/gigadb/app/tools/readme-generator/README.md).

## Any technical debt repayment?

There are 2 new model classes in `file-worker`: `Author` and `DatasetAuthor` which are required for querying the authors of a dataset. In addition, a `DataType` model was created.

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @pli888:

**praise:** functionality works for me

**praise:** all tests are passing both main app and in the readme generator directory

**praise:** the way you connect to the main database container service is elegant

**issue:** It doesn't feel right for the  ``getReadme()``  to be in the controller as it is business logic.
Furthermore, as such, It is highly plausible that in the future we may be asked to dynamically generate the readme elsewhere, 
maybe a button on the submission wizard  or the file upload wizard (or an automated email). 
We won't be able to use the code you wrote because it is inside a console controller. If it was in a business logic layer class, both the console controller and a future web controller or worker class could share this code.

**suggestion:** Maybe the ``getReadme()`` can be placed in ``models/Dataset.php`` or better still, in `` components/DatasetServices.php`` as it sounds like a service that needs to be available from various endpoints eventually

**Comment by pli888** [comment]
>suggestion: Maybe the getReadme() can be placed in models/Dataset.php or better still, in  components/DatasetServices.php as it sounds like a service that needs to be available from various endpoints eventually

A `components/DatasetService` class has now been implemented in `file-worker` and its `getReadme()` function is used to generate a read me file. Unit and functional tests have been used to check the `components/DatasetService` class.

**Review by rija — APPROVED** [review]
Hi @pli888 

**praise:** Saw that domain logic moved in domain logic layer (components for us)

**chore:** this PR might need one last rebase as I've merged another PR to ``develop``

**polish:** If you are curious, feel free to have a look at deviations from [PSR-12](https://www.php-fig.org/psr/psr-12/):

```
phpcs --standard=PSR12 tools/readme-generator/controllers worker/file-worker/components                                                                                  

FILE: /Users/owner/code/pli888-gigadb-website/gigadb/app/tools/readme-generator/controllers/ReadmeController.php
----------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AND 1 WARNING AFFECTING 4 LINES
----------------------------------------------------------------------------------------------------------------
[...]
----------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 5 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------


FILE: /Users/owner/code/pli888-gigadb-website/gigadb/app/worker/file-worker/components/DatasetService.php
------------------------------------------------------------------------------------------------------------
FOUND 31 ERRORS AND 1 WARNING AFFECTING 15 LINES
------------------------------------------------------------------------------------------------------------
[...]
------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 31 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------------

```


In any case, based on the above, I'm happy to approve this

**Comment by pli888** [comment]
To confirm, I've made a note to use PHP tools for my code to adhere to PHP coding standards in the future. Let's get this code merged in the meantime.

**Review by kencho51 — CHANGES_REQUESTED** [review]
Hi @pli888,

**praise:**  Generate readme functionality is working on my branch.

**praise:**  `Dataset $DOI not found` message will be thrown out for better error handling if not found DOI is supplied to the cmd.

**issue:** In `.gitignore`, `_generated` dir is ignored, which does not exist.

**suggestion:** In `.gitignore`, add in `tests/_support/_generated`.

**issue(non-blocking):** After running the function test, the `readme_100005.txt` is saved to `runtime/curators/`. Although there is `.gitignore` to ignore everything in runtime dir, the state of the code should be remained unchanged after the test?

**suggestion(non-blocking):** Implement `_after()` method in `tests/functional/ReadmeCest.php` to remove the readme file after the test.
```
public function _after()
{
    if (file_exists("/home/curators/readme_100005.txt")) {
        unlink("/home/curators/readme_100005.txt");
    }
}
```

**Comment by pli888** [comment]
@kencho51 The .gitignore file has been updated now. `ReadmeCest.php` has also been updated with teardown code in a new `_after() function.

**Review by kencho51 — APPROVED** [review]
Hi @pli888,

**praise:** `readme_100005.txt` is removed after the test.
**praise:** `FunctionalTesterActions.php` and `UnitTestActions.php` are not tracked now.

All changes look good to me, I'm happy to approve this PR.

**Pull request merged**
