### PR TITLE
Codebase onboarding fixes

### PR DESCRIPTION
**Pull request by rija**
# Pull request for issue: #1334

This is a pull request for the following functionalities:

* secrets sample that work by default
* env sample that work by default
* minor updates to yii and symfony dependencies for file-worker project and the corresponding lock file
* prevent warnings about variable not being set when running compose
* allow postgresql to stop cleanly without errors on shutdown
* remove usage of chrome-arm as not reliable and not necessary

### Guest mode

Make a new checkout of gigadb-website from this branch and cd into it
```
$ cd gigadb-website
```

Create .env and .secrets from samples

```
cp ops/configuration/variables/env-sample .env
cp ops/configuration/variables/secrets-sample .secrets
```

Start the application
```
$ ./up.sh
```
The application should start normally

Run all the tests suites:
```
$ ./tests/unit_functional_runner
$ ./tests/unit_runner
$ ./tests/functional_runner
$ ./tests/acceptance_runner
```

They should all pass

Tear down the application:
```
$ docker-compose down -v --remove-orphans
```

All services should be stopped and torn down gracefully

### Team mode

delete the `.secrets` file, and make sure `.env` has `GITLAB_PRIVATE_TOKEN` and `REPO_NAME` filled in with valid values.

run config generation again:
```
$ docker-compose run --rm config
```

Then run all the tests suites again.
They should all pass, and the previously skipped ones are now running (except fragile legacy functional tests that will always stay excluded).

## How have functionalities been implemented?

Remove all secrets from .secrets and .env and see which tests fails.
Then added if-test blocks in the suite runners (for acceptance tests) or in the before block (for functional test)
That check whether either GITLAB_PRIVATE_TOKEN or some over variables needed by the test are set
For the Codeception acceptance tests, the if-test leverages new tags to label the feature that can't run without secrets from those which can run with secrets.
For the Behat acceptance tests, added a new profile in `behat.yml` for running the features not labelled as needing secrets.
Also excluded some legacy functional tests by appending them in the exclude list of `phpunit.xml`

Regarding the issue with Postgresql showing errors on shutdown (it was always there - you can see that by looking at the docker database logs, but recently it caused a non-zero exit for me), I implemented the solution described on this ticket:

https://github.com/docker-library/postgres/issues/544#issuecomment-455738848

Fix the instructions for generating `PORTAINER_BCRYPT` in the `env-sample` file so it properly escape the `$` sign so not to show warnings every time we run docker-compose.

Remove the `chrome-arm` container service as it wasn't working.

## Any issues with implementation?

N/a

## Any changes to automated tests?

See above

## Any changes to documentation?

Update `README.md` to:
* make optional the setting of GitLab
* instruct how to enable default .env and .secrets

## Any technical debt repayment?

N/a

## Any improvements to CI/CD pipeline?

N/a

### CODE REVIEW

**Comment by rija** [comment]
Hi @pli888,
I've now updated this branch with changes to the `README.md` file with addition of the simpler instructions and the moving of GitLab set up further down in an optional section.
I've also rebased the branch to incorporate the latest merge I've done to `develop`

**Review by pli888 — COMMENTED** [review]
I was unable to create a Ubuntu VM for testing on my M2 MacBook Air. But, after installing Ubuntu 22.04 desktop on an external drive and running this on an Intel-based iMac, I managed to create an Linux environment to test this PR.

Docker Desktop for Linux version 4.22 was installed on my Ubuntu OS using the instructions described in  https://docs.docker.com/desktop/install/ubuntu/. This does not provide `docker-compose` which GigaDB deployment relies on from the command-line console. To fix this, I created a script at `/bin/docker-compose` with `docker compose "@0"` as its content - see [here](https://stackoverflow/questions/72099653/how-to-alias-docker-compose-to-docker-compose). I was then able to execute `up.sh` and see the GigaDB website at `http://gigadb.gigasciencejournal.com:9170` in a browser.

Most of the steps worked when testing this PR. However, there were some errors when executing `./tests/functional_runner`. These tests had error messages in guest and team mode. The errors can be seen in this [text file](https://drive.google.com/file/d/181ZsckMSE5qGl1f1SecApwHbYXkmmQmw/view?usp=sharing).

When testing this PR on my Intel-based iMac, I was able to successfully run all tests. The steps to confirm functionality in team mode were successfully executed too.

**Comment by rija** [comment]
Hi @pli888,

I've now added a couple of commits to exclude the failing functional tests and annotate the README file with the docker-compose install anomaly on Linux.

**Review by pli888 — APPROVED** [review]
**praise**: All tests appear to be passing now so I approve this PR:

```
$ ./tests/unit_functional_runner 
Codeception PHP Testing Framework v3.1.3
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed: 

Unit Tests (241) ---
...
Time: 1.14 minutes, Memory: 30.00MB

OK (241 tests, 736 assertions)
Codeception PHP Testing Framework v3.1.3
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed: 

Functional Tests (23) ---
...
Time: 1.26 minutes, Memory: 16.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 23, Assertions: 33, Skipped: 9.
```

```
$ ./tests/unit_runner 

Yii Migration Tool v1.0 (based on Yii v1.1.28)

No new migration found. Your system is up-to-date.
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.33 with Xdebug 2.9.8
Configuration: /var/www/protected/tests/phpunit.xml
...
62 / 62 (100%)

Time: 18.67 seconds, Memory: 20.00MB
```

```
$ ./tests/functional_runner
...
.......                                     29 / 29 (100%)

Time: 8.72 seconds, Memory: 18.00MB

OK (29 tests, 86 assertions)
Restoring current database...
```

```
$ ./tests/acceptance_runner 
Codeception PHP Testing Framework v5.0.4 https://helpukrainewin.org
[Groups] ok-can-offline 

Acceptance Tests (99) ---
...
Time: 11:11.675, Memory: 16.00 MB

OK (99 tests, 376 assertions)

  @ok
  Scenario: a user already associated to an author cannot claim another author # features/user-claims-dataset-57.feature:93
    Given Gigadb web site is loaded with "gigadb_testdata.pgdmp" data          # GigadbWebsiteContext::gigadbWebSiteIsLoadedWithData()
      │ Initializing the database with gigadb_testdata.pgdmp... Terminating DB Backend...
      │ Recreating database gigadb...
      │ Restarting php container for deployment project...
      │ 
    And user "joy_fox" is loaded                                               # GigadbWebsiteContext::userIsLoaded()
      │ Loaded joy_fox.sql on gigadb
    Given author "3794" is associated with a user                              # ClaimDatasetContext::authorIsAssociatedWithAUser()
    When I sign in as a user                                                   # GigadbWebsiteContext::iSignInAsAUser()
    And I go to "/dataset/100002"                                              # Behat\MinkExtension\Context\MinkContext::visit()
    Then I should not see "Your dataset?"                                      # Behat\MinkExtension\Context\MinkContext::assertPageNotContainsText()
  │
  │  Truncated user_command on gigadb
  │
  └─ @AfterScenario @user-claims-dataset # ClaimDatasetContext::resetClaimTable()

│
│  Loading environment variables... 
│  Restoring current database... 
│  Terminating DB Backend...
│  Recreating database gigadb...
│  Restarting php container for deployment project...
│  
│
└─ @AfterSuite # GigadbWebsiteContext::restoreCurrentDB()

28 scenarios (28 passed)
227 steps (227 passed)
4m8.57s (16.20Mb)
```

**Review by kencho51 — APPROVED** [review]
Hi @rija,

I just wanted to see if the workflow can run smoothly, and the test env is mac with Apple M2 chip.
**praise:** By updating the `GITLAB_PRIVATE_TOKEN`, `REPO_NAME` variables in `.env` file and delete the `.secrets` file, and execute `docker-compose run --rm config
`, the environment can be easily switched from `guest` to `dev` mode with complete secrets generated.
**praise:** All tests are passing in both `guest` and `dev` environments.
**praise:** All excluded tests in `guest` can be executed and passed in `dev` environment.
**issue(non-blocking)** Only happen in computer with non-intel chip. When `./up.sh`, would get this error:
```
+ docker stop socat
Error response from daemon: No such container: socat
+ docker run --name socat -d -v /var/run/docker.sock:/var/run/docker.sock -p 127.0.0.1:2375:2375 bobrik/socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
Unable to find image 'bobrik/socat:latest' locally
docker: Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported.
See 'docker run --help'.
```
It is because the image [bobrik/socat:latest](https://registry.hub.docker.com/r/bobrik/socat/tags) does not have the arm version, and its latest update is 8 years ago.
**suggestion(non-blocking)** Only happen in computer with non-intel chip. Replace the `bobrik/socat` image with [alpine/socat](https://hub.docker.com/r/alpine/socat/tags) which has the arm version, the update in `./up.sh` can be:
```
docker run --name socat -d -v /var/run/docker.sock:/var/run/docker.sock -p 127.0.0.1:2375:2375 alpine/socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock || true
```

All changes look good to me, happy to approve this PR.

**Pull request merged**
