### PR TITLE
SOPs for restoring database backups

### PR DESCRIPTION
**Pull request by pli888**
# Pull request for issue: #1019 [S1008] Write SOP for restoring database from backup

The main outputs of this PR are the SOPs in the `docs/sop` directory:

* SOP for restoring an AWS automated backup
* SOP for restoring an AWS snapshot
* SOP for restoring a database dump backup file stored in S3. 

The latter SOP required new scripts to be developed:

1. `upload_database_backup_to_S3.sh`

This shell script is responsible for creating a database dump backup file on the bastion server and uploading it to an S3 bucket called `gigadb-database-backups`. Access to the S3 `gigadb-database-backups` bucket has been provided to AWS IAM users by updating `policy-s3.md`. Rclone is used to perform the uploading process to S3.

The `bastion_playbook.yml` has been updated with steps to enable a database dump files to be created and uploaded to S3. Rclone is installed on the bastion server and is configured to access the S3 API. This requires 2 new Gitlab variables to be created for the `all` environment:

* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY

N.B. The above Gitlab variables have already been created in the Gitlab `Upstream/gigadb-website` project. These 2 variables are then used by `rclone.conf.j2` to create `rclone.conf` at `/home/centos/.conf/rclone` directory in the bastion server that is used to access the AWS S3 API.

The 2 AWS variables in Gitlab are also accessed by `ansible_init.sh` to create `ansible.properties`. The Ansible inventory `hosts` file then uses `ansible.properties` to provide the `beta.gigadb.org` server with the `aws_access_key_id` and `aws_secret_access_key` variables.

2. `restore_database_from_s3_backup.sh`

Database backup files in the S3 bucket can be restored onto RDS using the `restore_database_from_s3_backup.sh` shell script.

The `bastion_playbook.yml` has a step to create a cron job to run the `upload_database_backup_to_S3.sh` script on a daily basis. This step to create the cron job is only executed by running as part of the `BETA_DEPLOY.md` SOP:
```
$ ansible-playbook -i ../../inventories bastion_playbook.yml -e "upload_database_backup_to_S3_cronjob_state=present"
```

### CODE REVIEW

**Review by rija — COMMENTED** [review]
Hi @pli888,

I'm currently reviewing this branch. I'm not done, but I want to write down my findings as I go along.


I've successfully deployed that branch to my staging, including using the instructions for turning on the cronjob to perform backup to S3, and it works.

However the S3 bucket or the backup file name probably needs to be segregated per environment:
Staging and live environment must be the same as that's how on staging we can test and debug feature/bugs with confidence that the behaviour will be the same than on live environment.
So if/when we test backup/restore to/from S3 on staging, we don't want to accidentally overwrite a live backup.
I can see two ways to do it: either have a ``staging`` and ``live`` sub-directory in the bucket or make the environment part of the name of the backup file. And it's not just the environment actually, it's also the gitlab project, so maybe coding it the name is the easiest and safest approach to avoid risk of collision: 
e.g using REPO_NAME: 
```
gigadb_gigadb-website_live_20220101.backup (from Upstream pipelines)
gigadb_gigadb-website_staging_20220101.backup (from Upstream pipelines)
gigadb_rija-gigadb-website_staging_20220101.backup (from my fork's pipelines)
gigadb_rija-gigadb-website_live_20220101.backup (from my fork's pipelines)
```

Additionally, the date in the backup's filename seems to be the day before the backup is performed (e.g: backup I performed today on 09 March is named ``gigadb_20220508.backup``) , is it expected? 
it might cause confusions if we have to restore from s3 in a hurry for a specific date and didn't remember the file date is for the one before the one we think.

**Review by rija — COMMENTED** [review]
While following instructions in ``docs/sop/RESTORE_DATABASE_BACKUP_IN_S3.md``

 I got this error:

```
[centos@ip-10-99-0-182 files-url-updater]$ pwd
/home/centos/files-url-updater
[centos@ip-10-99-0-182 files-url-updater]$ ./restore_database_from_s3_backup.sh
-bash: ./restore_database_from_s3_backup.sh: No such file or directory
```

I could get it work only by calling the script with absolute path: 

```
$ /home/centos/file-url-updater/restore_database_from_s3_backup.sh
```

I noticed that in the project directory, that file was committed without the ``x`` permission bit set like the other script
(a simple ``chmod a+x`` on that file and then committing it should probably fix this)


Beside that, the script did its job correctly.


I also tried passing specific date:
```
/home/centos/files-url-updater/restore_database_from_S3_backup.sh 20220508
```

and it worked, however that possibility wasn't mentioned in the SOP.
I think it's worth adding as there will be types of incidents were we cannot use the "latest" backup
(e.g: a corruption of the data that happen over several days and/or corruption is copied in the latest backup, or the latest backup file is corrupt,...)

**Review by rija — COMMENTED** [review]
Hi @pli888

So I was following the first set of instructions in ``docs/sop/RESTORE_DATABASE_AWS_BACKUP.md``, 

I think deleting an existing RDS instance should be the first step instead of being mentioned as a pre-requisite without further hints.

This is because it's easy to skip it and jump to the numbered steps and more importantly because there is an important dialog box when you delete an instance from the dashboard. It has two check boxes and if the second one (Retain automated backups) is not checked, there won't be any retained backup to work with for the remainder of the steps, so that need to be mentioned in the SOP, as first step.

In step 12 regarding the Additional configuration box, an action missing in the SOP is that we should select the appropriate DB parameter group, especially that the  default selection, ``default.postgres11``, is not the correct one to choose, which in my case would be ``gigadb-db-param-group-rija``

Also it's worth mentioning in the SOP that the deletion of database instance and the restoration a backup into a new instance can each take several minutes.

And for the latter, queries to the web site will show a "504 gateway time out" until the new DB instance is ready.

**Review by rija — COMMENTED** [review]
While following the second set (terminal based) instructions in ``docs/sop/RESTORE_DATABASE_AWS_BACKUP.md``, it  went smoothly.
Beside the same remark re making the pre-requiste the first step, there's nothing to add on those steps.

>TODO: check if we need to delete existing RDS instance for live environment.

If we proceed without deleting the RDS instance beforehand, we will get this message from Terraform when applying:

```
$ terraform apply -var source_dbi_resource_id="db-ANLUVMR6JQNL4U2ROSYRLNQTBE" -var gigadb_db_database=""  -var use_latest_restorable_time="true"

...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.rds.module.db.module.db_instance.aws_db_instance.this[0] will be updated in-place
  ~ resource "aws_db_instance" "this" {
      ~ final_snapshot_identifier             = "snapshot-final-staging-rija-20220510133919-rds-server-staging-rija-216da8b7" -> (known after apply)
        id                                    = "rds-server-staging-rija"
        name                                  = "gigadb"
        tags                                  = {}
        # (50 unchanged attributes hidden)

      ~ restore_to_point_in_time {
          ~ source_dbi_resource_id     = "db-WNXT4BB2VXD4VXY72LBULYE7CU" -> "db-ANLUVMR6JQNL4U2ROSYRLNQTBE"
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

However, if we say yes, nothing will be restored, 
which is probably kind of expected given than restoration to PIT creates a new instance and the instance metadata in the terraform script are those of an already running instance?

**Review by rija — COMMENTED** [review]
After I've manually created a database snapshot, then making additional edit to the database state, 
I then followed the first set of instructions at ``docs/sop/RESTORE_DATABASE_AWS_SNAPSHOT.md``:


* In the prerequisite (that should be first step I reckon), about that instruction:
 >Check both these options

In the context of what I am testing (user initiated snapshots), that instruction is not required.
Keeping both checkboxes unchecked will still preserve both manually created snapshots and previous final snapshots.

It may be worth adding a short explanation on what we gain by checking those two check boxes (ability to choose automated backups and system generated snapshots for one, and the same for the current final snapshot for the other, as possible sources to restore).


* In steps 16, there is this text "started 8.10 pm" which looks spurious to me, as I'm seeing nothing of the sort on the Databases page. I'm just seeing my new instance with status progressing through ``Creating -> Modifying -> Available``.

* In steps 17, strangely the two tags that we need are already there (that wasn't the case with SOP ``docs/sop/RESTORE_DATABASE_AWS_BACKUP.md``)

 
Beside the above points, the restoration completed fine.

**Review by rija — COMMENTED** [review]
Finally, testing the second set (terminal based) of instructions in ``docs/sop/RESTORE_DATABASE_AWS_SNAPSHOT.md``:

* Step 1, 2 and 3: 

Since we are meant to use the terminal, I think it's more appropriate to use command line to get list of snapshots:

```
$ aws rds describe-db-snapshots
```

where the key information is the value of the "DBSnapshotIdentifier" key for the snapshot we want to use.
There is also a "TagList" key that show that the important tags are preserved.


* Step 6: 

Got this error

```
Error: Conflicting configuration arguments

  on .terraform/modules/rds.db/modules/db_instance/main.tf line 26, in resource "aws_db_instance" "this":
  26: resource "aws_db_instance" "this" {

"restore_to_point_in_time": conflicts with snapshot_identifier
```

Fixed it by removing the ``override.tf`` file. Maybe worth adding a note about this.


Also in step 6, is ``terraform refresh`` necessary? I didn't run it and it worked fine (and then tried again the whole set using a system generated snapshot and everything 
was still fine)

**Comment by pli888** [comment]
@rija Thanks for your comments. I've made all of the suggested changes.

**Review by rija — APPROVED** [review]
Hi @pli888,

The behaviour changes related to S3 backup workflow works fine on my local staging (backup, restore, name of backup file, scripts permissions).
Also saw the SOP for regular backup looks good now.

However the changes to snapshot SOP I mentioned in comment 

https://github.com/gigascience/gigadb-website/pull/1034#pullrequestreview-968046076

seem to have been overlooked?

Maybe the same for documenting passing the date to ``restore_database_from_s3_backup.sh`` script at end of  comment:

https://github.com/gigascience/gigadb-website/pull/1034#pullrequestreview-966487005


In any case I'm approving this PR as:
* those comments were fairly of minor impact or nota bene and can be added as amendment later.
* S3 workflow is the one that's going to be demoed

**Pull request merged**
